openapi: 3.1.0
info:
  title: oneroster.v1p2.v1
  description: API documentation for oneroster.v1p2.v1
  version: 1.0.0
servers:
  - url: https://localhost:8080
    description: Local API Server (TLS)
  - url: http://localhost:8080
    description: Local API Server (Cleartext)
paths: {}
components:
  schemas:
    oneroster.v1p2.v1.Credential:
      type: object
      properties:
        password:
          type:
            - string
            - "null"
          title: password
          description: Model Primitive Datatype = String. The password in this set of credentials. Care should be taken to ensure that no unencrypted value is revealed.
        type:
          type: string
          title: type
          description: Model Primitive Datatype = String. The type of credentials for the profile. This should be indicative of when this specific credential should be used.
        username:
          type: string
          title: username
          description: Model Primitive Datatype = NormalizedString. The username.
      title: Credential
      required:
        - type
        - username
      additionalProperties: false
      description: The container for a single set of credentials for an account.
security: []
