openapi: 3.1.0
info:
  title: oneroster.v1p2.v1
  description: API documentation for oneroster.v1p2.v1
  version: 1.0.0
servers:
  - url: https://localhost:8080
    description: Local API Server (TLS)
  - url: http://localhost:8080
    description: Local API Server (Cleartext)
paths: {}
components:
  schemas:
    oneroster.v1p2.v1.DeleteCourseRequest:
      type: object
      properties:
        sourcedId:
          type: string
          title: sourced_id
          minLength: 1
          description: OneRoster GUID of the course to mark deleted.
      title: DeleteCourseRequest
      additionalProperties: false
security: []
