openapi: 3.1.0
info:
  title: oneroster.v1p2.v1
  description: API documentation for oneroster.v1p2.v1
  version: 1.0.0
servers:
  - url: https://localhost:8080
    description: Local API Server (TLS)
  - url: http://localhost:8080
    description: Local API Server (Cleartext)
paths: {}
components:
  schemas:
    google.protobuf.ListValue:
      type: array
      items:
        $ref: '#/components/schemas/google.protobuf.Value'
      description: A JSON array whose elements may be any JSON value.
    google.protobuf.NullValue:
      type: string
      title: NullValue
      enum:
        - NULL_VALUE
      description: |-
        `NullValue` is a singleton enumeration to represent the null value for the
         `Value` type union.

         The JSON representation for `NullValue` is JSON `null`.
    google.protobuf.Struct:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/google.protobuf.Value'
      description: A JSON object whose property values may be any JSON value.
    google.protobuf.Timestamp:
      type: string
      examples:
        - "2023-01-15T01:30:15.01Z"
        - "2024-12-25T12:00:00Z"
      format: date-time
      description: A point in time in RFC 3339 format, with up to nanosecond precision. Output uses UTC (`Z`); input may use an offset from UTC.
    google.protobuf.Value:
      oneOf:
        - type: "null"
        - type: number
        - type: string
        - type: boolean
        - type: array
        - type: object
          additionalProperties: true
      description: 'Any JSON value: `null`, number, string, boolean, array, or object.'
    google.type.Date:
      type: object
      properties:
        year:
          type: integer
          title: year
          format: int32
          description: |-
            Year of the date. Must be from 1 to 9999, or 0 to specify a date without
             a year.
        month:
          type: integer
          title: month
          format: int32
          description: |-
            Month of a year. Must be from 1 to 12, or 0 to specify a year without a
             month and day.
        day:
          type: integer
          title: day
          format: int32
          description: |-
            Day of a month. Must be from 1 to 31 and valid for the year and month, or 0
             to specify a year by itself or a year and month where the day isn't
             significant.
      title: Date
      additionalProperties: false
      description: |-
        Represents a whole or partial calendar date, such as a birthday. The time of
         day and time zone are either specified elsewhere or are insignificant. The
         date is relative to the Gregorian Calendar. This can represent one of the
         following:

         * A full date, with non-zero year, month, and day values.
         * A month and day, with a zero year (for example, an anniversary).
         * A year on its own, with a zero month and a zero day.
         * A year and month, with a zero day (for example, a credit card expiration
           date).

         Related types:

         * [google.type.TimeOfDay][google.type.TimeOfDay]
         * [google.type.DateTime][google.type.DateTime]
         * [google.protobuf.Timestamp][google.protobuf.Timestamp]
    oneroster.v1p2.v1.AcadSessionGUIDRef:
      type: object
      properties:
        href:
          type: string
          title: href
          description: Model Primitive Datatype = AnyURI. The URI for the type of object being referenced.
        sourcedId:
          type: string
          title: sourced_id
          description: Model Primitive Datatype = String. The globally unique identifier of the object being referenced.
        type:
          type: string
          title: type
          enum:
            - "academicSession"
          description: The type of object being referenced i.e. an 'academicSession'.
          const: academicSession
      title: AcadSessionGUIDRef
      required:
        - href
        - sourcedId
      additionalProperties: false
      description: This is the container for reference to a OneRoster 'Academic Session' object that has an allocated sourcedId (GUID).
    oneroster.v1p2.v1.AcademicSession:
      type: object
      properties:
        children:
          type: array
          items:
            $ref: '#/components/schemas/oneroster.v1p2.v1.AcadSessionGUIDRef'
          title: children
          description: The set of links to the child AcademicSessions i.e. a set of AcademicSession 'sourcedIds'.
        dateLastModified:
          allOf:
            - $ref: '#/components/schemas/google.protobuf.Timestamp'
          title: date_last_modified
          description: Model Primitive Datatype = DateTime. All objects MUST be annotated with the dateTime upon which they were last modified. This enables requesters to query for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO 8601] and MUST contain the UTC timezone.
        endDate:
          type: string
          title: end_date
          format: date
          description: Model Primitive Datatype = Date. The end date for the academic session. The end date is excluded from the academic session. This is in [ISO 8601] format of 'YYYY-MM-DD'.
        metadata:
          allOf:
            - $ref: '#/components/schemas/google.protobuf.Struct'
          title: metadata
          description: All objects CAN be extended using the Metadata class. This specification is silent on what implementers may consider to be appropriate extensions. The form of the extension is dependent on the binding technology being used.
        parent:
          allOf:
            - $ref: '#/components/schemas/oneroster.v1p2.v1.AcadSessionGUIDRef'
          title: parent
          description: The link to parent AcademicSession i.e. an AcademicSession 'sourcedId'.
        schoolYear:
          type: string
          title: school_year
          description: Model Primitive Datatype = NormalizedString. The school year for the academic session. This year should include the school year end e.g. 2014. This is in the [ISO 8601] format of 'YYYY'.
        sourcedId:
          type: string
          title: sourced_id
          description: Model Primitive Datatype = String. The sourcedId of the object. All objects MUST be identified by a Source Identifier. This is a GUID System ID for an object. This is the GUID that SYSTEMS will refer to when making API calls, or when needing to identify an object. It is RECOMMENDED that systems are able to map whichever local ids (e.g. database key fields) they use to SourcedId. The sourcedId of an object is considered an addressable property of an entity and as such will not be treated as Personally Identifiable Information (PII) by certified products. Therefore, as a part of certification, vendors will be required to declare that they will notify customers via documentation or other formal and documented agreement that sourcedIds should never contain PII in general, but particularly users. This means that if a customer includes a student name in an enrollment.sourcedId, it will not fall to any certified product to protect the enrollment.sourcedId as PII, or even the userSourcedId field in the enrollment record.
        startDate:
          type: string
          title: start_date
          format: date
          description: Model Primitive Datatype = Date. The start date for the academic session. The start date is included in the academic session. This is in [ISO 8601] format of 'YYYY-MM-DD'.
        status:
          type: string
          title: status
          enum:
            - "active"
            - "tobedeleted"
          description: All objects MUST BE either 'active' or 'tobedeleted'. Something which is flagged 'tobedeleted' is to be considered safe to delete. Systems can delete records that are flagged as such if they wish, but they are not under any compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed and so for backwards compatibility all such marked objects should be interpreted as 'tobedeleted'.
        title:
          type: string
          title: title
          description: Model Primitive Datatype = NormalizedString. The title/label for the academic session.
        type:
          type: string
          anyOf:
            - type: string
              enum:
                - "gradingPeriod"
                - "semester"
                - "schoolYear"
                - "term"
            - type: string
              pattern: (ext:)[a-zA-Z0-9\.\-_]+
          title: type
          description: The type of academic session. This is based upon an enumerated vocabulary.
      title: AcademicSession
      required:
        - dateLastModified
        - endDate
        - schoolYear
        - sourcedId
        - startDate
        - title
        - type
      additionalProperties: false
      description: The container for an academicSession. An academicSession represents a duration of time. Typically they are used to describe terms, grading periods, and other durations e.g. school years. Term is used to describe a period of time during which learning will take place. Other words for term could be in common use around the world e.g. Semester. The important thing is that Term is a unit of time, often many weeks long, into which classes are scheduled. Grading Period is used to represent another unit of time, that within which line items are assessed. A term may have many grading periods, a grading period belongs to a single term. A class may be assessed over several grade periods (represented by a line item being connected to a grading period). The parent / child attributes of academic sessions allow terms to be connected to their grading periods and vice-versa.
    oneroster.v1p2.v1.GetAllTermsResponse:
      type: object
      properties:
        academicSessions:
          type: array
          items:
            $ref: '#/components/schemas/oneroster.v1p2.v1.AcademicSession'
          title: academic_sessions
          description: The collection of academicSession instances. The order is not significant. The corresponding query constraints may result in no instances being returned.
        nextPageToken:
          type: string
          title: next_page_token
          description: Page token for the next page, empty when this is the last page.
      title: GetAllTermsResponse
      additionalProperties: false
      description: Author-Colin Smythe (1EdTech); Version-1.2; Release Date-19th September 2022.
security: []
