// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package onerosterjson

import (
	"encoding/json"
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/atombender/go-jsonschema/pkg/types"
	"github.com/go-viper/mapstructure/v2"

	"github.com/StevenACoffman/toerr/errors"
)

// This is the container for reference to a OneRoster 'Academic Session' object
// that has an allocated sourcedId (GUID).
type AcadSessionGUIDRefDType struct {
	// Model Primitive Datatype = AnyURI. The URI for the type of object being
	// referenced.
	Href string `json:"href" yaml:"href" mapstructure:"href"`

	// Model Primitive Datatype = String. The globally unique identifier of the object
	// being referenced.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// The type of object being referenced i.e. an 'academicSession'.
	Type AcadSessionGUIDRefDTypeType `json:"type" yaml:"type" mapstructure:"type"`
}

type AcadSessionGUIDRefDTypeType string

const AcadSessionGUIDRefDTypeTypeAcademicSession AcadSessionGUIDRefDTypeType = "academicSession"

var enumValues_AcadSessionGUIDRefDTypeType = []any{
	"academicSession",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AcadSessionGUIDRefDTypeType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AcadSessionGUIDRefDTypeType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_AcadSessionGUIDRefDTypeType,
			v,
		)
	}
	*j = AcadSessionGUIDRefDTypeType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AcadSessionGUIDRefDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["href"]; raw != nil && !ok {
		return errors.New("field href in AcadSessionGUIDRefDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in AcadSessionGUIDRefDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in AcadSessionGUIDRefDType: required")
	}
	type Plain AcadSessionGUIDRefDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AcadSessionGUIDRefDType(plain)
	return nil
}

// The container for an academicSession. An academicSession represents a duration
// of time. Typically they are used to describe terms, grading periods, and other
// durations e.g. school years. Term is used to describe a period of time during
// which learning will take place. Other words for term could be in common use
// around the world e.g. Semester. The important thing is that Term is a unit of
// time, often many weeks long, into which classes are scheduled. Grading Period is
// used to represent another unit of time, that within which line items are
// assessed. A term may have many grading periods, a grading period belongs to a
// single term. A class may be assessed over several grade periods (represented by
// a line item being connected to a grading period). The parent / child attributes
// of academic sessions allow terms to be connected to their grading periods and
// vice-versa.
type AcademicSessionDType struct {
	// The set of links to the child AcademicSessions i.e. a set of AcademicSession
	// 'sourcedIds'.
	Children []AcadSessionGUIDRefDType `json:"children,omitempty" yaml:"children,omitempty" mapstructure:"children,omitempty"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Model Primitive Datatype = Date. The end date for the academic session. The end
	// date is excluded from the academic session. This is in [ISO 8601] format of
	// 'YYYY-MM-DD'.
	EndDate types.SerializableDate `json:"endDate" yaml:"endDate" mapstructure:"endDate"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// The link to parent AcademicSession i.e. an AcademicSession 'sourcedId'.
	Parent *AcadSessionGUIDRefDType `json:"parent,omitempty" yaml:"parent,omitempty" mapstructure:"parent,omitempty"`

	// Model Primitive Datatype = NormalizedString. The school year for the academic
	// session.  This year should include the school year end e.g. 2014. This is in
	// the [ISO 8601] format of 'YYYY'.
	SchoolYear string `json:"schoolYear" yaml:"schoolYear" mapstructure:"schoolYear"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// Model Primitive Datatype = Date. The start date for the academic session. The
	// start date is included in the academic session. This is in [ISO 8601] format of
	// 'YYYY-MM-DD'.
	StartDate types.SerializableDate `json:"startDate" yaml:"startDate" mapstructure:"startDate"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status AcademicSessionDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Model Primitive Datatype = NormalizedString. The title/label for the academic
	// session.
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// The type of academic session. This is based upon an enumerated vocabulary.
	Type any `json:"type" yaml:"type" mapstructure:"type"`
}

type AcademicSessionDTypeStatus string

const (
	AcademicSessionDTypeStatusActive      AcademicSessionDTypeStatus = "active"
	AcademicSessionDTypeStatusTobedeleted AcademicSessionDTypeStatus = "tobedeleted"
)

var enumValues_AcademicSessionDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AcademicSessionDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AcademicSessionDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_AcademicSessionDTypeStatus,
			v,
		)
	}
	*j = AcademicSessionDTypeStatus(v)
	return nil
}

type AcademicSessionDTypeType_0 string

const (
	AcademicSessionDTypeType_0_GradingPeriod AcademicSessionDTypeType_0 = "gradingPeriod"
	AcademicSessionDTypeType_0_SchoolYear    AcademicSessionDTypeType_0 = "schoolYear"
	AcademicSessionDTypeType_0_Semester      AcademicSessionDTypeType_0 = "semester"
	AcademicSessionDTypeType_0_Term          AcademicSessionDTypeType_0 = "term"
)

var enumValues_AcademicSessionDTypeType_0 = []any{
	"gradingPeriod",
	"semester",
	"schoolYear",
	"term",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AcademicSessionDTypeType_0) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AcademicSessionDTypeType_0 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_AcademicSessionDTypeType_0,
			v,
		)
	}
	*j = AcademicSessionDTypeType_0(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AcademicSessionDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in AcademicSessionDType: required")
	}
	if _, ok := raw["endDate"]; raw != nil && !ok {
		return errors.New("field endDate in AcademicSessionDType: required")
	}
	if _, ok := raw["schoolYear"]; raw != nil && !ok {
		return errors.New("field schoolYear in AcademicSessionDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in AcademicSessionDType: required")
	}
	if _, ok := raw["startDate"]; raw != nil && !ok {
		return errors.New("field startDate in AcademicSessionDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in AcademicSessionDType: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return errors.New("field title in AcademicSessionDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in AcademicSessionDType: required")
	}
	type Plain AcademicSessionDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AcademicSessionDType(plain)
	return nil
}

// A class is an instance of a course, onto which students and teachers are
// enrolled. A class is typically held within a term.
type ClassDType struct {
	// Model Primitive Datatype = NormalizedString. The class code.
	ClassCode *string `json:"classCode,omitempty" yaml:"classCode,omitempty" mapstructure:"classCode,omitempty"`

	// The type of class. This is based upon an enumerated vocabulary.
	ClassType any `json:"classType,omitempty" yaml:"classType,omitempty" mapstructure:"classType,omitempty"`

	// The link to the associated course i.e. the Course 'sourcedId'.
	Course CourseGUIDRefDType `json:"course" yaml:"course" mapstructure:"course"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Model Primitive Datatype = NormalizedString. The grade(s) who attend the class.
	// The permitted vocabulary should be defined as part of the adoption and
	// deployment process. See the Implementation Guide [OR-IMPL-12] for more details
	// on how to define/use such a vocabulary.
	Grades []string `json:"grades,omitempty" yaml:"grades,omitempty" mapstructure:"grades,omitempty"`

	// Model Primitive Datatype = NormalizedString. The location for the class e.g.
	// 'Room 19'.
	Location *string `json:"location,omitempty" yaml:"location,omitempty" mapstructure:"location,omitempty"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// Model Primitive Datatype = NormalizedString. The time slots in the day that the
	// class will be given. Examples are 1 or a list of 1, 3, 5, etc.
	Periods []string `json:"periods,omitempty" yaml:"periods,omitempty" mapstructure:"periods,omitempty"`

	// The links to the set of associated resources i.e. the Resource 'sourcedIds'.
	Resources []ResourceGUIDRefDType `json:"resources,omitempty" yaml:"resources,omitempty" mapstructure:"resources,omitempty"`

	// The link to the associated school i.e. the School 'sourcedId'.
	School OrgGUIDRefDType `json:"school" yaml:"school" mapstructure:"school"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status ClassDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Model Primitive Datatype = NormalizedString. This is a machine readable set of
	// codes and the number should match the associated 'subjects' attribute. The
	// vocabulary for this characteristic should be defined as part of the local
	// addition of this specification (see the Implementation Guide [OR-IMPL-12] for
	// more details).
	SubjectCodes []string `json:"subjectCodes,omitempty" yaml:"subjectCodes,omitempty" mapstructure:"subjectCodes,omitempty"`

	// Model Primitive Datatype = NormalizedString. The set of subjects addressed by
	// this class e.g. 'chemistry'.
	Subjects []string `json:"subjects,omitempty" yaml:"subjects,omitempty" mapstructure:"subjects,omitempty"`

	// The links to the set of terms or semesters (academicSession) i.e. the set of
	// 'sourcedIds' for the terms within the associated school year.
	Terms []AcadSessionGUIDRefDType `json:"terms" yaml:"terms" mapstructure:"terms"`

	// Model Primitive Datatype = NormalizedString. The tile/label for the class.
	Title string `json:"title" yaml:"title" mapstructure:"title"`
}

type ClassDTypeClassType_0 string

const (
	ClassDTypeClassType_0_Homeroom  ClassDTypeClassType_0 = "homeroom"
	ClassDTypeClassType_0_Scheduled ClassDTypeClassType_0 = "scheduled"
)

var enumValues_ClassDTypeClassType_0 = []any{
	"homeroom",
	"scheduled",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClassDTypeClassType_0) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ClassDTypeClassType_0 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_ClassDTypeClassType_0,
			v,
		)
	}
	*j = ClassDTypeClassType_0(v)
	return nil
}

type ClassDTypeStatus string

const (
	ClassDTypeStatusActive      ClassDTypeStatus = "active"
	ClassDTypeStatusTobedeleted ClassDTypeStatus = "tobedeleted"
)

var enumValues_ClassDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClassDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ClassDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_ClassDTypeStatus,
			v,
		)
	}
	*j = ClassDTypeStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClassDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["course"]; raw != nil && !ok {
		return errors.New("field course in ClassDType: required")
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in ClassDType: required")
	}
	if _, ok := raw["school"]; raw != nil && !ok {
		return errors.New("field school in ClassDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in ClassDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in ClassDType: required")
	}
	if _, ok := raw["terms"]; raw != nil && !ok {
		return errors.New("field terms in ClassDType: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return errors.New("field title in ClassDType: required")
	}
	type Plain ClassDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Terms != nil && len(plain.Terms) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "terms", 1)
	}
	*j = ClassDType(plain)
	return nil
}

// This is the container for reference to a OneRoster 'Class' object that has an
// allocated sourcedId (GUID).
type ClassGUIDRefDType struct {
	// Model Primitive Datatype = AnyURI. The URI for the type of object being
	// referenced.
	Href string `json:"href" yaml:"href" mapstructure:"href"`

	// Model Primitive Datatype = String. The globally unique identifier of the object
	// being referenced.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// The type of object being referenced i.e. a 'class'.
	Type ClassGUIDRefDTypeType `json:"type" yaml:"type" mapstructure:"type"`
}

type ClassGUIDRefDTypeType string

const ClassGUIDRefDTypeTypeClass ClassGUIDRefDTypeType = "class"

var enumValues_ClassGUIDRefDTypeType = []any{
	"class",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClassGUIDRefDTypeType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ClassGUIDRefDTypeType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_ClassGUIDRefDTypeType,
			v,
		)
	}
	*j = ClassGUIDRefDTypeType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClassGUIDRefDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["href"]; raw != nil && !ok {
		return errors.New("field href in ClassGUIDRefDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in ClassGUIDRefDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in ClassGUIDRefDType: required")
	}
	type Plain ClassGUIDRefDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ClassGUIDRefDType(plain)
	return nil
}

// The information about a course. A Course is a course of study that, typically,
// has a shared curriculum although it may be taught to different students by
// different teachers. It is likely that several classes of a single course may be
// taught in a term. For example, a school runs Grade 9 English in the spring term.
// There are four classes, each with a different 30 students, taught by 4 different
// teachers. However the curriculum for each of those four classes is the same i.e.
// the course curriculum.
type CourseDType struct {
	// Model Primitive Datatype = NormalizedString. The assigned course code.
	CourseCode string `json:"courseCode" yaml:"courseCode" mapstructure:"courseCode"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Model Primitive Datatype = NormalizedString. Grade(s) for which the class is
	// attended. The permitted vocabulary should be defined as part of the adoption
	// and deployment process. See the Implementation Guide [OR-IMPL-12] for more
	// details on how to define/use such a vocabulary.
	Grades []string `json:"grades,omitempty" yaml:"grades,omitempty" mapstructure:"grades,omitempty"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// The link to org i.e. the 'sourcedId' of the org.
	Org *OrgGUIDRefDType `json:"org,omitempty" yaml:"org,omitempty" mapstructure:"org,omitempty"`

	// The links to the associated resources if applicable i.e. the resource
	// 'sourcedIds'.
	Resources []ResourceGUIDRefDType `json:"resources,omitempty" yaml:"resources,omitempty" mapstructure:"resources,omitempty"`

	// The link to academicSession i.e. the AcademicSession 'sourcedId'.
	SchoolYear *AcadSessionGUIDRefDType `json:"schoolYear,omitempty" yaml:"schoolYear,omitempty" mapstructure:"schoolYear,omitempty"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status CourseDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Model Primitive Datatype = NormalizedString. This is a machine readable set of
	// codes and the number should match the associated 'subjects' attribute. The
	// vocabulary for this characteristic should be defined as part of the local
	// addition of this specification (see the Implementation Guide [OR-IMPL-12] for
	// more details).
	SubjectCodes []string `json:"subjectCodes,omitempty" yaml:"subjectCodes,omitempty" mapstructure:"subjectCodes,omitempty"`

	// Model Primitive Datatype = NormalizedString. The set of subjects addresse by
	// this course. This is a set of human readable strings.
	Subjects []string `json:"subjects,omitempty" yaml:"subjects,omitempty" mapstructure:"subjects,omitempty"`

	// Model Primitive Datatype = NormalizedString. The title of the course.
	Title string `json:"title" yaml:"title" mapstructure:"title"`
}

type CourseDTypeStatus string

const (
	CourseDTypeStatusActive      CourseDTypeStatus = "active"
	CourseDTypeStatusTobedeleted CourseDTypeStatus = "tobedeleted"
)

var enumValues_CourseDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CourseDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CourseDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_CourseDTypeStatus,
			v,
		)
	}
	*j = CourseDTypeStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CourseDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["courseCode"]; raw != nil && !ok {
		return errors.New("field courseCode in CourseDType: required")
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in CourseDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in CourseDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in CourseDType: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return errors.New("field title in CourseDType: required")
	}
	type Plain CourseDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CourseDType(plain)
	return nil
}

// This is the container for reference to a OneRoster 'Course' object that has an
// allocated sourcedId (GUID).
type CourseGUIDRefDType struct {
	// Model Primitive Datatype = AnyURI. The URI for the type of object being
	// referenced.
	Href string `json:"href" yaml:"href" mapstructure:"href"`

	// Model Primitive Datatype = String. The globally unique identifier of the object
	// being referenced.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// The type of object being referenced i.e. a 'course'.
	Type CourseGUIDRefDTypeType `json:"type" yaml:"type" mapstructure:"type"`
}

type CourseGUIDRefDTypeType string

const CourseGUIDRefDTypeTypeCourse CourseGUIDRefDTypeType = "course"

var enumValues_CourseGUIDRefDTypeType = []any{
	"course",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CourseGUIDRefDTypeType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CourseGUIDRefDTypeType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_CourseGUIDRefDTypeType,
			v,
		)
	}
	*j = CourseGUIDRefDTypeType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CourseGUIDRefDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["href"]; raw != nil && !ok {
		return errors.New("field href in CourseGUIDRefDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in CourseGUIDRefDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in CourseGUIDRefDType: required")
	}
	type Plain CourseGUIDRefDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CourseGUIDRefDType(plain)
	return nil
}

// The container for a single set of credentials for an account.
type CredentialDType struct {
	// Model Primitive Datatype = String. The password in this set of credentials.
	// Care should be taken to ensure that no unencrypted value is revealed.
	Password *string `json:"password,omitempty" yaml:"password,omitempty" mapstructure:"password,omitempty"`

	// Model Primitive Datatype = String. The type of credentials for the profile.
	// This should be indicative of when this specific credential should be used.
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// Model Primitive Datatype = NormalizedString. The username.
	Username string `json:"username" yaml:"username" mapstructure:"username"`

	AdditionalProperties any `mapstructure:"remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CredentialDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in CredentialDType: required")
	}
	if _, ok := raw["username"]; raw != nil && !ok {
		return errors.New("field username in CredentialDType: required")
	}
	type Plain CredentialDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = CredentialDType(plain)
	return nil
}

// Demographics information is taken from the Common Educational Data Standards
// (CEDS) from the US government. (http://ceds.ed.gov). Note that demographics data
// is held in its own service, and that access to this service is considered
// privileged. Not all consumer keys will be able to request demographics data.
type DemographicsDType struct {
	// Identification of whether or not the user is an American Indian or Alaska
	// Native ethnicity.
	AmericanIndianOrAlaskaNative *DemographicsDTypeAmericanIndianOrAlaskaNative `json:"americanIndianOrAlaskaNative,omitempty" yaml:"americanIndianOrAlaskaNative,omitempty" mapstructure:"americanIndianOrAlaskaNative,omitempty"`

	// Identification of whether or not the user is of Asian ethnicity.
	Asian *DemographicsDTypeAsian `json:"asian,omitempty" yaml:"asian,omitempty" mapstructure:"asian,omitempty"`

	// Model Primitive Datatype = Date. the date of birth. The format is [ISO 8601] of
	// 'YYYY-MM-DD'.
	BirthDate *types.SerializableDate `json:"birthDate,omitempty" yaml:"birthDate,omitempty" mapstructure:"birthDate,omitempty"`

	// Identification of whether or not the user is black or African American
	// ethnicity.
	BlackOrAfricanAmerican *DemographicsDTypeBlackOrAfricanAmerican `json:"blackOrAfricanAmerican,omitempty" yaml:"blackOrAfricanAmerican,omitempty" mapstructure:"blackOrAfricanAmerican,omitempty"`

	// Model Primitive Datatype = NormalizedString. The name of the city in which the
	// user was born.
	CityOfBirth *string `json:"cityOfBirth,omitempty" yaml:"cityOfBirth,omitempty" mapstructure:"cityOfBirth,omitempty"`

	// Model Primitive Datatype = NormalizedString. The country of birth code. The
	// permitted vocabulary should be defined as part of the adoption and deployment
	// process. See the Implementation Guide [OR-IMPL-12] for more details on how to
	// define/use such a vocabulary.
	CountryOfBirthCode *string `json:"countryOfBirthCode,omitempty" yaml:"countryOfBirthCode,omitempty" mapstructure:"countryOfBirthCode,omitempty"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Identification of whether or not the user has a demographic of two or more race
	// ethnicities.
	DemographicRaceTwoOrMoreRaces *DemographicsDTypeDemographicRaceTwoOrMoreRaces `json:"demographicRaceTwoOrMoreRaces,omitempty" yaml:"demographicRaceTwoOrMoreRaces,omitempty" mapstructure:"demographicRaceTwoOrMoreRaces,omitempty"`

	// Identification of whether or not the user is Hispanic or of Latino ethnicity.
	HispanicOrLatinoEthnicity *DemographicsDTypeHispanicOrLatinoEthnicity `json:"hispanicOrLatinoEthnicity,omitempty" yaml:"hispanicOrLatinoEthnicity,omitempty" mapstructure:"hispanicOrLatinoEthnicity,omitempty"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// Identification of whether or not the user is Native Hawaiian or Other Pacific
	// Islander ethnicity.
	NativeHawaiianOrOtherPacificIslander *DemographicsDTypeNativeHawaiianOrOtherPacificIslander `json:"nativeHawaiianOrOtherPacificIslander,omitempty" yaml:"nativeHawaiianOrOtherPacificIslander,omitempty" mapstructure:"nativeHawaiianOrOtherPacificIslander,omitempty"`

	// Model Primitive Datatype = NormalizedString. An indication of the location of a
	// person's legal residence relative to (within or outside) the boundaries of the
	// public school attended and its administrative unit. The permitted vocabulary
	// should be defined as part of the adoption and deployment process. See the
	// Implementation Guide [OR-IMPL-12] for more details on how to define/use such a
	// vocabulary.
	PublicSchoolResidenceStatus *string `json:"publicSchoolResidenceStatus,omitempty" yaml:"publicSchoolResidenceStatus,omitempty" mapstructure:"publicSchoolResidenceStatus,omitempty"`

	// The sex of the individual. The permitted values are from an enumerated list.
	Sex any `json:"sex,omitempty" yaml:"sex,omitempty" mapstructure:"sex,omitempty"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// Model Primitive Datatype = NormalizedString. The abbreviation for the name of
	// the state (within the United States) or extra-state jurisdiction in which a
	// person was born. The permitted vocabulary should be defined as part of the
	// adoption and deployment process. See the Implementation Guide [OR-IMPL-12] for
	// more details on how to define/use such a vocabulary.
	StateOfBirthAbbreviation *string `json:"stateOfBirthAbbreviation,omitempty" yaml:"stateOfBirthAbbreviation,omitempty" mapstructure:"stateOfBirthAbbreviation,omitempty"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status DemographicsDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Identification of whether or not the user is of white ethnicity.
	White *DemographicsDTypeWhite `json:"white,omitempty" yaml:"white,omitempty" mapstructure:"white,omitempty"`
}

type DemographicsDTypeAmericanIndianOrAlaskaNative string

const (
	DemographicsDTypeAmericanIndianOrAlaskaNativeFalse DemographicsDTypeAmericanIndianOrAlaskaNative = "false"
	DemographicsDTypeAmericanIndianOrAlaskaNativeTrue  DemographicsDTypeAmericanIndianOrAlaskaNative = "true"
)

var enumValues_DemographicsDTypeAmericanIndianOrAlaskaNative = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeAmericanIndianOrAlaskaNative) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeAmericanIndianOrAlaskaNative {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeAmericanIndianOrAlaskaNative,
			v,
		)
	}
	*j = DemographicsDTypeAmericanIndianOrAlaskaNative(v)
	return nil
}

type DemographicsDTypeAsian string

const (
	DemographicsDTypeAsianFalse DemographicsDTypeAsian = "false"
	DemographicsDTypeAsianTrue  DemographicsDTypeAsian = "true"
)

var enumValues_DemographicsDTypeAsian = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeAsian) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeAsian {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeAsian,
			v,
		)
	}
	*j = DemographicsDTypeAsian(v)
	return nil
}

type DemographicsDTypeBlackOrAfricanAmerican string

const (
	DemographicsDTypeBlackOrAfricanAmericanFalse DemographicsDTypeBlackOrAfricanAmerican = "false"
	DemographicsDTypeBlackOrAfricanAmericanTrue  DemographicsDTypeBlackOrAfricanAmerican = "true"
)

var enumValues_DemographicsDTypeBlackOrAfricanAmerican = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeBlackOrAfricanAmerican) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeBlackOrAfricanAmerican {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeBlackOrAfricanAmerican,
			v,
		)
	}
	*j = DemographicsDTypeBlackOrAfricanAmerican(v)
	return nil
}

type DemographicsDTypeDemographicRaceTwoOrMoreRaces string

const (
	DemographicsDTypeDemographicRaceTwoOrMoreRacesFalse DemographicsDTypeDemographicRaceTwoOrMoreRaces = "false"
	DemographicsDTypeDemographicRaceTwoOrMoreRacesTrue  DemographicsDTypeDemographicRaceTwoOrMoreRaces = "true"
)

var enumValues_DemographicsDTypeDemographicRaceTwoOrMoreRaces = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeDemographicRaceTwoOrMoreRaces) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeDemographicRaceTwoOrMoreRaces {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeDemographicRaceTwoOrMoreRaces,
			v,
		)
	}
	*j = DemographicsDTypeDemographicRaceTwoOrMoreRaces(v)
	return nil
}

type DemographicsDTypeHispanicOrLatinoEthnicity string

const (
	DemographicsDTypeHispanicOrLatinoEthnicityFalse DemographicsDTypeHispanicOrLatinoEthnicity = "false"
	DemographicsDTypeHispanicOrLatinoEthnicityTrue  DemographicsDTypeHispanicOrLatinoEthnicity = "true"
)

var enumValues_DemographicsDTypeHispanicOrLatinoEthnicity = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeHispanicOrLatinoEthnicity) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeHispanicOrLatinoEthnicity {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeHispanicOrLatinoEthnicity,
			v,
		)
	}
	*j = DemographicsDTypeHispanicOrLatinoEthnicity(v)
	return nil
}

type DemographicsDTypeNativeHawaiianOrOtherPacificIslander string

const (
	DemographicsDTypeNativeHawaiianOrOtherPacificIslanderFalse DemographicsDTypeNativeHawaiianOrOtherPacificIslander = "false"
	DemographicsDTypeNativeHawaiianOrOtherPacificIslanderTrue  DemographicsDTypeNativeHawaiianOrOtherPacificIslander = "true"
)

var enumValues_DemographicsDTypeNativeHawaiianOrOtherPacificIslander = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeNativeHawaiianOrOtherPacificIslander) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeNativeHawaiianOrOtherPacificIslander {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeNativeHawaiianOrOtherPacificIslander,
			v,
		)
	}
	*j = DemographicsDTypeNativeHawaiianOrOtherPacificIslander(v)
	return nil
}

type DemographicsDTypeSex_0 string

const (
	DemographicsDTypeSex_0_Female      DemographicsDTypeSex_0 = "female"
	DemographicsDTypeSex_0_Male        DemographicsDTypeSex_0 = "male"
	DemographicsDTypeSex_0_Other       DemographicsDTypeSex_0 = "other"
	DemographicsDTypeSex_0_Unspecified DemographicsDTypeSex_0 = "unspecified"
)

var enumValues_DemographicsDTypeSex_0 = []any{
	"male",
	"female",
	"unspecified",
	"other",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeSex_0) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeSex_0 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeSex_0,
			v,
		)
	}
	*j = DemographicsDTypeSex_0(v)
	return nil
}

type DemographicsDTypeStatus string

const (
	DemographicsDTypeStatusActive      DemographicsDTypeStatus = "active"
	DemographicsDTypeStatusTobedeleted DemographicsDTypeStatus = "tobedeleted"
)

var enumValues_DemographicsDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeStatus,
			v,
		)
	}
	*j = DemographicsDTypeStatus(v)
	return nil
}

type DemographicsDTypeWhite string

const (
	DemographicsDTypeWhiteFalse DemographicsDTypeWhite = "false"
	DemographicsDTypeWhiteTrue  DemographicsDTypeWhite = "true"
)

var enumValues_DemographicsDTypeWhite = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeWhite) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeWhite {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeWhite,
			v,
		)
	}
	*j = DemographicsDTypeWhite(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in DemographicsDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in DemographicsDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in DemographicsDType: required")
	}
	type Plain DemographicsDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DemographicsDType(plain)
	return nil
}

// An enrollment is the name given to an individual taking part in a class. In the
// vast majority of cases, users will be students learning in a class, or teachers
// teaching the class. Other roles are also possible.
type EnrollmentDType struct {
	// Model Primitive Datatype = Date. The start date for the enrollment (inclusive).
	// This date must be within the period of the associated Academic Session for the
	// class (Term/Semester/SchoolYear). Use the [ISO 8601] format of 'YYYY-MM-DD'.
	BeginDate *types.SerializableDate `json:"beginDate,omitempty" yaml:"beginDate,omitempty" mapstructure:"beginDate,omitempty"`

	// The link to the class on which the user is enrolled i.e. the Class 'sourcedId'.
	Class ClassGUIDRefDType `json:"class" yaml:"class" mapstructure:"class"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Model Primitive Datatype = Date. The end date for the enrollment (exclusive).
	// This date must be within the period of the associated Academic Session for the
	// class (Term/Semester/SchoolYear). Use the [ISO 8601] format of 'YYYY-MM-DD'.
	EndDate *types.SerializableDate `json:"endDate,omitempty" yaml:"endDate,omitempty" mapstructure:"endDate,omitempty"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// Applicable only to teachers. Only one teacher should be designated as the
	// primary teacher for a class (this value set as 'true') in the period defined by
	// the begin/end dates.
	Primary *EnrollmentDTypePrimary `json:"primary,omitempty" yaml:"primary,omitempty" mapstructure:"primary,omitempty"`

	// The role of the user for this class in the school e.g teacher, student, etc.
	// This is from an enumerated vocabulary.
	Role any `json:"role" yaml:"role" mapstructure:"role"`

	// The link to the school at which the class is being provided i.e. an Org
	// 'sourcedId'.
	School OrgGUIDRefDType `json:"school" yaml:"school" mapstructure:"school"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status EnrollmentDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// The link to the enrolled User i.e. the User 'sourcedId'.
	User UserGUIDRefDType `json:"user" yaml:"user" mapstructure:"user"`
}

type EnrollmentDTypePrimary string

const (
	EnrollmentDTypePrimaryFalse EnrollmentDTypePrimary = "false"
	EnrollmentDTypePrimaryTrue  EnrollmentDTypePrimary = "true"
)

var enumValues_EnrollmentDTypePrimary = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnrollmentDTypePrimary) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnrollmentDTypePrimary {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_EnrollmentDTypePrimary,
			v,
		)
	}
	*j = EnrollmentDTypePrimary(v)
	return nil
}

type EnrollmentDTypeRole_0 string

const (
	EnrollmentDTypeRole_0_Administrator EnrollmentDTypeRole_0 = "administrator"
	EnrollmentDTypeRole_0_Proctor       EnrollmentDTypeRole_0 = "proctor"
	EnrollmentDTypeRole_0_Student       EnrollmentDTypeRole_0 = "student"
	EnrollmentDTypeRole_0_Teacher       EnrollmentDTypeRole_0 = "teacher"
)

var enumValues_EnrollmentDTypeRole_0 = []any{
	"administrator",
	"proctor",
	"student",
	"teacher",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnrollmentDTypeRole_0) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnrollmentDTypeRole_0 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_EnrollmentDTypeRole_0,
			v,
		)
	}
	*j = EnrollmentDTypeRole_0(v)
	return nil
}

type EnrollmentDTypeStatus string

const (
	EnrollmentDTypeStatusActive      EnrollmentDTypeStatus = "active"
	EnrollmentDTypeStatusTobedeleted EnrollmentDTypeStatus = "tobedeleted"
)

var enumValues_EnrollmentDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnrollmentDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnrollmentDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_EnrollmentDTypeStatus,
			v,
		)
	}
	*j = EnrollmentDTypeStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnrollmentDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["class"]; raw != nil && !ok {
		return errors.New("field class in EnrollmentDType: required")
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in EnrollmentDType: required")
	}
	if _, ok := raw["role"]; raw != nil && !ok {
		return errors.New("field role in EnrollmentDType: required")
	}
	if _, ok := raw["school"]; raw != nil && !ok {
		return errors.New("field school in EnrollmentDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in EnrollmentDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in EnrollmentDType: required")
	}
	if _, ok := raw["user"]; raw != nil && !ok {
		return errors.New("field user in EnrollmentDType: required")
	}
	type Plain EnrollmentDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = EnrollmentDType(plain)
	return nil
}

// The container for the proprietary extensions.
type MetadataDType map[string]any

// Composite roster response containing the full set of OneRoster v1.2 rostering
// collections.
type Onerosterrosteringservicev1P2Getroster200ResponsepayloadSchemav1P0Json struct {
	// An imaginary complete roster payload containing all OneRoster rostering
	// collections.
	Roster RosterDType `json:"roster" yaml:"roster" mapstructure:"roster"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Onerosterrosteringservicev1P2Getroster200ResponsepayloadSchemav1P0Json) UnmarshalJSON(
	value []byte,
) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["roster"]; raw != nil && !ok {
		return errors.New(
			"field roster in Onerosterrosteringservicev1P2Getroster200ResponsepayloadSchemav1P0Json: required",
		)
	}
	type Plain Onerosterrosteringservicev1P2Getroster200ResponsepayloadSchemav1P0Json
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = Onerosterrosteringservicev1P2Getroster200ResponsepayloadSchemav1P0Json(plain)
	return nil
}

// ORG is defined here as a structure for holding organizational information. An
// ORG might be a school, or it might be a local, statewide, or national entity.
// ORGs will typically have a parent ORG (up to the national level), and children,
// allowing a hierarchy to be established. School is defined here as the place
// where the learning happens. Most commonly this is the data that describes a
// bricks and mortar building, or, in the case of a virtual school, the virtual
// school organization. For enrollment and result reporting purposes, little
// information about this organization is required. A common example of a local
// organization is a school district.
type OrgDType struct {
	// The 'sourcedIds' for the set of child organizations.
	Children []OrgGUIDRefDType `json:"children,omitempty" yaml:"children,omitempty" mapstructure:"children,omitempty"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Model Primitive Datatype = String. Human readable identifier for this org e.g.
	// NCES ID.
	Identifier string `json:"identifier" yaml:"identifier" mapstructure:"identifier"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// Model Primitive Datatype = NormalizedString. The name of the organization.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// The 'sourcedId' of the parent organization.
	Parent *OrgGUIDRefDType `json:"parent,omitempty" yaml:"parent,omitempty" mapstructure:"parent,omitempty"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status OrgDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// The type of organization. This uses a predefined vocabulary.
	Type any `json:"type" yaml:"type" mapstructure:"type"`
}

type OrgDTypeStatus string

const (
	OrgDTypeStatusActive      OrgDTypeStatus = "active"
	OrgDTypeStatusTobedeleted OrgDTypeStatus = "tobedeleted"
)

var enumValues_OrgDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OrgDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OrgDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_OrgDTypeStatus,
			v,
		)
	}
	*j = OrgDTypeStatus(v)
	return nil
}

type OrgDTypeType_0 string

const (
	OrgDTypeType_0_Department OrgDTypeType_0 = "department"
	OrgDTypeType_0_District   OrgDTypeType_0 = "district"
	OrgDTypeType_0_Local      OrgDTypeType_0 = "local"
	OrgDTypeType_0_National   OrgDTypeType_0 = "national"
	OrgDTypeType_0_School     OrgDTypeType_0 = "school"
	OrgDTypeType_0_State      OrgDTypeType_0 = "state"
)

var enumValues_OrgDTypeType_0 = []any{
	"department",
	"district",
	"local",
	"national",
	"school",
	"state",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OrgDTypeType_0) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OrgDTypeType_0 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_OrgDTypeType_0,
			v,
		)
	}
	*j = OrgDTypeType_0(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OrgDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in OrgDType: required")
	}
	if _, ok := raw["identifier"]; raw != nil && !ok {
		return errors.New("field identifier in OrgDType: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return errors.New("field name in OrgDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in OrgDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in OrgDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in OrgDType: required")
	}
	type Plain OrgDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = OrgDType(plain)
	return nil
}

// This is the container for reference to a OneRoster 'Org' object that has an
// allocated sourcedId (GUID).
type OrgGUIDRefDType struct {
	// Model Primitive Datatype = AnyURI. The URI for the type of object being
	// referenced.
	Href string `json:"href" yaml:"href" mapstructure:"href"`

	// Model Primitive Datatype = String. The globally unique identifier of the object
	// being referenced.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// The type of object being referenced i.e. an 'org'.
	Type OrgGUIDRefDTypeType `json:"type" yaml:"type" mapstructure:"type"`
}

type OrgGUIDRefDTypeType string

const OrgGUIDRefDTypeTypeOrg OrgGUIDRefDTypeType = "org"

var enumValues_OrgGUIDRefDTypeType = []any{
	"org",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OrgGUIDRefDTypeType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OrgGUIDRefDTypeType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_OrgGUIDRefDTypeType,
			v,
		)
	}
	*j = OrgGUIDRefDTypeType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OrgGUIDRefDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["href"]; raw != nil && !ok {
		return errors.New("field href in OrgGUIDRefDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in OrgGUIDRefDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in OrgGUIDRefDType: required")
	}
	type Plain OrgGUIDRefDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = OrgGUIDRefDType(plain)
	return nil
}

// This is the container for reference to a OneRoster 'Resource' object that has an
// allocated sourcedId (GUID).
type ResourceGUIDRefDType struct {
	// Model Primitive Datatype = AnyURI. The URI for the type of object being
	// referenced.
	Href string `json:"href" yaml:"href" mapstructure:"href"`

	// Model Primitive Datatype = String. The globally unique identifier of the object
	// being referenced.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// The type of object being referenced i.e. a 'resource'.
	Type ResourceGUIDRefDTypeType `json:"type" yaml:"type" mapstructure:"type"`
}

type ResourceGUIDRefDTypeType string

const ResourceGUIDRefDTypeTypeResource ResourceGUIDRefDTypeType = "resource"

var enumValues_ResourceGUIDRefDTypeType = []any{
	"resource",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResourceGUIDRefDTypeType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ResourceGUIDRefDTypeType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_ResourceGUIDRefDTypeType,
			v,
		)
	}
	*j = ResourceGUIDRefDTypeType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResourceGUIDRefDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["href"]; raw != nil && !ok {
		return errors.New("field href in ResourceGUIDRefDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in ResourceGUIDRefDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in ResourceGUIDRefDType: required")
	}
	type Plain ResourceGUIDRefDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ResourceGUIDRefDType(plain)
	return nil
}

// The container for one mapping between a role and an org for the user.
type RoleDType struct {
	// Model Primitive Datatype = Date. The start date on which the role becomes
	// active (inclusive).
	BeginDate *types.SerializableDate `json:"beginDate,omitempty" yaml:"beginDate,omitempty" mapstructure:"beginDate,omitempty"`

	// Model Primitive Datatype = Date. The end date on which the role becomes
	// inactive (exclusive).
	EndDate *types.SerializableDate `json:"endDate,omitempty" yaml:"endDate,omitempty" mapstructure:"endDate,omitempty"`

	// The link to the associated org i.e. the 'sourcedId' for the org.
	Org OrgGUIDRefDType `json:"org" yaml:"org" mapstructure:"org"`

	// The role of the user in the org. The permitted values are from an enumerated
	// list.
	Role any `json:"role" yaml:"role" mapstructure:"role"`

	// Indicates if this role is the primary or secondary role for that org. There
	// MUST be one, and only one, primary role for each org.
	RoleType RoleDTypeRoleType `json:"roleType" yaml:"roleType" mapstructure:"roleType"`

	// Model Primitive Datatype = AnyURI. The identifier for the system/tool/app
	// access account that is relevant to this role in the org. The equivalent
	// UserProfile should exist with a 'profileId' equal to this identifier value.
	UserProfile *string `json:"userProfile,omitempty" yaml:"userProfile,omitempty" mapstructure:"userProfile,omitempty"`
}

type RoleDTypeRoleType string

const (
	RoleDTypeRoleTypePrimary   RoleDTypeRoleType = "primary"
	RoleDTypeRoleTypeSecondary RoleDTypeRoleType = "secondary"
)

var enumValues_RoleDTypeRoleType = []any{
	"primary",
	"secondary",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RoleDTypeRoleType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RoleDTypeRoleType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_RoleDTypeRoleType,
			v,
		)
	}
	*j = RoleDTypeRoleType(v)
	return nil
}

type RoleDTypeRole_0 string

const (
	RoleDTypeRole_0_Aide                  RoleDTypeRole_0 = "aide"
	RoleDTypeRole_0_Counselor             RoleDTypeRole_0 = "counselor"
	RoleDTypeRole_0_DistrictAdministrator RoleDTypeRole_0 = "districtAdministrator"
	RoleDTypeRole_0_Guardian              RoleDTypeRole_0 = "guardian"
	RoleDTypeRole_0_Parent                RoleDTypeRole_0 = "parent"
	RoleDTypeRole_0_Principal             RoleDTypeRole_0 = "principal"
	RoleDTypeRole_0_Proctor               RoleDTypeRole_0 = "proctor"
	RoleDTypeRole_0_Relative              RoleDTypeRole_0 = "relative"
	RoleDTypeRole_0_SiteAdministrator     RoleDTypeRole_0 = "siteAdministrator"
	RoleDTypeRole_0_Student               RoleDTypeRole_0 = "student"
	RoleDTypeRole_0_SystemAdministrator   RoleDTypeRole_0 = "systemAdministrator"
	RoleDTypeRole_0_Teacher               RoleDTypeRole_0 = "teacher"
)

var enumValues_RoleDTypeRole_0 = []any{
	"aide",
	"counselor",
	"districtAdministrator",
	"guardian",
	"parent",
	"principal",
	"proctor",
	"relative",
	"siteAdministrator",
	"student",
	"systemAdministrator",
	"teacher",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RoleDTypeRole_0) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RoleDTypeRole_0 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_RoleDTypeRole_0,
			v,
		)
	}
	*j = RoleDTypeRole_0(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RoleDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["org"]; raw != nil && !ok {
		return errors.New("field org in RoleDType: required")
	}
	if _, ok := raw["role"]; raw != nil && !ok {
		return errors.New("field role in RoleDType: required")
	}
	if _, ok := raw["roleType"]; raw != nil && !ok {
		return errors.New("field roleType in RoleDType: required")
	}
	type Plain RoleDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = RoleDType(plain)
	return nil
}

// A composite container for all OneRoster v1.2 rostering collections returned in a
// single response.
type RosterDType struct {
	// The collection of academicSession instances (includes terms, grading periods,
	// and school years). The order is not significant.
	AcademicSessions []AcademicSessionDType `json:"academicSessions,omitempty" yaml:"academicSessions,omitempty" mapstructure:"academicSessions,omitempty"`

	// The collection of class instances. The order is not significant.
	Classes []ClassDType `json:"classes,omitempty" yaml:"classes,omitempty" mapstructure:"classes,omitempty"`

	// The collection of course instances. The order is not significant.
	Courses []CourseDType `json:"courses,omitempty" yaml:"courses,omitempty" mapstructure:"courses,omitempty"`

	// The collection of demographics instances. The order is not significant.
	Demographics []DemographicsDType `json:"demographics,omitempty" yaml:"demographics,omitempty" mapstructure:"demographics,omitempty"`

	// The collection of enrollment instances. The order is not significant.
	Enrollments []EnrollmentDType `json:"enrollments,omitempty" yaml:"enrollments,omitempty" mapstructure:"enrollments,omitempty"`

	// The collection of org instances (includes schools and other organizations). The
	// order is not significant.
	Orgs []OrgDType `json:"orgs,omitempty" yaml:"orgs,omitempty" mapstructure:"orgs,omitempty"`

	// The collection of user instances (includes students, teachers, and all other
	// user roles). The order is not significant.
	Users []UserDType `json:"users,omitempty" yaml:"users,omitempty" mapstructure:"users,omitempty"`
}

// Users, Teachers and Students are human beings that are teaching or studying in a
// class respectively. A single User class is used to represent both teachers and
// students and a role property is used to distinguish a user's natural role.Humans
// may have relationships with other humans. For example, a student may have
// parents. The 'agents' attribute allows for relationships between humans to be
// expressed. Note that these are typically from the point of view of the student -
// so a student will link to its parents (via the agent attribute). The reverse
// view MUST also be modeled, so for example, a user of role 'parent' MUST have
// agents that are of type 'student'. Note: Teachers MUST NOT be set as agents of
// students i.e. the teaching relationship is covered via enrollments.
type UserDType struct {
	// The links to other people i.e. User 'sourcedIds'.
	Agents []UserGUIDRefDType `json:"agents,omitempty" yaml:"agents,omitempty" mapstructure:"agents,omitempty"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Model Primitive Datatype = NormalizedString. The email address for the user.
	Email *string `json:"email,omitempty" yaml:"email,omitempty" mapstructure:"email,omitempty"`

	// This is used to determine whether or not the record is active in the local
	// system. 'false' denotes that the record is active but system access is
	// curtailed according to the local administration rules.
	EnabledUser UserDTypeEnabledUser `json:"enabledUser" yaml:"enabledUser" mapstructure:"enabledUser"`

	// Model Primitive Datatype = NormalizedString. The family name. Also, known as
	// the last name.
	FamilyName string `json:"familyName" yaml:"familyName" mapstructure:"familyName"`

	// Model Primitive Datatype = NormalizedString. The given name. Also, known as the
	// first name.
	GivenName string `json:"givenName" yaml:"givenName" mapstructure:"givenName"`

	// Model Primitive Datatype = NormalizedString. Grade(s) for which a user with
	// role 'student' is enrolled. The permitted vocabulary should be defined as part
	// of the adoption and deployment process. See the Implementation Guide
	// [OR-IMPL-12] for more details on how to define/use such a vocabulary.
	Grades []string `json:"grades,omitempty" yaml:"grades,omitempty" mapstructure:"grades,omitempty"`

	// Model Primitive Datatype = String. An identifier for the user. NOTE - This
	// characteristic is kept for backwards compatibility with OneRoster 1.1/1.0. The
	// 'userIds' characteristic SHOULD be used instead.
	Identifier *string `json:"identifier,omitempty" yaml:"identifier,omitempty" mapstructure:"identifier,omitempty"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// Model Primitive Datatype = NormalizedString. The set of middle names. If more
	// than one middle name is needed separate using a space e.g. 'Wingarde
	// Granville'.
	MiddleName *string `json:"middleName,omitempty" yaml:"middleName,omitempty" mapstructure:"middleName,omitempty"`

	// Model Primitive Datatype = String. A top-level password for the user. Care
	// should be taken when using this field and the password SHOULD be encrypted.
	Password *string `json:"password,omitempty" yaml:"password,omitempty" mapstructure:"password,omitempty"`

	// Model Primitive Datatype = NormalizedString. The phone number for the user.
	Phone *string `json:"phone,omitempty" yaml:"phone,omitempty" mapstructure:"phone,omitempty"`

	// Model Primitive Datatype = NormalizedString. The user's preferred first name.
	// This attribute was added in version 1.2.
	PreferredFirstName *string `json:"preferredFirstName,omitempty" yaml:"preferredFirstName,omitempty" mapstructure:"preferredFirstName,omitempty"`

	// Model Primitive Datatype = NormalizedString. The user's preferred last name.
	// This attribute was added in version 1.2.
	PreferredLastName *string `json:"preferredLastName,omitempty" yaml:"preferredLastName,omitempty" mapstructure:"preferredLastName,omitempty"`

	// Model Primitive Datatype = NormalizedString. The user's preferred middle
	// name(s). This attribute was added in version 1.2.
	PreferredMiddleName *string `json:"preferredMiddleName,omitempty" yaml:"preferredMiddleName,omitempty" mapstructure:"preferredMiddleName,omitempty"`

	// It is possible for a user to be a member of more than one organization and to
	// have one or more roles in an organization. This attribute identifies the
	// 'sourcedId' of the primary organization.
	PrimaryOrg *OrgGUIDRefDType `json:"primaryOrg,omitempty" yaml:"primaryOrg,omitempty" mapstructure:"primaryOrg,omitempty"`

	// Model Primitive Datatype = NormalizedString. The pronoun(s) by which this
	// person is referenced. Examples (in the case of English) include 'she/her/hers',
	// 'he/him/his', 'they/them/theirs', 'ze/hir/hir', 'xe/xir', or a statement that
	// the person's name should be used instead of any pronoun.
	Pronouns *string `json:"pronouns,omitempty" yaml:"pronouns,omitempty" mapstructure:"pronouns,omitempty"`

	// The identifiers (GUIDs) for the set of resources that are to be made available
	// to the user. These are the sourcedIds that should be used for obtaining the
	// metadata about the resources using the OR 1.2 Resources Service [OR-RES-SM-12].
	Resources []ResourceGUIDRefDType `json:"resources,omitempty" yaml:"resources,omitempty" mapstructure:"resources,omitempty"`

	// The set of roles for each of the orgs to which the user is affilliated. This is
	// expressed as a set of role/org tuples.
	Roles []RoleDType `json:"roles" yaml:"roles" mapstructure:"roles"`

	// Model Primitive Datatype = NormalizedString. The SMS number for the user.
	Sms *string `json:"sms,omitempty" yaml:"sms,omitempty" mapstructure:"sms,omitempty"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status UserDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// The set of external user identifiers that should be used for this user, if for
	// some reason the sourcedId cannot be used. This might be an active directory id,
	// an LTI id, or some other machine-readable identifier that is used for this
	// person.
	UserIds []UserIdDType `json:"userIds,omitempty" yaml:"userIds,omitempty" mapstructure:"userIds,omitempty"`

	// Model Primitive Datatype = NormalizedString. The master unique identifier for
	// this user. This is NOT the same as the user's interoperability 'sourcedId'.
	// This should be used to ensure that all of the system identifiers/accounts etc.
	// can be reconciled to the same user. How this identifier is assigned and its
	// format is beyond the scope of this specification.
	UserMasterIdentifier *string `json:"userMasterIdentifier,omitempty" yaml:"userMasterIdentifier,omitempty" mapstructure:"userMasterIdentifier,omitempty"`

	// The set of system/app/tool profiles for the user.
	UserProfiles []UserProfileDType `json:"userProfiles,omitempty" yaml:"userProfiles,omitempty" mapstructure:"userProfiles,omitempty"`

	// Model Primitive Datatype = NormalizedString. The user name assigned to the
	// user. NOTE - This has been kept for backwards compatibility with OneRoster 1.1
	// and the new 'userProfiles' characteristic SHOULD be used instead.
	Username *string `json:"username,omitempty" yaml:"username,omitempty" mapstructure:"username,omitempty"`
}

type UserDTypeEnabledUser string

const (
	UserDTypeEnabledUserFalse UserDTypeEnabledUser = "false"
	UserDTypeEnabledUserTrue  UserDTypeEnabledUser = "true"
)

var enumValues_UserDTypeEnabledUser = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserDTypeEnabledUser) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_UserDTypeEnabledUser {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_UserDTypeEnabledUser,
			v,
		)
	}
	*j = UserDTypeEnabledUser(v)
	return nil
}

type UserDTypeStatus string

const (
	UserDTypeStatusActive      UserDTypeStatus = "active"
	UserDTypeStatusTobedeleted UserDTypeStatus = "tobedeleted"
)

var enumValues_UserDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_UserDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_UserDTypeStatus,
			v,
		)
	}
	*j = UserDTypeStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in UserDType: required")
	}
	if _, ok := raw["enabledUser"]; raw != nil && !ok {
		return errors.New("field enabledUser in UserDType: required")
	}
	if _, ok := raw["familyName"]; raw != nil && !ok {
		return errors.New("field familyName in UserDType: required")
	}
	if _, ok := raw["givenName"]; raw != nil && !ok {
		return errors.New("field givenName in UserDType: required")
	}
	if _, ok := raw["roles"]; raw != nil && !ok {
		return errors.New("field roles in UserDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in UserDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in UserDType: required")
	}
	type Plain UserDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Roles != nil && len(plain.Roles) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "roles", 1)
	}
	*j = UserDType(plain)
	return nil
}

// This is the container for reference to a OneRoster 'User' object that has an
// allocated sourcedId (GUID).
type UserGUIDRefDType struct {
	// Model Primitive Datatype = AnyURI. The URI for the type of object being
	// referenced.
	Href string `json:"href" yaml:"href" mapstructure:"href"`

	// Model Primitive Datatype = String. The globally unique identifier of the object
	// being referenced.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// The type of object being referenced i.e. a 'user'.
	Type UserGUIDRefDTypeType `json:"type" yaml:"type" mapstructure:"type"`
}

type UserGUIDRefDTypeType string

const UserGUIDRefDTypeTypeUser UserGUIDRefDTypeType = "user"

var enumValues_UserGUIDRefDTypeType = []any{
	"user",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserGUIDRefDTypeType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_UserGUIDRefDTypeType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_UserGUIDRefDTypeType,
			v,
		)
	}
	*j = UserGUIDRefDTypeType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserGUIDRefDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["href"]; raw != nil && !ok {
		return errors.New("field href in UserGUIDRefDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in UserGUIDRefDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in UserGUIDRefDType: required")
	}
	type Plain UserGUIDRefDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UserGUIDRefDType(plain)
	return nil
}

// This is the set of external user identifiers that should be used for this user,
// if for some reason the sourcedId cannot be used. This might be an active
// directory id, an LTI id, or some other machine-readable identifier that is used
// for this person.
type UserIdDType struct {
	// Model Primitive Datatype = String. The user identifier.
	Identifier string `json:"identifier" yaml:"identifier" mapstructure:"identifier"`

	// Model Primitive Datatype = NormalizedString. The type of identifier. This is no
	// predefined vocabuary.
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserIdDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["identifier"]; raw != nil && !ok {
		return errors.New("field identifier in UserIdDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in UserIdDType: required")
	}
	type Plain UserIdDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UserIdDType(plain)
	return nil
}

// The container for the information about a User Profile that will provide the
// user with access to some system, application, tool, etc.
type UserProfileDType struct {
	// Model Primitive Datatype = NormalizedString. Identifier for the application
	// associated with the account. The nature, and how this identifier is assigned is
	// not defined by this specification. This may have a value of 'default' to denote
	// this account should be used for default access to all applications related to
	// this vendor.
	ApplicationId *string `json:"applicationId,omitempty" yaml:"applicationId,omitempty" mapstructure:"applicationId,omitempty"`

	// The set of credentials that are available for access to this profile.
	Credentials []CredentialDType `json:"credentials,omitempty" yaml:"credentials,omitempty" mapstructure:"credentials,omitempty"`

	// Model Primitive Datatype = String. A human readable description of the use of
	// the profile. This should not contain any security information for access to the
	// account.
	Description *string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Model Primitive Datatype = AnyURI. The unique identifier for the profile. This
	// does not need to be a globally unique identifier but it must be unique within
	// the scope of the user.
	ProfileId string `json:"profileId" yaml:"profileId" mapstructure:"profileId"`

	// Model Primitive Datatype = NormalizedString. The type of profile. This should
	// be a human readable label that has some significance in the context of the
	// related system, app, tool, etc.
	ProfileType string `json:"profileType" yaml:"profileType" mapstructure:"profileType"`

	// Model Primitive Datatype = NormalizedString. The unique identifier for the
	// vendor of the system, tool, app, etc. which requires the use of this profile.
	VendorId string `json:"vendorId" yaml:"vendorId" mapstructure:"vendorId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserProfileDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["profileId"]; raw != nil && !ok {
		return errors.New("field profileId in UserProfileDType: required")
	}
	if _, ok := raw["profileType"]; raw != nil && !ok {
		return errors.New("field profileType in UserProfileDType: required")
	}
	if _, ok := raw["vendorId"]; raw != nil && !ok {
		return errors.New("field vendorId in UserProfileDType: required")
	}
	type Plain UserProfileDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UserProfileDType(plain)
	return nil
}
