// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rosterjson

import (
	"encoding/json"
	"fmt"
	"reflect"
	"time"

	"github.com/StevenACoffman/toerr/errors"
)

// A class is an instance of a course, onto which students and teachers are
// enrolled. A class is typically held within a term.
type ClassDType struct {
	// Model Primitive Datatype = NormalizedString. The class code.
	ClassCode *string `json:"classCode,omitempty" yaml:"classCode,omitempty" mapstructure:"classCode,omitempty"`

	// The type of class. This is based upon an enumerated vocabulary.
	ClassType any `json:"classType,omitempty" yaml:"classType,omitempty" mapstructure:"classType,omitempty"`

	// The link to the associated course i.e. the Course 'sourcedId'.
	Course CourseGUIDRefDType `json:"course" yaml:"course" mapstructure:"course"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Model Primitive Datatype = NormalizedString. The grade(s) who attend the class.
	// The permitted vocabulary should be defined as part of the adoption and
	// deployment process. See the Implementation Guide [OR-IMPL-12] for more details
	// on how to define/use such a vocabulary.
	Grades []string `json:"grades,omitempty" yaml:"grades,omitempty" mapstructure:"grades,omitempty"`

	// Model Primitive Datatype = NormalizedString. The location for the class e.g.
	// 'Room 19'.
	Location *string `json:"location,omitempty" yaml:"location,omitempty" mapstructure:"location,omitempty"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// Model Primitive Datatype = NormalizedString. The time slots in the day that the
	// class will be given. Examples are 1 or a list of 1, 3, 5, etc.
	Periods []string `json:"periods,omitempty" yaml:"periods,omitempty" mapstructure:"periods,omitempty"`

	// The links to the set of associated resources i.e. the Resource 'sourcedIds'.
	Resources []ResourceGUIDRefDType `json:"resources,omitempty" yaml:"resources,omitempty" mapstructure:"resources,omitempty"`

	// The link to the associated school i.e. the School 'sourcedId'.
	School OrgGUIDRefDType `json:"school" yaml:"school" mapstructure:"school"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status ClassDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Model Primitive Datatype = NormalizedString. This is a machine readable set of
	// codes and the number should match the associated 'subjects' attribute. The
	// vocabulary for this characteristic should be defined as part of the local
	// addition of this specification (see the Implementation Guide [OR-IMPL-12] for
	// more details).
	SubjectCodes []string `json:"subjectCodes,omitempty" yaml:"subjectCodes,omitempty" mapstructure:"subjectCodes,omitempty"`

	// Model Primitive Datatype = NormalizedString. The set of subjects addressed by
	// this class e.g. 'chemistry'.
	Subjects []string `json:"subjects,omitempty" yaml:"subjects,omitempty" mapstructure:"subjects,omitempty"`

	// The links to the set of terms or semesters (academicSession) i.e. the set of
	// 'sourcedIds' for the terms within the associated school year.
	Terms []AcadSessionGUIDRefDType `json:"terms" yaml:"terms" mapstructure:"terms"`

	// Model Primitive Datatype = NormalizedString. The tile/label for the class.
	Title string `json:"title" yaml:"title" mapstructure:"title"`
}

type ClassDTypeClassType_0 string

const (
	ClassDTypeClassType_0_Homeroom  ClassDTypeClassType_0 = "homeroom"
	ClassDTypeClassType_0_Scheduled ClassDTypeClassType_0 = "scheduled"
)

var enumValues_ClassDTypeClassType_0 = []any{
	"homeroom",
	"scheduled",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClassDTypeClassType_0) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ClassDTypeClassType_0 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_ClassDTypeClassType_0,
			v,
		)
	}
	*j = ClassDTypeClassType_0(v)
	return nil
}

type ClassDTypeStatus string

const (
	ClassDTypeStatusActive      ClassDTypeStatus = "active"
	ClassDTypeStatusTobedeleted ClassDTypeStatus = "tobedeleted"
)

var enumValues_ClassDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClassDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ClassDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_ClassDTypeStatus,
			v,
		)
	}
	*j = ClassDTypeStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClassDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["course"]; raw != nil && !ok {
		return errors.New("field course in ClassDType: required")
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in ClassDType: required")
	}
	if _, ok := raw["school"]; raw != nil && !ok {
		return errors.New("field school in ClassDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in ClassDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in ClassDType: required")
	}
	if _, ok := raw["terms"]; raw != nil && !ok {
		return errors.New("field terms in ClassDType: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return errors.New("field title in ClassDType: required")
	}
	type Plain ClassDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Terms != nil && len(plain.Terms) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "terms", 1)
	}
	*j = ClassDType(plain)
	return nil
}

// This is the container for reference to a OneRoster 'Course' object that has an
// allocated sourcedId (GUID).
type CourseGUIDRefDType struct {
	// Model Primitive Datatype = AnyURI. The URI for the type of object being
	// referenced.
	Href string `json:"href" yaml:"href" mapstructure:"href"`

	// Model Primitive Datatype = String. The globally unique identifier of the object
	// being referenced.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// The type of object being referenced i.e. a 'course'.
	Type CourseGUIDRefDTypeType `json:"type" yaml:"type" mapstructure:"type"`
}

type CourseGUIDRefDTypeType string

const CourseGUIDRefDTypeTypeCourse CourseGUIDRefDTypeType = "course"

var enumValues_CourseGUIDRefDTypeType = []any{
	"course",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CourseGUIDRefDTypeType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CourseGUIDRefDTypeType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_CourseGUIDRefDTypeType,
			v,
		)
	}
	*j = CourseGUIDRefDTypeType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CourseGUIDRefDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["href"]; raw != nil && !ok {
		return errors.New("field href in CourseGUIDRefDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in CourseGUIDRefDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in CourseGUIDRefDType: required")
	}
	type Plain CourseGUIDRefDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CourseGUIDRefDType(plain)
	return nil
}

// Author-Colin Smythe (1EdTech);  Version-1.2;  Release Date-19th September 2022.
type Onerosterrosteringservicev1P2Getallclasses200ResponsepayloadSchemav1P0Json struct {
	// The collection of class instances. The order is not significant. The
	// corresponding query constraints may result in no instances being returned.
	Classes []ClassDType `json:"classes,omitempty" yaml:"classes,omitempty" mapstructure:"classes,omitempty"`
}
