// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rosterjson

import (
	"encoding/json"
	"fmt"
	"reflect"
	"time"

	"github.com/StevenACoffman/toerr/errors"
)

// The information about a course. A Course is a course of study that, typically,
// has a shared curriculum although it may be taught to different students by
// different teachers. It is likely that several classes of a single course may be
// taught in a term. For example, a school runs Grade 9 English in the spring term.
// There are four classes, each with a different 30 students, taught by 4 different
// teachers. However the curriculum for each of those four classes is the same i.e.
// the course curriculum.
type CourseDType struct {
	// Model Primitive Datatype = NormalizedString. The assigned course code.
	CourseCode string `json:"courseCode" yaml:"courseCode" mapstructure:"courseCode"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Model Primitive Datatype = NormalizedString. Grade(s) for which the class is
	// attended. The permitted vocabulary should be defined as part of the adoption
	// and deployment process. See the Implementation Guide [OR-IMPL-12] for more
	// details on how to define/use such a vocabulary.
	Grades []string `json:"grades,omitempty" yaml:"grades,omitempty" mapstructure:"grades,omitempty"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// The link to org i.e. the 'sourcedId' of the org.
	Org *OrgGUIDRefDType `json:"org,omitempty" yaml:"org,omitempty" mapstructure:"org,omitempty"`

	// The links to the associated resources if applicable i.e. the resource
	// 'sourcedIds'.
	Resources []ResourceGUIDRefDType `json:"resources,omitempty" yaml:"resources,omitempty" mapstructure:"resources,omitempty"`

	// The link to academicSession i.e. the AcademicSession 'sourcedId'.
	SchoolYear *AcadSessionGUIDRefDType `json:"schoolYear,omitempty" yaml:"schoolYear,omitempty" mapstructure:"schoolYear,omitempty"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status CourseDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Model Primitive Datatype = NormalizedString. This is a machine readable set of
	// codes and the number should match the associated 'subjects' attribute. The
	// vocabulary for this characteristic should be defined as part of the local
	// addition of this specification (see the Implementation Guide [OR-IMPL-12] for
	// more details).
	SubjectCodes []string `json:"subjectCodes,omitempty" yaml:"subjectCodes,omitempty" mapstructure:"subjectCodes,omitempty"`

	// Model Primitive Datatype = NormalizedString. The set of subjects addresse by
	// this course. This is a set of human readable strings.
	Subjects []string `json:"subjects,omitempty" yaml:"subjects,omitempty" mapstructure:"subjects,omitempty"`

	// Model Primitive Datatype = NormalizedString. The title of the course.
	Title string `json:"title" yaml:"title" mapstructure:"title"`
}

type CourseDTypeStatus string

const (
	CourseDTypeStatusActive      CourseDTypeStatus = "active"
	CourseDTypeStatusTobedeleted CourseDTypeStatus = "tobedeleted"
)

var enumValues_CourseDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CourseDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CourseDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_CourseDTypeStatus,
			v,
		)
	}
	*j = CourseDTypeStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CourseDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["courseCode"]; raw != nil && !ok {
		return errors.New("field courseCode in CourseDType: required")
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in CourseDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in CourseDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in CourseDType: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return errors.New("field title in CourseDType: required")
	}
	type Plain CourseDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = CourseDType(plain)
	return nil
}

// Author-Colin Smythe (1EdTech);  Version-1.2;  Release Date-19th September 2022.
type Onerosterrosteringservicev1P2Getallcourses200ResponsepayloadSchemav1P0Json struct {
	// The collection of course instances. The order is not significant. The
	// corresponding query constraints may result in no instances being returned.
	Courses []CourseDType `json:"courses,omitempty" yaml:"courses,omitempty" mapstructure:"courses,omitempty"`
}
