// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rosterjson

import (
	"encoding/json"
	"reflect"
	"strings"

	"github.com/go-viper/mapstructure/v2"

	"github.com/StevenACoffman/toerr/errors"
)

// The container for a single set of credentials for an account.
type CredentialDType struct {
	// Model Primitive Datatype = String. The password in this set of credentials.
	// Care should be taken to ensure that no unencrypted value is revealed.
	Password *string `json:"password,omitempty" yaml:"password,omitempty" mapstructure:"password,omitempty"`

	// Model Primitive Datatype = String. The type of credentials for the profile.
	// This should be indicative of when this specific credential should be used.
	Type string `json:"type" yaml:"type" mapstructure:"type"`

	// Model Primitive Datatype = NormalizedString. The username.
	Username string `json:"username" yaml:"username" mapstructure:"username"`

	AdditionalProperties any `mapstructure:"remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CredentialDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in CredentialDType: required")
	}
	if _, ok := raw["username"]; raw != nil && !ok {
		return errors.New("field username in CredentialDType: required")
	}
	type Plain CredentialDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	st := reflect.TypeFor[Plain]()
	for field := range st.Fields() {
		delete(raw, field.Name)
		delete(raw, strings.Split(field.Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = CredentialDType(plain)
	return nil
}
