// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rosterjson

import (
	"encoding/json"
	"fmt"
	"reflect"
	"time"

	"github.com/atombender/go-jsonschema/pkg/types"

	"github.com/StevenACoffman/toerr/errors"
)

// Demographics information is taken from the Common Educational Data Standards
// (CEDS) from the US government. (http://ceds.ed.gov). Note that demographics data
// is held in its own service, and that access to this service is considered
// privileged. Not all consumer keys will be able to request demographics data.
type DemographicsDType struct {
	// Identification of whether or not the user is an American Indian or Alaska
	// Native ethnicity.
	AmericanIndianOrAlaskaNative *DemographicsDTypeAmericanIndianOrAlaskaNative `json:"americanIndianOrAlaskaNative,omitempty" yaml:"americanIndianOrAlaskaNative,omitempty" mapstructure:"americanIndianOrAlaskaNative,omitempty"`

	// Identification of whether or not the user is of Asian ethnicity.
	Asian *DemographicsDTypeAsian `json:"asian,omitempty" yaml:"asian,omitempty" mapstructure:"asian,omitempty"`

	// Model Primitive Datatype = Date. the date of birth. The format is [ISO 8601] of
	// 'YYYY-MM-DD'.
	BirthDate *types.SerializableDate `json:"birthDate,omitempty" yaml:"birthDate,omitempty" mapstructure:"birthDate,omitempty"`

	// Identification of whether or not the user is black or African American
	// ethnicity.
	BlackOrAfricanAmerican *DemographicsDTypeBlackOrAfricanAmerican `json:"blackOrAfricanAmerican,omitempty" yaml:"blackOrAfricanAmerican,omitempty" mapstructure:"blackOrAfricanAmerican,omitempty"`

	// Model Primitive Datatype = NormalizedString. The name of the city in which the
	// user was born.
	CityOfBirth *string `json:"cityOfBirth,omitempty" yaml:"cityOfBirth,omitempty" mapstructure:"cityOfBirth,omitempty"`

	// Model Primitive Datatype = NormalizedString. The country of birth code. The
	// permitted vocabulary should be defined as part of the adoption and deployment
	// process. See the Implementation Guide [OR-IMPL-12] for more details on how to
	// define/use such a vocabulary.
	CountryOfBirthCode *string `json:"countryOfBirthCode,omitempty" yaml:"countryOfBirthCode,omitempty" mapstructure:"countryOfBirthCode,omitempty"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Identification of whether or not the user has a demographic of two or more race
	// ethnicities.
	DemographicRaceTwoOrMoreRaces *DemographicsDTypeDemographicRaceTwoOrMoreRaces `json:"demographicRaceTwoOrMoreRaces,omitempty" yaml:"demographicRaceTwoOrMoreRaces,omitempty" mapstructure:"demographicRaceTwoOrMoreRaces,omitempty"`

	// Identification of whether or not the user is Hispanic or of Latino ethnicity.
	HispanicOrLatinoEthnicity *DemographicsDTypeHispanicOrLatinoEthnicity `json:"hispanicOrLatinoEthnicity,omitempty" yaml:"hispanicOrLatinoEthnicity,omitempty" mapstructure:"hispanicOrLatinoEthnicity,omitempty"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// Identification of whether or not the user is Native Hawaiian or Other Pacific
	// Islander ethnicity.
	NativeHawaiianOrOtherPacificIslander *DemographicsDTypeNativeHawaiianOrOtherPacificIslander `json:"nativeHawaiianOrOtherPacificIslander,omitempty" yaml:"nativeHawaiianOrOtherPacificIslander,omitempty" mapstructure:"nativeHawaiianOrOtherPacificIslander,omitempty"`

	// Model Primitive Datatype = NormalizedString. An indication of the location of a
	// person's legal residence relative to (within or outside) the boundaries of the
	// public school attended and its administrative unit. The permitted vocabulary
	// should be defined as part of the adoption and deployment process. See the
	// Implementation Guide [OR-IMPL-12] for more details on how to define/use such a
	// vocabulary.
	PublicSchoolResidenceStatus *string `json:"publicSchoolResidenceStatus,omitempty" yaml:"publicSchoolResidenceStatus,omitempty" mapstructure:"publicSchoolResidenceStatus,omitempty"`

	// The sex of the individual. The permitted values are from an enumerated list.
	Sex any `json:"sex,omitempty" yaml:"sex,omitempty" mapstructure:"sex,omitempty"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// Model Primitive Datatype = NormalizedString. The abbreviation for the name of
	// the state (within the United States) or extra-state jurisdiction in which a
	// person was born. The permitted vocabulary should be defined as part of the
	// adoption and deployment process. See the Implementation Guide [OR-IMPL-12] for
	// more details on how to define/use such a vocabulary.
	StateOfBirthAbbreviation *string `json:"stateOfBirthAbbreviation,omitempty" yaml:"stateOfBirthAbbreviation,omitempty" mapstructure:"stateOfBirthAbbreviation,omitempty"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status DemographicsDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Identification of whether or not the user is of white ethnicity.
	White *DemographicsDTypeWhite `json:"white,omitempty" yaml:"white,omitempty" mapstructure:"white,omitempty"`
}

type DemographicsDTypeAmericanIndianOrAlaskaNative string

const (
	DemographicsDTypeAmericanIndianOrAlaskaNativeFalse DemographicsDTypeAmericanIndianOrAlaskaNative = "false"
	DemographicsDTypeAmericanIndianOrAlaskaNativeTrue  DemographicsDTypeAmericanIndianOrAlaskaNative = "true"
)

var enumValues_DemographicsDTypeAmericanIndianOrAlaskaNative = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeAmericanIndianOrAlaskaNative) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeAmericanIndianOrAlaskaNative {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeAmericanIndianOrAlaskaNative,
			v,
		)
	}
	*j = DemographicsDTypeAmericanIndianOrAlaskaNative(v)
	return nil
}

type DemographicsDTypeAsian string

const (
	DemographicsDTypeAsianFalse DemographicsDTypeAsian = "false"
	DemographicsDTypeAsianTrue  DemographicsDTypeAsian = "true"
)

var enumValues_DemographicsDTypeAsian = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeAsian) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeAsian {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeAsian,
			v,
		)
	}
	*j = DemographicsDTypeAsian(v)
	return nil
}

type DemographicsDTypeBlackOrAfricanAmerican string

const (
	DemographicsDTypeBlackOrAfricanAmericanFalse DemographicsDTypeBlackOrAfricanAmerican = "false"
	DemographicsDTypeBlackOrAfricanAmericanTrue  DemographicsDTypeBlackOrAfricanAmerican = "true"
)

var enumValues_DemographicsDTypeBlackOrAfricanAmerican = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeBlackOrAfricanAmerican) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeBlackOrAfricanAmerican {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeBlackOrAfricanAmerican,
			v,
		)
	}
	*j = DemographicsDTypeBlackOrAfricanAmerican(v)
	return nil
}

type DemographicsDTypeDemographicRaceTwoOrMoreRaces string

const (
	DemographicsDTypeDemographicRaceTwoOrMoreRacesFalse DemographicsDTypeDemographicRaceTwoOrMoreRaces = "false"
	DemographicsDTypeDemographicRaceTwoOrMoreRacesTrue  DemographicsDTypeDemographicRaceTwoOrMoreRaces = "true"
)

var enumValues_DemographicsDTypeDemographicRaceTwoOrMoreRaces = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeDemographicRaceTwoOrMoreRaces) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeDemographicRaceTwoOrMoreRaces {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeDemographicRaceTwoOrMoreRaces,
			v,
		)
	}
	*j = DemographicsDTypeDemographicRaceTwoOrMoreRaces(v)
	return nil
}

type DemographicsDTypeHispanicOrLatinoEthnicity string

const (
	DemographicsDTypeHispanicOrLatinoEthnicityFalse DemographicsDTypeHispanicOrLatinoEthnicity = "false"
	DemographicsDTypeHispanicOrLatinoEthnicityTrue  DemographicsDTypeHispanicOrLatinoEthnicity = "true"
)

var enumValues_DemographicsDTypeHispanicOrLatinoEthnicity = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeHispanicOrLatinoEthnicity) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeHispanicOrLatinoEthnicity {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeHispanicOrLatinoEthnicity,
			v,
		)
	}
	*j = DemographicsDTypeHispanicOrLatinoEthnicity(v)
	return nil
}

type DemographicsDTypeNativeHawaiianOrOtherPacificIslander string

const (
	DemographicsDTypeNativeHawaiianOrOtherPacificIslanderFalse DemographicsDTypeNativeHawaiianOrOtherPacificIslander = "false"
	DemographicsDTypeNativeHawaiianOrOtherPacificIslanderTrue  DemographicsDTypeNativeHawaiianOrOtherPacificIslander = "true"
)

var enumValues_DemographicsDTypeNativeHawaiianOrOtherPacificIslander = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeNativeHawaiianOrOtherPacificIslander) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeNativeHawaiianOrOtherPacificIslander {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeNativeHawaiianOrOtherPacificIslander,
			v,
		)
	}
	*j = DemographicsDTypeNativeHawaiianOrOtherPacificIslander(v)
	return nil
}

type DemographicsDTypeSex_0 string

const (
	DemographicsDTypeSex_0_Female      DemographicsDTypeSex_0 = "female"
	DemographicsDTypeSex_0_Male        DemographicsDTypeSex_0 = "male"
	DemographicsDTypeSex_0_Other       DemographicsDTypeSex_0 = "other"
	DemographicsDTypeSex_0_Unspecified DemographicsDTypeSex_0 = "unspecified"
)

var enumValues_DemographicsDTypeSex_0 = []any{
	"male",
	"female",
	"unspecified",
	"other",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeSex_0) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeSex_0 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeSex_0,
			v,
		)
	}
	*j = DemographicsDTypeSex_0(v)
	return nil
}

type DemographicsDTypeStatus string

const (
	DemographicsDTypeStatusActive      DemographicsDTypeStatus = "active"
	DemographicsDTypeStatusTobedeleted DemographicsDTypeStatus = "tobedeleted"
)

var enumValues_DemographicsDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeStatus,
			v,
		)
	}
	*j = DemographicsDTypeStatus(v)
	return nil
}

type DemographicsDTypeWhite string

const (
	DemographicsDTypeWhiteFalse DemographicsDTypeWhite = "false"
	DemographicsDTypeWhiteTrue  DemographicsDTypeWhite = "true"
)

var enumValues_DemographicsDTypeWhite = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDTypeWhite) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_DemographicsDTypeWhite {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_DemographicsDTypeWhite,
			v,
		)
	}
	*j = DemographicsDTypeWhite(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DemographicsDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in DemographicsDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in DemographicsDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in DemographicsDType: required")
	}
	type Plain DemographicsDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = DemographicsDType(plain)
	return nil
}

// Author-Colin Smythe (1EdTech);  Version-1.2;  Release Date-19th September 2022.
type Onerosterrosteringservicev1P2Getalldemographics200ResponsepayloadSchemav1P0Json struct {
	// The collection of demographics instances. The order is not significant. The
	// corresponding query constraints may result in no instances being returned.
	Demographics []DemographicsDType `json:"demographics,omitempty" yaml:"demographics,omitempty" mapstructure:"demographics,omitempty"`
}
