// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rosterjson

import (
	"encoding/json"
	"fmt"
	"reflect"
	"time"

	"github.com/atombender/go-jsonschema/pkg/types"

	"github.com/StevenACoffman/toerr/errors"
)

// This is the container for reference to a OneRoster 'Class' object that has an
// allocated sourcedId (GUID).
type ClassGUIDRefDType struct {
	// Model Primitive Datatype = AnyURI. The URI for the type of object being
	// referenced.
	Href string `json:"href" yaml:"href" mapstructure:"href"`

	// Model Primitive Datatype = String. The globally unique identifier of the object
	// being referenced.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// The type of object being referenced i.e. a 'class'.
	Type ClassGUIDRefDTypeType `json:"type" yaml:"type" mapstructure:"type"`
}

type ClassGUIDRefDTypeType string

const ClassGUIDRefDTypeTypeClass ClassGUIDRefDTypeType = "class"

var enumValues_ClassGUIDRefDTypeType = []any{
	"class",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClassGUIDRefDTypeType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ClassGUIDRefDTypeType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_ClassGUIDRefDTypeType,
			v,
		)
	}
	*j = ClassGUIDRefDTypeType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ClassGUIDRefDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["href"]; raw != nil && !ok {
		return errors.New("field href in ClassGUIDRefDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in ClassGUIDRefDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in ClassGUIDRefDType: required")
	}
	type Plain ClassGUIDRefDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ClassGUIDRefDType(plain)
	return nil
}

// An enrollment is the name given to an individual taking part in a class. In the
// vast majority of cases, users will be students learning in a class, or teachers
// teaching the class. Other roles are also possible.
type EnrollmentDType struct {
	// Model Primitive Datatype = Date. The start date for the enrollment (inclusive).
	// This date must be within the period of the associated Academic Session for the
	// class (Term/Semester/SchoolYear). Use the [ISO 8601] format of 'YYYY-MM-DD'.
	BeginDate *types.SerializableDate `json:"beginDate,omitempty" yaml:"beginDate,omitempty" mapstructure:"beginDate,omitempty"`

	// The link to the class on which the user is enrolled i.e. the Class 'sourcedId'.
	Class ClassGUIDRefDType `json:"class" yaml:"class" mapstructure:"class"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Model Primitive Datatype = Date. The end date for the enrollment (exclusive).
	// This date must be within the period of the associated Academic Session for the
	// class (Term/Semester/SchoolYear). Use the [ISO 8601] format of 'YYYY-MM-DD'.
	EndDate *types.SerializableDate `json:"endDate,omitempty" yaml:"endDate,omitempty" mapstructure:"endDate,omitempty"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// Applicable only to teachers. Only one teacher should be designated as the
	// primary teacher for a class (this value set as 'true') in the period defined by
	// the begin/end dates.
	Primary *EnrollmentDTypePrimary `json:"primary,omitempty" yaml:"primary,omitempty" mapstructure:"primary,omitempty"`

	// The role of the user for this class in the school e.g teacher, student, etc.
	// This is from an enumerated vocabulary.
	Role any `json:"role" yaml:"role" mapstructure:"role"`

	// The link to the school at which the class is being provided i.e. an Org
	// 'sourcedId'.
	School OrgGUIDRefDType `json:"school" yaml:"school" mapstructure:"school"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status EnrollmentDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// The link to the enrolled User i.e. the User 'sourcedId'.
	User UserGUIDRefDType `json:"user" yaml:"user" mapstructure:"user"`
}

type EnrollmentDTypePrimary string

const (
	EnrollmentDTypePrimaryFalse EnrollmentDTypePrimary = "false"
	EnrollmentDTypePrimaryTrue  EnrollmentDTypePrimary = "true"
)

var enumValues_EnrollmentDTypePrimary = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnrollmentDTypePrimary) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnrollmentDTypePrimary {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_EnrollmentDTypePrimary,
			v,
		)
	}
	*j = EnrollmentDTypePrimary(v)
	return nil
}

type EnrollmentDTypeRole_0 string

const (
	EnrollmentDTypeRole_0_Administrator EnrollmentDTypeRole_0 = "administrator"
	EnrollmentDTypeRole_0_Proctor       EnrollmentDTypeRole_0 = "proctor"
	EnrollmentDTypeRole_0_Student       EnrollmentDTypeRole_0 = "student"
	EnrollmentDTypeRole_0_Teacher       EnrollmentDTypeRole_0 = "teacher"
)

var enumValues_EnrollmentDTypeRole_0 = []any{
	"administrator",
	"proctor",
	"student",
	"teacher",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnrollmentDTypeRole_0) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnrollmentDTypeRole_0 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_EnrollmentDTypeRole_0,
			v,
		)
	}
	*j = EnrollmentDTypeRole_0(v)
	return nil
}

type EnrollmentDTypeStatus string

const (
	EnrollmentDTypeStatusActive      EnrollmentDTypeStatus = "active"
	EnrollmentDTypeStatusTobedeleted EnrollmentDTypeStatus = "tobedeleted"
)

var enumValues_EnrollmentDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnrollmentDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_EnrollmentDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_EnrollmentDTypeStatus,
			v,
		)
	}
	*j = EnrollmentDTypeStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *EnrollmentDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["class"]; raw != nil && !ok {
		return errors.New("field class in EnrollmentDType: required")
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in EnrollmentDType: required")
	}
	if _, ok := raw["role"]; raw != nil && !ok {
		return errors.New("field role in EnrollmentDType: required")
	}
	if _, ok := raw["school"]; raw != nil && !ok {
		return errors.New("field school in EnrollmentDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in EnrollmentDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in EnrollmentDType: required")
	}
	if _, ok := raw["user"]; raw != nil && !ok {
		return errors.New("field user in EnrollmentDType: required")
	}
	type Plain EnrollmentDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = EnrollmentDType(plain)
	return nil
}

// Author-Colin Smythe (1EdTech);  Version-1.2;  Release Date-19th September 2022.
type Onerosterrosteringservicev1P2Getallenrollments200ResponsepayloadSchemav1P0Json struct {
	// The collection of enrollment instances. The order is not significant. The
	// corresponding query constraints may result in no instances being returned.
	Enrollments []EnrollmentDType `json:"enrollments,omitempty" yaml:"enrollments,omitempty" mapstructure:"enrollments,omitempty"`
}
