// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rosterjson

import (
	"encoding/json"
	"fmt"
	"reflect"
	"time"

	"github.com/atombender/go-jsonschema/pkg/types"

	"github.com/StevenACoffman/toerr/errors"
)

// This is the container for reference to a OneRoster 'Academic Session' object
// that has an allocated sourcedId (GUID).
type AcadSessionGUIDRefDType struct {
	// Model Primitive Datatype = AnyURI. The URI for the type of object being
	// referenced.
	Href string `json:"href" yaml:"href" mapstructure:"href"`

	// Model Primitive Datatype = String. The globally unique identifier of the object
	// being referenced.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// The type of object being referenced i.e. an 'academicSession'.
	Type AcadSessionGUIDRefDTypeType `json:"type" yaml:"type" mapstructure:"type"`
}

type AcadSessionGUIDRefDTypeType string

const AcadSessionGUIDRefDTypeTypeAcademicSession AcadSessionGUIDRefDTypeType = "academicSession"

var enumValues_AcadSessionGUIDRefDTypeType = []any{
	"academicSession",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AcadSessionGUIDRefDTypeType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AcadSessionGUIDRefDTypeType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_AcadSessionGUIDRefDTypeType,
			v,
		)
	}
	*j = AcadSessionGUIDRefDTypeType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AcadSessionGUIDRefDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["href"]; raw != nil && !ok {
		return errors.New("field href in AcadSessionGUIDRefDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in AcadSessionGUIDRefDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in AcadSessionGUIDRefDType: required")
	}
	type Plain AcadSessionGUIDRefDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AcadSessionGUIDRefDType(plain)
	return nil
}

// The container for an academicSession. An academicSession represents a duration
// of time. Typically they are used to describe terms, grading periods, and other
// durations e.g. school years. Term is used to describe a period of time during
// which learning will take place. Other words for term could be in common use
// around the world e.g. Semester. The important thing is that Term is a unit of
// time, often many weeks long, into which classes are scheduled. Grading Period is
// used to represent another unit of time, that within which line items are
// assessed. A term may have many grading periods, a grading period belongs to a
// single term. A class may be assessed over several grade periods (represented by
// a line item being connected to a grading period). The parent / child attributes
// of academic sessions allow terms to be connected to their grading periods and
// vice-versa.
type AcademicSessionDType struct {
	// The set of links to the child AcademicSessions i.e. a set of AcademicSession
	// 'sourcedIds'.
	Children []AcadSessionGUIDRefDType `json:"children,omitempty" yaml:"children,omitempty" mapstructure:"children,omitempty"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Model Primitive Datatype = Date. The end date for the academic session. The end
	// date is excluded from the academic session. This is in [ISO 8601] format of
	// 'YYYY-MM-DD'.
	EndDate types.SerializableDate `json:"endDate" yaml:"endDate" mapstructure:"endDate"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// The link to parent AcademicSession i.e. an AcademicSession 'sourcedId'.
	Parent *AcadSessionGUIDRefDType `json:"parent,omitempty" yaml:"parent,omitempty" mapstructure:"parent,omitempty"`

	// Model Primitive Datatype = NormalizedString. The school year for the academic
	// session.  This year should include the school year end e.g. 2014. This is in
	// the [ISO 8601] format of 'YYYY'.
	SchoolYear string `json:"schoolYear" yaml:"schoolYear" mapstructure:"schoolYear"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// Model Primitive Datatype = Date. The start date for the academic session. The
	// start date is included in the academic session. This is in [ISO 8601] format of
	// 'YYYY-MM-DD'.
	StartDate types.SerializableDate `json:"startDate" yaml:"startDate" mapstructure:"startDate"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status AcademicSessionDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// Model Primitive Datatype = NormalizedString. The title/label for the academic
	// session.
	Title string `json:"title" yaml:"title" mapstructure:"title"`

	// The type of academic session. This is based upon an enumerated vocabulary.
	Type any `json:"type" yaml:"type" mapstructure:"type"`
}

type AcademicSessionDTypeStatus string

const (
	AcademicSessionDTypeStatusActive      AcademicSessionDTypeStatus = "active"
	AcademicSessionDTypeStatusTobedeleted AcademicSessionDTypeStatus = "tobedeleted"
)

var enumValues_AcademicSessionDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AcademicSessionDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AcademicSessionDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_AcademicSessionDTypeStatus,
			v,
		)
	}
	*j = AcademicSessionDTypeStatus(v)
	return nil
}

type AcademicSessionDTypeType_0 string

const (
	AcademicSessionDTypeType_0_GradingPeriod AcademicSessionDTypeType_0 = "gradingPeriod"
	AcademicSessionDTypeType_0_SchoolYear    AcademicSessionDTypeType_0 = "schoolYear"
	AcademicSessionDTypeType_0_Semester      AcademicSessionDTypeType_0 = "semester"
	AcademicSessionDTypeType_0_Term          AcademicSessionDTypeType_0 = "term"
)

var enumValues_AcademicSessionDTypeType_0 = []any{
	"gradingPeriod",
	"semester",
	"schoolYear",
	"term",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AcademicSessionDTypeType_0) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_AcademicSessionDTypeType_0 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_AcademicSessionDTypeType_0,
			v,
		)
	}
	*j = AcademicSessionDTypeType_0(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AcademicSessionDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in AcademicSessionDType: required")
	}
	if _, ok := raw["endDate"]; raw != nil && !ok {
		return errors.New("field endDate in AcademicSessionDType: required")
	}
	if _, ok := raw["schoolYear"]; raw != nil && !ok {
		return errors.New("field schoolYear in AcademicSessionDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in AcademicSessionDType: required")
	}
	if _, ok := raw["startDate"]; raw != nil && !ok {
		return errors.New("field startDate in AcademicSessionDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in AcademicSessionDType: required")
	}
	if _, ok := raw["title"]; raw != nil && !ok {
		return errors.New("field title in AcademicSessionDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in AcademicSessionDType: required")
	}
	type Plain AcademicSessionDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AcademicSessionDType(plain)
	return nil
}

// Author-Colin Smythe (1EdTech);  Version-1.2;  Release Date-19th September 2022.
type Onerosterrosteringservicev1P2Getallgradingperiods200ResponsepayloadSchemav1P0Json struct {
	// The collection of academicSession instances. The order is not significant. The
	// corresponding query constraints may result in no instances being returned.
	AcademicSessions []AcademicSessionDType `json:"academicSessions,omitempty" yaml:"academicSessions,omitempty" mapstructure:"academicSessions,omitempty"`
}
