// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rosterjson

import (
	"encoding/json"
	"fmt"
	"reflect"
	"time"

	"github.com/StevenACoffman/toerr/errors"
)

// Author-Colin Smythe (1EdTech);  Version-1.2;  Release Date-19th September 2022.
type Onerosterrosteringservicev1P2Getallorgs200ResponsepayloadSchemav1P0Json struct {
	// The collection of org instances. The order is not significant. The
	// corresponding query constraints may result in no instances being returned.
	Orgs []OrgDType `json:"orgs,omitempty" yaml:"orgs,omitempty" mapstructure:"orgs,omitempty"`
}

// ORG is defined here as a structure for holding organizational information. An
// ORG might be a school, or it might be a local, statewide, or national entity.
// ORGs will typically have a parent ORG (up to the national level), and children,
// allowing a hierarchy to be established. School is defined here as the place
// where the learning happens. Most commonly this is the data that describes a
// bricks and mortar building, or, in the case of a virtual school, the virtual
// school organization. For enrollment and result reporting purposes, little
// information about this organization is required. A common example of a local
// organization is a school district.
type OrgDType struct {
	// The 'sourcedIds' for the set of child organizations.
	Children []OrgGUIDRefDType `json:"children,omitempty" yaml:"children,omitempty" mapstructure:"children,omitempty"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Model Primitive Datatype = String. Human readable identifier for this org e.g.
	// NCES ID.
	Identifier string `json:"identifier" yaml:"identifier" mapstructure:"identifier"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// Model Primitive Datatype = NormalizedString. The name of the organization.
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// The 'sourcedId' of the parent organization.
	Parent *OrgGUIDRefDType `json:"parent,omitempty" yaml:"parent,omitempty" mapstructure:"parent,omitempty"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status OrgDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// The type of organization. This uses a predefined vocabulary.
	Type any `json:"type" yaml:"type" mapstructure:"type"`
}

type OrgDTypeStatus string

const (
	OrgDTypeStatusActive      OrgDTypeStatus = "active"
	OrgDTypeStatusTobedeleted OrgDTypeStatus = "tobedeleted"
)

var enumValues_OrgDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OrgDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OrgDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_OrgDTypeStatus,
			v,
		)
	}
	*j = OrgDTypeStatus(v)
	return nil
}

type OrgDTypeType_0 string

const (
	OrgDTypeType_0_Department OrgDTypeType_0 = "department"
	OrgDTypeType_0_District   OrgDTypeType_0 = "district"
	OrgDTypeType_0_Local      OrgDTypeType_0 = "local"
	OrgDTypeType_0_National   OrgDTypeType_0 = "national"
	OrgDTypeType_0_School     OrgDTypeType_0 = "school"
	OrgDTypeType_0_State      OrgDTypeType_0 = "state"
)

var enumValues_OrgDTypeType_0 = []any{
	"department",
	"district",
	"local",
	"national",
	"school",
	"state",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OrgDTypeType_0) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OrgDTypeType_0 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_OrgDTypeType_0,
			v,
		)
	}
	*j = OrgDTypeType_0(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OrgDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in OrgDType: required")
	}
	if _, ok := raw["identifier"]; raw != nil && !ok {
		return errors.New("field identifier in OrgDType: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return errors.New("field name in OrgDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in OrgDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in OrgDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in OrgDType: required")
	}
	type Plain OrgDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = OrgDType(plain)
	return nil
}

// This is the container for reference to a OneRoster 'Org' object that has an
// allocated sourcedId (GUID).
type OrgGUIDRefDType struct {
	// Model Primitive Datatype = AnyURI. The URI for the type of object being
	// referenced.
	Href string `json:"href" yaml:"href" mapstructure:"href"`

	// Model Primitive Datatype = String. The globally unique identifier of the object
	// being referenced.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// The type of object being referenced i.e. an 'org'.
	Type OrgGUIDRefDTypeType `json:"type" yaml:"type" mapstructure:"type"`
}

type OrgGUIDRefDTypeType string

const OrgGUIDRefDTypeTypeOrg OrgGUIDRefDTypeType = "org"

var enumValues_OrgGUIDRefDTypeType = []any{
	"org",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OrgGUIDRefDTypeType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_OrgGUIDRefDTypeType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_OrgGUIDRefDTypeType,
			v,
		)
	}
	*j = OrgGUIDRefDTypeType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *OrgGUIDRefDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["href"]; raw != nil && !ok {
		return errors.New("field href in OrgGUIDRefDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in OrgGUIDRefDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in OrgGUIDRefDType: required")
	}
	type Plain OrgGUIDRefDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = OrgGUIDRefDType(plain)
	return nil
}
