// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rosterjson

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/atombender/go-jsonschema/pkg/types"

	"github.com/StevenACoffman/toerr/errors"
)

// The container for one mapping between a role and an org for the user.
type RoleDType struct {
	// Model Primitive Datatype = Date. The start date on which the role becomes
	// active (inclusive).
	BeginDate *types.SerializableDate `json:"beginDate,omitempty" yaml:"beginDate,omitempty" mapstructure:"beginDate,omitempty"`

	// Model Primitive Datatype = Date. The end date on which the role becomes
	// inactive (exclusive).
	EndDate *types.SerializableDate `json:"endDate,omitempty" yaml:"endDate,omitempty" mapstructure:"endDate,omitempty"`

	// The link to the associated org i.e. the 'sourcedId' for the org.
	Org OrgGUIDRefDType `json:"org" yaml:"org" mapstructure:"org"`

	// The role of the user in the org. The permitted values are from an enumerated
	// list.
	Role any `json:"role" yaml:"role" mapstructure:"role"`

	// Indicates if this role is the primary or secondary role for that org. There
	// MUST be one, and only one, primary role for each org.
	RoleType RoleDTypeRoleType `json:"roleType" yaml:"roleType" mapstructure:"roleType"`

	// Model Primitive Datatype = AnyURI. The identifier for the system/tool/app
	// access account that is relevant to this role in the org. The equivalent
	// UserProfile should exist with a 'profileId' equal to this identifier value.
	UserProfile *string `json:"userProfile,omitempty" yaml:"userProfile,omitempty" mapstructure:"userProfile,omitempty"`
}

type RoleDTypeRoleType string

const (
	RoleDTypeRoleTypePrimary   RoleDTypeRoleType = "primary"
	RoleDTypeRoleTypeSecondary RoleDTypeRoleType = "secondary"
)

var enumValues_RoleDTypeRoleType = []any{
	"primary",
	"secondary",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RoleDTypeRoleType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RoleDTypeRoleType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_RoleDTypeRoleType,
			v,
		)
	}
	*j = RoleDTypeRoleType(v)
	return nil
}

type RoleDTypeRole_0 string

const (
	RoleDTypeRole_0_Aide                  RoleDTypeRole_0 = "aide"
	RoleDTypeRole_0_Counselor             RoleDTypeRole_0 = "counselor"
	RoleDTypeRole_0_DistrictAdministrator RoleDTypeRole_0 = "districtAdministrator"
	RoleDTypeRole_0_Guardian              RoleDTypeRole_0 = "guardian"
	RoleDTypeRole_0_Parent                RoleDTypeRole_0 = "parent"
	RoleDTypeRole_0_Principal             RoleDTypeRole_0 = "principal"
	RoleDTypeRole_0_Proctor               RoleDTypeRole_0 = "proctor"
	RoleDTypeRole_0_Relative              RoleDTypeRole_0 = "relative"
	RoleDTypeRole_0_SiteAdministrator     RoleDTypeRole_0 = "siteAdministrator"
	RoleDTypeRole_0_Student               RoleDTypeRole_0 = "student"
	RoleDTypeRole_0_SystemAdministrator   RoleDTypeRole_0 = "systemAdministrator"
	RoleDTypeRole_0_Teacher               RoleDTypeRole_0 = "teacher"
)

var enumValues_RoleDTypeRole_0 = []any{
	"aide",
	"counselor",
	"districtAdministrator",
	"guardian",
	"parent",
	"principal",
	"proctor",
	"relative",
	"siteAdministrator",
	"student",
	"systemAdministrator",
	"teacher",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RoleDTypeRole_0) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_RoleDTypeRole_0 {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_RoleDTypeRole_0,
			v,
		)
	}
	*j = RoleDTypeRole_0(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *RoleDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["org"]; raw != nil && !ok {
		return errors.New("field org in RoleDType: required")
	}
	if _, ok := raw["role"]; raw != nil && !ok {
		return errors.New("field role in RoleDType: required")
	}
	if _, ok := raw["roleType"]; raw != nil && !ok {
		return errors.New("field roleType in RoleDType: required")
	}
	type Plain RoleDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = RoleDType(plain)
	return nil
}
