// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rosterjson

// Author-Colin Smythe (1EdTech);  Version-1.2;  Release Date-19th September 2022.
type Onerosterrosteringservicev1P2Getallschools200ResponsepayloadSchemav1P0Json struct {
	// The collection of org instances. The order is not significant. The
	// corresponding query constraints may result in no instances being returned.
	Orgs []OrgDType `json:"orgs,omitempty" yaml:"orgs,omitempty" mapstructure:"orgs,omitempty"`
}
