// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rosterjson

// Author-Colin Smythe (1EdTech);  Version-1.2;  Release Date-19th September 2022.
type Onerosterrosteringservicev1P2Getallstudents200ResponsepayloadSchemav1P0Json struct {
	// The collection of user instances. The order is not significant. The
	// corresponding query constraints may result in no instances being returned.
	Users []UserDType `json:"users,omitempty" yaml:"users,omitempty" mapstructure:"users,omitempty"`
}
