// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rosterjson

import (
	"encoding/json"
	"fmt"
	"reflect"

	"github.com/StevenACoffman/toerr/errors"
)

// Author-Colin Smythe (1EdTech);  Version-1.2;  Release Date-19th September 2022.
type Onerosterrosteringservicev1P2Getallteachers200ResponsepayloadSchemav1P0Json struct {
	// The collection of user instances. The order is not significant. The
	// corresponding query constraints may result in no instances being returned.
	Users []UserDType `json:"users,omitempty" yaml:"users,omitempty" mapstructure:"users,omitempty"`
}

// This is the container for reference to a OneRoster 'Resourse' object that has an
// allocated sourcedId (GUID).
type ResourceGUIDRefDType struct {
	// Model Primitive Datatype = AnyURI. The URI for the type of object being
	// referenced.
	Href string `json:"href" yaml:"href" mapstructure:"href"`

	// Model Primitive Datatype = String. The globally unique identifier of the object
	// being referenced.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// The type of object being referenced i.e. a 'resource'.
	Type ResourceGUIDRefDTypeType `json:"type" yaml:"type" mapstructure:"type"`
}

type ResourceGUIDRefDTypeType string

const ResourceGUIDRefDTypeTypeResource ResourceGUIDRefDTypeType = "resource"

var enumValues_ResourceGUIDRefDTypeType = []any{
	"resource",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResourceGUIDRefDTypeType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ResourceGUIDRefDTypeType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_ResourceGUIDRefDTypeType,
			v,
		)
	}
	*j = ResourceGUIDRefDTypeType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ResourceGUIDRefDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["href"]; raw != nil && !ok {
		return errors.New("field href in ResourceGUIDRefDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in ResourceGUIDRefDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in ResourceGUIDRefDType: required")
	}
	type Plain ResourceGUIDRefDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = ResourceGUIDRefDType(plain)
	return nil
}
