// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rosterjson

// Author-Colin Smythe (1EdTech);  Version-1.2;  Release Date-19th September 2022.
type Onerosterrosteringservicev1P2Getallterms200ResponsepayloadSchemav1P0Json struct {
	// The collection of academicSession instances. The order is not significant. The
	// corresponding query constraints may result in no instances being returned.
	AcademicSessions []AcademicSessionDType `json:"academicSessions,omitempty" yaml:"academicSessions,omitempty" mapstructure:"academicSessions,omitempty"`
}
