// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package rosterjson

import (
	"encoding/json"
	"fmt"
	"reflect"
	"time"

	"github.com/StevenACoffman/toerr/errors"
)

// Author-Colin Smythe (1EdTech);  Version-1.2;  Release Date-19th September 2022.
type Onerosterrosteringservicev1P2Getallusers200ResponsepayloadSchemav1P0Json struct {
	// The collection of user instances. The order is not significant. The
	// corresponding query constraints may result in no instances being returned.
	Users []UserDType `json:"users,omitempty" yaml:"users,omitempty" mapstructure:"users,omitempty"`
}

// Users, Teachers and Students are human beings that are teaching or studying in a
// class respectively. A single User class is used to represent both teachers and
// students and a role property is used to distinguish a user's natural role.Humans
// may have relationships with other humans. For example, a student may have
// parents. The 'agents' attribute allows for relationships between humans to be
// expressed. Note that these are typically from the point of view of the student -
// so a student will link to its parents (via the agent attribute). The reverse
// view MUST also be modeled, so for example, a user of role 'parent' MUST have
// agents that are of type 'student'. Note: Teachers MUST NOT be set as agents of
// students i.e. the teaching relationship is covered via enrollments.
type UserDType struct {
	// The links to other people i.e. User 'sourcedIds'.
	Agents []UserGUIDRefDType `json:"agents,omitempty" yaml:"agents,omitempty" mapstructure:"agents,omitempty"`

	// Model Primitive Datatype = DateTime. All objects MUST be annotated with the
	// dateTime upon which they were last modified. This enables requesters to query
	// for just the latest objects. DateTimes MUST be expressed in W3C profile of [ISO
	// 8601] and MUST contain the UTC timezone.
	DateLastModified time.Time `json:"dateLastModified" yaml:"dateLastModified" mapstructure:"dateLastModified"`

	// Model Primitive Datatype = NormalizedString. The email address for the user.
	Email *string `json:"email,omitempty" yaml:"email,omitempty" mapstructure:"email,omitempty"`

	// This is used to determine whether or not the record is active in the local
	// system. 'false' denotes that the record is active but system access is
	// curtailed according to the local administration rules.
	EnabledUser UserDTypeEnabledUser `json:"enabledUser" yaml:"enabledUser" mapstructure:"enabledUser"`

	// Model Primitive Datatype = NormalizedString. The family name. Also, known as
	// the last name.
	FamilyName string `json:"familyName" yaml:"familyName" mapstructure:"familyName"`

	// Model Primitive Datatype = NormalizedString. The given name. Also, known as the
	// first name.
	GivenName string `json:"givenName" yaml:"givenName" mapstructure:"givenName"`

	// Model Primitive Datatype = NormalizedString. Grade(s) for which a user with
	// role 'student' is enrolled. The permitted vocabulary should be defined as part
	// of the adoption and deployment process. See the Implementation Guide
	// [OR-IMPL-12] for more details on how to define/use such a vocabulary.
	Grades []string `json:"grades,omitempty" yaml:"grades,omitempty" mapstructure:"grades,omitempty"`

	// Model Primitive Datatype = String. An identifier for the user. NOTE - This
	// characteristic is kept for backwards compatibility with OneRoster 1.1/1.0. The
	// 'userIds' characteristic SHOULD be used instead.
	Identifier *string `json:"identifier,omitempty" yaml:"identifier,omitempty" mapstructure:"identifier,omitempty"`

	// All objects CAN be extended using the Metadata class. This specification is
	// silent on what implementers may consider to be appropriate extensions. The form
	// of the extension is dependent on the binding technology being used.
	Metadata MetadataDType `json:"metadata,omitempty" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// Model Primitive Datatype = NormalizedString. The set of middle names. If more
	// than one middle name is needed separate using a space e.g. 'Wingarde
	// Granville'.
	MiddleName *string `json:"middleName,omitempty" yaml:"middleName,omitempty" mapstructure:"middleName,omitempty"`

	// Model Primitive Datatype = String. A top-level password for the user. Care
	// should be taken when using this field and the password SHOULD be encrypted.
	Password *string `json:"password,omitempty" yaml:"password,omitempty" mapstructure:"password,omitempty"`

	// Model Primitive Datatype = NormalizedString. The phone number for the user.
	Phone *string `json:"phone,omitempty" yaml:"phone,omitempty" mapstructure:"phone,omitempty"`

	// Model Primitive Datatype = NormalizedString. The user's preferred first name.
	// This attribute was added in version 1.2.
	PreferredFirstName *string `json:"preferredFirstName,omitempty" yaml:"preferredFirstName,omitempty" mapstructure:"preferredFirstName,omitempty"`

	// Model Primitive Datatype = NormalizedString. The user's preferred last name.
	// This attribute was added in version 1.2.
	PreferredLastName *string `json:"preferredLastName,omitempty" yaml:"preferredLastName,omitempty" mapstructure:"preferredLastName,omitempty"`

	// Model Primitive Datatype = NormalizedString. The user's preferred middle
	// name(s). This attribute was added in version 1.2.
	PreferredMiddleName *string `json:"preferredMiddleName,omitempty" yaml:"preferredMiddleName,omitempty" mapstructure:"preferredMiddleName,omitempty"`

	// It is possible for a user to be a member of more than one organization and to
	// have one or more roles in an organization. This attribute identifies the
	// 'sourcedId' of the primary organization.
	PrimaryOrg *OrgGUIDRefDType `json:"primaryOrg,omitempty" yaml:"primaryOrg,omitempty" mapstructure:"primaryOrg,omitempty"`

	// Model Primitive Datatype = NormalizedString. The pronoun(s) by which this
	// person is referenced. Examples (in the case of English) include 'she/her/hers',
	// 'he/him/his', 'they/them/theirs', 'ze/hir/hir', 'xe/xir', or a statement that
	// the person's name should be used instead of any pronoun.
	Pronouns *string `json:"pronouns,omitempty" yaml:"pronouns,omitempty" mapstructure:"pronouns,omitempty"`

	// The identifiers (GUIDs) for the set of resources that are to be made available
	// to the user. These are the sourcedIds that should be used for obtaining the
	// metadata about the resources using the OR 1.2 Resources Service [OR-RES-SM-12].
	Resources []ResourceGUIDRefDType `json:"resources,omitempty" yaml:"resources,omitempty" mapstructure:"resources,omitempty"`

	// The set of roles for each of the orgs to which the user is affilliated. This is
	// expressed as a set of role/org tuples.
	Roles []RoleDType `json:"roles" yaml:"roles" mapstructure:"roles"`

	// Model Primitive Datatype = NormalizedString. The SMS number for the user.
	Sms *string `json:"sms,omitempty" yaml:"sms,omitempty" mapstructure:"sms,omitempty"`

	// Model Primitive Datatype = String. The sourcedId of the object. All objects
	// MUST be identified by a Source Identifier. This is a GUID  System ID for an
	// object. This is the GUID that SYSTEMS will refer to when making API calls, or
	// when needing to identify an object. It is RECOMMENDED that systems are able to
	// map whichever local ids (e.g. database key fields) they use to SourcedId.  The
	// sourcedId of an object is considered an addressable property of an entity and
	// as such will not be treated as Personally Identifiable Information (PII) by
	// certified products.  Therefore, as a part of certification, vendors will be
	// required to declare that they will notify customers via documentation or other
	// formal and documented agreement that sourcedIds should never contain PII in
	// general, but particularly users. This means that if a customer includes a
	// student name in an enrollment.sourcedId, it will not fall to any certified
	// product to protect the enrollment.sourcedId as PII, or even the userSourcedId
	// field in the enrollment record.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// All objects MUST BE either 'active' or 'tobedeleted'.  Something which is
	// flagged 'tobedeleted' is to be considered safe to delete. Systems can delete
	// records that are flagged as such if they wish, but they are not under any
	// compulsion to do so. In v1.1 the enumeration value of 'inactive' was removed
	// and so for backwards compatibility all such marked objects should be
	// interpreted as 'tobedeleted'.
	Status UserDTypeStatus `json:"status" yaml:"status" mapstructure:"status"`

	// The set of external user identifiers that should be used for this user, if for
	// some reason the sourcedId cannot be used. This might be an active directory id,
	// an LTI id, or some other machine-readable identifier that is used for this
	// person.
	UserIds []UserIdDType `json:"userIds,omitempty" yaml:"userIds,omitempty" mapstructure:"userIds,omitempty"`

	// Model Primitive Datatype = NormalizedString. The master unique identifier for
	// this user. This is NOT the same as the user's interoperability 'sourcedId'.
	// This should be used to ensure that all of the system identifiers/accounts etc.
	// can be reconciled to the same user. How this identifier is assigned and its
	// format is beyond the scope of this specification.
	UserMasterIdentifier *string `json:"userMasterIdentifier,omitempty" yaml:"userMasterIdentifier,omitempty" mapstructure:"userMasterIdentifier,omitempty"`

	// The set of system/app/tool profiles for the user.
	UserProfiles []UserProfileDType `json:"userProfiles,omitempty" yaml:"userProfiles,omitempty" mapstructure:"userProfiles,omitempty"`

	// Model Primitive Datatype = NormalizedString. The user name assigned to the
	// user. NOTE - This has been kept for backwards compatibility with OneRoster 1.1
	// and the new 'userProfiles' characteristic SHOULD be used instead.
	Username *string `json:"username,omitempty" yaml:"username,omitempty" mapstructure:"username,omitempty"`
}

type UserDTypeEnabledUser string

const (
	UserDTypeEnabledUserFalse UserDTypeEnabledUser = "false"
	UserDTypeEnabledUserTrue  UserDTypeEnabledUser = "true"
)

var enumValues_UserDTypeEnabledUser = []any{
	"true",
	"false",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserDTypeEnabledUser) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_UserDTypeEnabledUser {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_UserDTypeEnabledUser,
			v,
		)
	}
	*j = UserDTypeEnabledUser(v)
	return nil
}

type UserDTypeStatus string

const (
	UserDTypeStatusActive      UserDTypeStatus = "active"
	UserDTypeStatusTobedeleted UserDTypeStatus = "tobedeleted"
)

var enumValues_UserDTypeStatus = []any{
	"active",
	"tobedeleted",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserDTypeStatus) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_UserDTypeStatus {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_UserDTypeStatus,
			v,
		)
	}
	*j = UserDTypeStatus(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["dateLastModified"]; raw != nil && !ok {
		return errors.New("field dateLastModified in UserDType: required")
	}
	if _, ok := raw["enabledUser"]; raw != nil && !ok {
		return errors.New("field enabledUser in UserDType: required")
	}
	if _, ok := raw["familyName"]; raw != nil && !ok {
		return errors.New("field familyName in UserDType: required")
	}
	if _, ok := raw["givenName"]; raw != nil && !ok {
		return errors.New("field givenName in UserDType: required")
	}
	if _, ok := raw["roles"]; raw != nil && !ok {
		return errors.New("field roles in UserDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in UserDType: required")
	}
	if _, ok := raw["status"]; raw != nil && !ok {
		return errors.New("field status in UserDType: required")
	}
	type Plain UserDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Roles != nil && len(plain.Roles) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "roles", 1)
	}
	*j = UserDType(plain)
	return nil
}

// This is the container for reference to a OneRoster 'User' object that has an
// allocated sourcedId (GUID).
type UserGUIDRefDType struct {
	// Model Primitive Datatype = AnyURI. The URI for the type of object being
	// referenced.
	Href string `json:"href" yaml:"href" mapstructure:"href"`

	// Model Primitive Datatype = String. The globally unique identifier of the object
	// being referenced.
	SourcedId string `json:"sourcedId" yaml:"sourcedId" mapstructure:"sourcedId"`

	// The type of object being referenced i.e. a 'user'.
	Type UserGUIDRefDTypeType `json:"type" yaml:"type" mapstructure:"type"`
}

type UserGUIDRefDTypeType string

const UserGUIDRefDTypeTypeUser UserGUIDRefDTypeType = "user"

var enumValues_UserGUIDRefDTypeType = []any{
	"user",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserGUIDRefDTypeType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_UserGUIDRefDTypeType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf(
			"invalid value (expected one of %#v): %#v",
			enumValues_UserGUIDRefDTypeType,
			v,
		)
	}
	*j = UserGUIDRefDTypeType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserGUIDRefDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["href"]; raw != nil && !ok {
		return errors.New("field href in UserGUIDRefDType: required")
	}
	if _, ok := raw["sourcedId"]; raw != nil && !ok {
		return errors.New("field sourcedId in UserGUIDRefDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in UserGUIDRefDType: required")
	}
	type Plain UserGUIDRefDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UserGUIDRefDType(plain)
	return nil
}

// This is the set of external user identifiers that should be used for this user,
// if for some reason the sourcedId cannot be used. This might be an active
// directory id, an LTI id, or some other machine-readable identifier that is used
// for this person.
type UserIdDType struct {
	// Model Primitive Datatype = String. The user identifier.
	Identifier string `json:"identifier" yaml:"identifier" mapstructure:"identifier"`

	// Model Primitive Datatype = NormalizedString. The type of identifier. This is no
	// predefined vocabuary.
	Type string `json:"type" yaml:"type" mapstructure:"type"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserIdDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["identifier"]; raw != nil && !ok {
		return errors.New("field identifier in UserIdDType: required")
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return errors.New("field type in UserIdDType: required")
	}
	type Plain UserIdDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UserIdDType(plain)
	return nil
}

// The container for the information about a User Profile that will provide the
// user with access to some system, application, tool, etc.
type UserProfileDType struct {
	// Model Primitive Datatype = NormalizedString. Identifier for the application
	// associated with the account. The nature, and how this identifier is assigned is
	// not defined by this specification. This may have a value of 'default' to denote
	// this account should be used for default access to all applications related to
	// this vendor.
	ApplicationId *string `json:"applicationId,omitempty" yaml:"applicationId,omitempty" mapstructure:"applicationId,omitempty"`

	// The set of credentials that are available for access to this profile.
	Credentials []CredentialDType `json:"credentials,omitempty" yaml:"credentials,omitempty" mapstructure:"credentials,omitempty"`

	// Model Primitive Datatype = String. A human readable description of the use of
	// the profile. This should not contain any security information for access to the
	// account.
	Description *string `json:"description,omitempty" yaml:"description,omitempty" mapstructure:"description,omitempty"`

	// Model Primitive Datatype = AnyURI. The unique identifier for the profile. This
	// does not need to be a globally unique identifier but it must be unique within
	// the scope of the user.
	ProfileId string `json:"profileId" yaml:"profileId" mapstructure:"profileId"`

	// Model Primitive Datatype = NormalizedString. The type of profile. This should
	// be a human readable label that has some significance in the context of the
	// related system, app, tool, etc.
	ProfileType string `json:"profileType" yaml:"profileType" mapstructure:"profileType"`

	// Model Primitive Datatype = NormalizedString. The unique identifier for the
	// vendor of the system, tool, app, etc. which requires the use of this profile.
	VendorId string `json:"vendorId" yaml:"vendorId" mapstructure:"vendorId"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *UserProfileDType) UnmarshalJSON(value []byte) error {
	var raw map[string]any
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["profileId"]; raw != nil && !ok {
		return errors.New("field profileId in UserProfileDType: required")
	}
	if _, ok := raw["profileType"]; raw != nil && !ok {
		return errors.New("field profileType in UserProfileDType: required")
	}
	if _, ok := raw["vendorId"]; raw != nil && !ok {
		return errors.New("field vendorId in UserProfileDType: required")
	}
	type Plain UserProfileDType
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = UserProfileDType(plain)
	return nil
}
