// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: authorization.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one

INSERT INTO auth_api_token (principal_id, name, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, principal_id, name, token_hash, created_at, last_used_at, expires_at, revoked_at
`

type CreateAPITokenParams struct {
	PrincipalID pgtype.UUID        `json:"principal_id"`
	Name        string             `json:"name"`
	TokenHash   []byte             `json:"token_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// ── API tokens ────────────────────────────────────────────────────────────────
func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (AuthApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.PrincipalID,
		arg.Name,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i AuthApiToken
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.Name,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAuthRole = `-- name: GetAuthRole :one
SELECT name, description, is_global FROM auth_role WHERE name = $1
`

func (q *Queries) GetAuthRole(ctx context.Context, name string) (AuthRole, error) {
	row := q.db.QueryRow(ctx, getAuthRole, name)
	var i AuthRole
	err := row.Scan(&i.Name, &i.Description, &i.IsGlobal)
	return i, err
}

const getPrincipal = `-- name: GetPrincipal :one
SELECT id, subject, kind, email, display_name, oneroster_user_sourced_id, disabled, created_at, modified_at FROM auth_principal WHERE id = $1
`

func (q *Queries) GetPrincipal(ctx context.Context, id pgtype.UUID) (AuthPrincipal, error) {
	row := q.db.QueryRow(ctx, getPrincipal, id)
	var i AuthPrincipal
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Kind,
		&i.Email,
		&i.DisplayName,
		&i.OnerosterUserSourcedID,
		&i.Disabled,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getPrincipalBySubject = `-- name: GetPrincipalBySubject :one
SELECT id, subject, kind, email, display_name, oneroster_user_sourced_id, disabled, created_at, modified_at FROM auth_principal WHERE subject = $1
`

func (q *Queries) GetPrincipalBySubject(ctx context.Context, subject string) (AuthPrincipal, error) {
	row := q.db.QueryRow(ctx, getPrincipalBySubject, subject)
	var i AuthPrincipal
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Kind,
		&i.Email,
		&i.DisplayName,
		&i.OnerosterUserSourcedID,
		&i.Disabled,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const getPrincipalByTokenHash = `-- name: GetPrincipalByTokenHash :one
SELECT p.id, p.subject, p.kind, p.email, p.display_name, p.oneroster_user_sourced_id, p.disabled, p.created_at, p.modified_at
FROM auth_api_token t
JOIN auth_principal p ON p.id = t.principal_id
WHERE t.token_hash = $1
  AND t.revoked_at IS NULL
  AND (t.expires_at IS NULL OR t.expires_at > NOW())
  AND NOT p.disabled
`

// The authentication path: hash the presented bearer token, look it up here. A
// revoked, expired, or disabled row returns no principal.
func (q *Queries) GetPrincipalByTokenHash(ctx context.Context, tokenHash []byte) (AuthPrincipal, error) {
	row := q.db.QueryRow(ctx, getPrincipalByTokenHash, tokenHash)
	var i AuthPrincipal
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Kind,
		&i.Email,
		&i.DisplayName,
		&i.OnerosterUserSourcedID,
		&i.Disabled,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const grantRole = `-- name: GrantRole :one

INSERT INTO auth_grant (principal_id, role_name, org_sourced_id, granted_by, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (principal_id, role_name, org_sourced_id) DO UPDATE SET
    granted_by = EXCLUDED.granted_by,
    granted_at = NOW(),
    expires_at = EXCLUDED.expires_at
RETURNING id, principal_id, role_name, org_sourced_id, granted_by, granted_at, expires_at
`

type GrantRoleParams struct {
	PrincipalID  pgtype.UUID        `json:"principal_id"`
	RoleName     string             `json:"role_name"`
	OrgSourcedID pgtype.Text        `json:"org_sourced_id"`
	GrantedBy    pgtype.UUID        `json:"granted_by"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

// ── Grants ────────────────────────────────────────────────────────────────────
// A repeat grant refreshes the expiry and the audit trail rather than erroring,
// so re-running a provisioning script is safe.
func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) (AuthGrant, error) {
	row := q.db.QueryRow(ctx, grantRole,
		arg.PrincipalID,
		arg.RoleName,
		arg.OrgSourcedID,
		arg.GrantedBy,
		arg.ExpiresAt,
	)
	var i AuthGrant
	err := row.Scan(
		&i.ID,
		&i.PrincipalID,
		&i.RoleName,
		&i.OrgSourcedID,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listAPITokensForPrincipal = `-- name: ListAPITokensForPrincipal :many
SELECT id, principal_id, name, created_at, last_used_at, expires_at, revoked_at
FROM auth_api_token
WHERE principal_id = $1
ORDER BY created_at DESC
`

type ListAPITokensForPrincipalRow struct {
	ID          pgtype.UUID        `json:"id"`
	PrincipalID pgtype.UUID        `json:"principal_id"`
	Name        string             `json:"name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

// token_hash is deliberately not selected: nothing outside authentication needs
// it, and a listing is the likeliest thing to end up in a log.
func (q *Queries) ListAPITokensForPrincipal(ctx context.Context, principalID pgtype.UUID) ([]ListAPITokensForPrincipalRow, error) {
	rows, err := q.db.Query(ctx, listAPITokensForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPITokensForPrincipalRow{}
	for rows.Next() {
		var i ListAPITokensForPrincipalRow
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.Name,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccessibleOrgs = `-- name: ListAccessibleOrgs :many
SELECT DISTINCT o.sourced_id, o.status, o.date_last_modified, o.metadata, o.name, o.type, o.identifier, o.parent_sourced_id, o.parent_href
FROM auth_effective_access a
JOIN org o ON o.sourced_id = a.org_sourced_id
WHERE a.subject = $1 AND a.role_name = ANY($2::text[])
ORDER BY o.sourced_id
`

type ListAccessibleOrgsParams struct {
	Subject string   `json:"subject"`
	Column2 []string `json:"column_2"`
}

// Every org this subject may touch in any of the given roles. Used to scope a
// list response rather than filtering it per row.
func (q *Queries) ListAccessibleOrgs(ctx context.Context, arg ListAccessibleOrgsParams) ([]Org, error) {
	rows, err := q.db.Query(ctx, listAccessibleOrgs, arg.Subject, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Org{}
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.SourcedID,
			&i.Status,
			&i.DateLastModified,
			&i.Metadata,
			&i.Name,
			&i.Type,
			&i.Identifier,
			&i.ParentSourcedID,
			&i.ParentHref,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthRoles = `-- name: ListAuthRoles :many

SELECT name, description, is_global FROM auth_role ORDER BY name
`

// ── Roles ─────────────────────────────────────────────────────────────────────
func (q *Queries) ListAuthRoles(ctx context.Context) ([]AuthRole, error) {
	rows, err := q.db.Query(ctx, listAuthRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthRole{}
	for rows.Next() {
		var i AuthRole
		if err := rows.Scan(&i.Name, &i.Description, &i.IsGlobal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForOrg = `-- name: ListGrantsForOrg :many
SELECT g.id, g.principal_id, g.role_name, g.org_sourced_id, g.granted_by, g.granted_at, g.expires_at, p.subject, p.email, closure.depth
FROM auth_grant g
JOIN auth_principal p ON p.id = g.principal_id
JOIN org_closure closure ON closure.ancestor_sourced_id = g.org_sourced_id
WHERE closure.descendant_sourced_id = $1
ORDER BY closure.depth, p.subject
`

type ListGrantsForOrgRow struct {
	ID           pgtype.UUID        `json:"id"`
	PrincipalID  pgtype.UUID        `json:"principal_id"`
	RoleName     string             `json:"role_name"`
	OrgSourcedID pgtype.Text        `json:"org_sourced_id"`
	GrantedBy    pgtype.UUID        `json:"granted_by"`
	GrantedAt    pgtype.Timestamptz `json:"granted_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	Subject      string             `json:"subject"`
	Email        pgtype.Text        `json:"email"`
	Depth        int32              `json:"depth"`
}

// Answers "who has access to this school, and who gave it to them?" — including
// grants inherited from an ancestor org, which is the part a plain lookup on
// auth_grant would miss.
func (q *Queries) ListGrantsForOrg(ctx context.Context, descendantSourcedID string) ([]ListGrantsForOrgRow, error) {
	rows, err := q.db.Query(ctx, listGrantsForOrg, descendantSourcedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantsForOrgRow{}
	for rows.Next() {
		var i ListGrantsForOrgRow
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.RoleName,
			&i.OrgSourcedID,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.Subject,
			&i.Email,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrantsForPrincipal = `-- name: ListGrantsForPrincipal :many
SELECT g.id, g.principal_id, g.role_name, g.org_sourced_id, g.granted_by, g.granted_at, g.expires_at, r.is_global
FROM auth_grant g
JOIN auth_role r ON r.name = g.role_name
WHERE g.principal_id = $1
ORDER BY g.role_name, g.org_sourced_id
`

type ListGrantsForPrincipalRow struct {
	ID           pgtype.UUID        `json:"id"`
	PrincipalID  pgtype.UUID        `json:"principal_id"`
	RoleName     string             `json:"role_name"`
	OrgSourcedID pgtype.Text        `json:"org_sourced_id"`
	GrantedBy    pgtype.UUID        `json:"granted_by"`
	GrantedAt    pgtype.Timestamptz `json:"granted_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	IsGlobal     bool               `json:"is_global"`
}

func (q *Queries) ListGrantsForPrincipal(ctx context.Context, principalID pgtype.UUID) ([]ListGrantsForPrincipalRow, error) {
	rows, err := q.db.Query(ctx, listGrantsForPrincipal, principalID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGrantsForPrincipalRow{}
	for rows.Next() {
		var i ListGrantsForPrincipalRow
		if err := rows.Scan(
			&i.ID,
			&i.PrincipalID,
			&i.RoleName,
			&i.OrgSourcedID,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.ExpiresAt,
			&i.IsGlobal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrincipals = `-- name: ListPrincipals :many
SELECT id, subject, kind, email, display_name, oneroster_user_sourced_id, disabled, created_at, modified_at FROM auth_principal
WHERE subject > $1::text
ORDER BY subject
LIMIT $2::int
`

type ListPrincipalsParams struct {
	AfterSubject string `json:"after_subject"`
	PageSize     int32  `json:"page_size"`
}

// Keyset paged on subject, which is UNIQUE and therefore a total order. An empty
// @after_subject starts at the first page.
func (q *Queries) ListPrincipals(ctx context.Context, arg ListPrincipalsParams) ([]AuthPrincipal, error) {
	rows, err := q.db.Query(ctx, listPrincipals, arg.AfterSubject, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthPrincipal{}
	for rows.Next() {
		var i AuthPrincipal
		if err := rows.Scan(
			&i.ID,
			&i.Subject,
			&i.Kind,
			&i.Email,
			&i.DisplayName,
			&i.OnerosterUserSourcedID,
			&i.Disabled,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForSubject = `-- name: ListRolesForSubject :many
SELECT DISTINCT role_name FROM auth_effective_access
WHERE subject = $1
ORDER BY role_name
`

func (q *Queries) ListRolesForSubject(ctx context.Context, subject string) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolesForSubject, subject)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var role_name string
		if err := rows.Scan(&role_name); err != nil {
			return nil, err
		}
		items = append(items, role_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const principalHasAnyRoleForOrg = `-- name: PrincipalHasAnyRoleForOrg :one
SELECT EXISTS (
    SELECT 1 FROM auth_effective_access
    WHERE subject = $1 AND role_name = ANY($2::text[]) AND org_sourced_id = $3
) AS allowed
`

type PrincipalHasAnyRoleForOrgParams struct {
	Subject      string   `json:"subject"`
	Column2      []string `json:"column_2"`
	OrgSourcedID string   `json:"org_sourced_id"`
}

func (q *Queries) PrincipalHasAnyRoleForOrg(ctx context.Context, arg PrincipalHasAnyRoleForOrgParams) (bool, error) {
	row := q.db.QueryRow(ctx, principalHasAnyRoleForOrg, arg.Subject, arg.Column2, arg.OrgSourcedID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const principalHasRoleForOrg = `-- name: PrincipalHasRoleForOrg :one

SELECT EXISTS (
    SELECT 1 FROM auth_effective_access
    WHERE subject = $1 AND role_name = $2 AND org_sourced_id = $3
) AS allowed
`

type PrincipalHasRoleForOrgParams struct {
	Subject      string `json:"subject"`
	RoleName     string `json:"role_name"`
	OrgSourcedID string `json:"org_sourced_id"`
}

// ── Access checks ─────────────────────────────────────────────────────────────
// The interceptor's question: may this subject act in this role on this org?
func (q *Queries) PrincipalHasRoleForOrg(ctx context.Context, arg PrincipalHasRoleForOrgParams) (bool, error) {
	row := q.db.QueryRow(ctx, principalHasRoleForOrg, arg.Subject, arg.RoleName, arg.OrgSourcedID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const principalIsGlobalAdmin = `-- name: PrincipalIsGlobalAdmin :one
SELECT EXISTS (
    SELECT 1
    FROM auth_grant g
    JOIN auth_principal p ON p.id = g.principal_id
    JOIN auth_role r ON r.name = g.role_name
    WHERE p.subject = $1
      AND NOT p.disabled
      AND r.is_global
      AND (g.expires_at IS NULL OR g.expires_at > NOW())
) AS allowed
`

// Checked without reference to an org, so it answers correctly on an empty
// database — where the cross join in auth_effective_access yields no rows.
func (q *Queries) PrincipalIsGlobalAdmin(ctx context.Context, subject string) (bool, error) {
	row := q.db.QueryRow(ctx, principalIsGlobalAdmin, subject)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const revokeAPIToken = `-- name: RevokeAPIToken :exec
UPDATE auth_api_token SET revoked_at = NOW() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAPIToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIToken, id)
	return err
}

const revokeGrant = `-- name: RevokeGrant :exec
DELETE FROM auth_grant WHERE id = $1
`

func (q *Queries) RevokeGrant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeGrant, id)
	return err
}

const revokeRoleForPrincipal = `-- name: RevokeRoleForPrincipal :exec
DELETE FROM auth_grant
WHERE principal_id = $1
  AND role_name = $2
  AND org_sourced_id IS NOT DISTINCT FROM $3
`

type RevokeRoleForPrincipalParams struct {
	PrincipalID  pgtype.UUID `json:"principal_id"`
	RoleName     string      `json:"role_name"`
	OrgSourcedID pgtype.Text `json:"org_sourced_id"`
}

func (q *Queries) RevokeRoleForPrincipal(ctx context.Context, arg RevokeRoleForPrincipalParams) error {
	_, err := q.db.Exec(ctx, revokeRoleForPrincipal, arg.PrincipalID, arg.RoleName, arg.OrgSourcedID)
	return err
}

const setPrincipalDisabled = `-- name: SetPrincipalDisabled :one
UPDATE auth_principal
SET disabled = $2, modified_at = NOW()
WHERE id = $1
RETURNING id, subject, kind, email, display_name, oneroster_user_sourced_id, disabled, created_at, modified_at
`

type SetPrincipalDisabledParams struct {
	ID       pgtype.UUID `json:"id"`
	Disabled bool        `json:"disabled"`
}

func (q *Queries) SetPrincipalDisabled(ctx context.Context, arg SetPrincipalDisabledParams) (AuthPrincipal, error) {
	row := q.db.QueryRow(ctx, setPrincipalDisabled, arg.ID, arg.Disabled)
	var i AuthPrincipal
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Kind,
		&i.Email,
		&i.DisplayName,
		&i.OnerosterUserSourcedID,
		&i.Disabled,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const touchAPToken = `-- name: TouchAPToken :exec
UPDATE auth_api_token SET last_used_at = NOW() WHERE token_hash = $1
`

func (q *Queries) TouchAPToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, touchAPToken, tokenHash)
	return err
}

const upsertPrincipal = `-- name: UpsertPrincipal :one


INSERT INTO auth_principal (
    subject, kind, email, display_name, oneroster_user_sourced_id, disabled
) VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (subject) DO UPDATE SET
    kind                      = EXCLUDED.kind,
    email                     = EXCLUDED.email,
    display_name              = EXCLUDED.display_name,
    oneroster_user_sourced_id = EXCLUDED.oneroster_user_sourced_id,
    disabled                  = EXCLUDED.disabled,
    modified_at               = NOW()
RETURNING id, subject, kind, email, display_name, oneroster_user_sourced_id, disabled, created_at, modified_at
`

type UpsertPrincipalParams struct {
	Subject                string      `json:"subject"`
	Kind                   string      `json:"kind"`
	Email                  pgtype.Text `json:"email"`
	DisplayName            pgtype.Text `json:"display_name"`
	OnerosterUserSourcedID pgtype.Text `json:"oneroster_user_sourced_id"`
	Disabled               bool        `json:"disabled"`
}

// Authorization queries: who may manage which rosters.
//
// The access checks read auth_effective_access, which already expands org
// subtrees and filters expired grants and disabled principals, so a request path
// never runs the recursive walk itself.
// ── Principals ────────────────────────────────────────────────────────────────
func (q *Queries) UpsertPrincipal(ctx context.Context, arg UpsertPrincipalParams) (AuthPrincipal, error) {
	row := q.db.QueryRow(ctx, upsertPrincipal,
		arg.Subject,
		arg.Kind,
		arg.Email,
		arg.DisplayName,
		arg.OnerosterUserSourcedID,
		arg.Disabled,
	)
	var i AuthPrincipal
	err := row.Scan(
		&i.ID,
		&i.Subject,
		&i.Kind,
		&i.Email,
		&i.DisplayName,
		&i.OnerosterUserSourcedID,
		&i.Disabled,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}
