// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: curation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const academicSessionExists = `-- name: AcademicSessionExists :one
SELECT EXISTS (
    SELECT 1 FROM academic_session WHERE sourced_id = $1::text
) AS present
`

// After a guarded write affects nothing and the caller IS a roster_admin, this
// says whether the row was missing (not_found) or its version moved (aborted).
func (q *Queries) AcademicSessionExists(ctx context.Context, sourcedID string) (bool, error) {
	row := q.db.QueryRow(ctx, academicSessionExists, sourcedID)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const canCurateOrg = `-- name: CanCurateOrg :one

SELECT EXISTS (
    SELECT 1 FROM auth_effective_access a
    WHERE a.subject = $1::text
      AND a.org_sourced_id = $2::text
      AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
    UNION ALL
    SELECT 1
    FROM auth_grant g
    JOIN auth_principal p ON p.id = g.principal_id
    JOIN auth_role r ON r.name = g.role_name
    WHERE p.subject = $1::text
      AND NOT p.disabled
      AND r.is_global
      AND g.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
      AND (g.expires_at IS NULL OR g.expires_at > NOW())
) AS allowed
`

type CanCurateOrgParams struct {
	Subject      string `json:"subject"`
	OrgSourcedID string `json:"org_sourced_id"`
}

// Curation writes: the statements behind the Create/Update/Delete RPCs.
//
// Three invariants hold for every statement here.
//
//  1. Authorization is in the statement. An insert is
//     `INSERT ... SELECT ... WHERE EXISTS (<curating access>)`; an update or
//     delete carries the same predicate as a WHERE conjunct. A caller without
//     the grant affects zero rows, and the handler reports that as not_found —
//     the same answer an out-of-scope read gets, so a write cannot be used to
//     probe for an entity's existence.
//
//  2. Writing needs more than reading. The curating roles are roster_admin,
//     district_admin, school_admin and data_provider. roster_reader is absent,
//     so a read-only grant cannot write no matter which RPC it calls.
//
//  3. Updates are version-checked on date_last_modified. The caller sends the
//     value it read; a mismatch affects zero rows. Without this a nightly
//     import and a curator editing the same record would silently overwrite
//     each other, and the loser would never know.
//
// The global-grant branch is spelled out separately in every predicate rather
// than relying on auth_effective_access alone. That view expands a global grant
// with `CROSS JOIN org`, so it yields no rows while org is empty — meaning a
// global administrator could not create the very first org. The extra clause is
// what makes bootstrapping possible.
// Whether this subject may write to the given org. Used to distinguish "you may
// not" from "it does not exist" after a guarded write affects nothing.
func (q *Queries) CanCurateOrg(ctx context.Context, arg CanCurateOrgParams) (bool, error) {
	row := q.db.QueryRow(ctx, canCurateOrg, arg.Subject, arg.OrgSourcedID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const classIsVisibleForCuration = `-- name: ClassIsVisibleForCuration :one
SELECT EXISTS (
    SELECT 1 FROM class c
    JOIN auth_effective_access a ON a.org_sourced_id = c.school_sourced_id
    WHERE c.sourced_id = $1::text
      AND a.subject = $2::text
      AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
) AS visible
`

type ClassIsVisibleForCurationParams struct {
	SourcedID string `json:"sourced_id"`
	Subject   string `json:"subject"`
}

func (q *Queries) ClassIsVisibleForCuration(ctx context.Context, arg ClassIsVisibleForCurationParams) (bool, error) {
	row := q.db.QueryRow(ctx, classIsVisibleForCuration, arg.SourcedID, arg.Subject)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}

const courseIsVisibleForCuration = `-- name: CourseIsVisibleForCuration :one
SELECT EXISTS (
    SELECT 1 FROM course c
    JOIN auth_effective_access a ON a.org_sourced_id = c.org_sourced_id
    WHERE c.sourced_id = $1::text
      AND a.subject = $2::text
      AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
) AS visible
`

type CourseIsVisibleForCurationParams struct {
	SourcedID string `json:"sourced_id"`
	Subject   string `json:"subject"`
}

func (q *Queries) CourseIsVisibleForCuration(ctx context.Context, arg CourseIsVisibleForCurationParams) (bool, error) {
	row := q.db.QueryRow(ctx, courseIsVisibleForCuration, arg.SourcedID, arg.Subject)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}

const createAcademicSessionGuarded = `-- name: CreateAcademicSessionGuarded :one
INSERT INTO academic_session (
    sourced_id, status, date_last_modified, metadata, title, start_date,
    end_date, type, school_year, parent_sourced_id, parent_href
)
SELECT $1::text, $2::text, $3::timestamptz,
       $4::jsonb, $5::text, $6::date, $7::date,
       $8::text, $9::text,
       $10::text, $11::text
WHERE EXISTS (
    SELECT 1
    FROM auth_grant g
    JOIN auth_principal p ON p.id = g.principal_id
    JOIN auth_role r ON r.name = g.role_name
    WHERE p.subject = $12::text
      AND NOT p.disabled
      AND r.is_global
      AND g.role_name = 'roster_admin'
      AND (g.expires_at IS NULL OR g.expires_at > NOW())
)
RETURNING sourced_id, status, date_last_modified, metadata, title, start_date, end_date, type, school_year, parent_sourced_id, parent_href
`

type CreateAcademicSessionGuardedParams struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	Title            string             `json:"title"`
	StartDate        pgtype.Date        `json:"start_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	Type             string             `json:"type"`
	SchoolYear       string             `json:"school_year"`
	ParentSourcedID  pgtype.Text        `json:"parent_sourced_id"`
	ParentHref       pgtype.Text        `json:"parent_href"`
	Subject          string             `json:"subject"`
}

func (q *Queries) CreateAcademicSessionGuarded(ctx context.Context, arg CreateAcademicSessionGuardedParams) (AcademicSession, error) {
	row := q.db.QueryRow(ctx, createAcademicSessionGuarded,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.Type,
		arg.SchoolYear,
		arg.ParentSourcedID,
		arg.ParentHref,
		arg.Subject,
	)
	var i AcademicSession
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.SchoolYear,
		&i.ParentSourcedID,
		&i.ParentHref,
	)
	return i, err
}

const createClassGuarded = `-- name: CreateClassGuarded :one

INSERT INTO class (
    sourced_id, status, date_last_modified, metadata, title, class_code,
    class_type, location, grades, subjects, subject_codes, periods,
    course_sourced_id, course_href, school_sourced_id, school_href
)
SELECT $1::text, $2::text, $3::timestamptz,
       $4::jsonb, $5::text, $6::text,
       $7::text, $8::text,
       $9::text[], $10::text[], $11::text[], $12::text[],
       $13::text, $14::text,
       $15::text, $16::text
WHERE EXISTS (
    SELECT 1 FROM auth_effective_access a
    WHERE a.subject = $17::text
      AND a.org_sourced_id = $15::text
      AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
)
RETURNING sourced_id, status, date_last_modified, metadata, title, class_code, class_type, location, grades, subjects, subject_codes, periods, course_sourced_id, course_href, school_sourced_id, school_href
`

type CreateClassGuardedParams struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	Title            string             `json:"title"`
	ClassCode        pgtype.Text        `json:"class_code"`
	ClassType        pgtype.Text        `json:"class_type"`
	Location         pgtype.Text        `json:"location"`
	Grades           []string           `json:"grades"`
	Subjects         []string           `json:"subjects"`
	SubjectCodes     []string           `json:"subject_codes"`
	Periods          []string           `json:"periods"`
	CourseSourcedID  string             `json:"course_sourced_id"`
	CourseHref       pgtype.Text        `json:"course_href"`
	SchoolSourcedID  string             `json:"school_sourced_id"`
	SchoolHref       pgtype.Text        `json:"school_href"`
	Subject          string             `json:"subject"`
}

// ── Class ─────────────────────────────────────────────────────────────────────
// Scoped on school_sourced_id, which is NOT NULL for a class, so there is no
// bootstrap case here: a class always belongs to a school that already exists.
func (q *Queries) CreateClassGuarded(ctx context.Context, arg CreateClassGuardedParams) (Class, error) {
	row := q.db.QueryRow(ctx, createClassGuarded,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.Title,
		arg.ClassCode,
		arg.ClassType,
		arg.Location,
		arg.Grades,
		arg.Subjects,
		arg.SubjectCodes,
		arg.Periods,
		arg.CourseSourcedID,
		arg.CourseHref,
		arg.SchoolSourcedID,
		arg.SchoolHref,
		arg.Subject,
	)
	var i Class
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.ClassCode,
		&i.ClassType,
		&i.Location,
		&i.Grades,
		&i.Subjects,
		&i.SubjectCodes,
		&i.Periods,
		&i.CourseSourcedID,
		&i.CourseHref,
		&i.SchoolSourcedID,
		&i.SchoolHref,
	)
	return i, err
}

const createCourseGuarded = `-- name: CreateCourseGuarded :one

INSERT INTO course (
    sourced_id, status, date_last_modified, metadata, title, course_code,
    grades, subjects, subject_codes, org_sourced_id, org_href,
    school_year_sourced_id, school_year_href
)
SELECT $1::text, $2::text, $3::timestamptz,
       $4::jsonb, $5::text, $6::text,
       $7::text[], $8::text[], $9::text[],
       $10::text, $11::text,
       $12::text, $13::text
WHERE EXISTS (
    SELECT 1 FROM auth_effective_access a
    WHERE a.subject = $14::text
      AND a.org_sourced_id = COALESCE($10::text, '')
      AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
)
RETURNING sourced_id, status, date_last_modified, metadata, title, course_code, grades, subjects, subject_codes, org_sourced_id, org_href, school_year_sourced_id, school_year_href
`

type CreateCourseGuardedParams struct {
	SourcedID           string             `json:"sourced_id"`
	Status              string             `json:"status"`
	DateLastModified    pgtype.Timestamptz `json:"date_last_modified"`
	Metadata            []byte             `json:"metadata"`
	Title               string             `json:"title"`
	CourseCode          string             `json:"course_code"`
	Grades              []string           `json:"grades"`
	Subjects            []string           `json:"subjects"`
	SubjectCodes        []string           `json:"subject_codes"`
	OrgSourcedID        pgtype.Text        `json:"org_sourced_id"`
	OrgHref             pgtype.Text        `json:"org_href"`
	SchoolYearSourcedID pgtype.Text        `json:"school_year_sourced_id"`
	SchoolYearHref      pgtype.Text        `json:"school_year_href"`
	Subject             string             `json:"subject"`
}

// ── Course ────────────────────────────────────────────────────────────────────
func (q *Queries) CreateCourseGuarded(ctx context.Context, arg CreateCourseGuardedParams) (Course, error) {
	row := q.db.QueryRow(ctx, createCourseGuarded,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.Title,
		arg.CourseCode,
		arg.Grades,
		arg.Subjects,
		arg.SubjectCodes,
		arg.OrgSourcedID,
		arg.OrgHref,
		arg.SchoolYearSourcedID,
		arg.SchoolYearHref,
		arg.Subject,
	)
	var i Course
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.CourseCode,
		&i.Grades,
		&i.Subjects,
		&i.SubjectCodes,
		&i.OrgSourcedID,
		&i.OrgHref,
		&i.SchoolYearSourcedID,
		&i.SchoolYearHref,
	)
	return i, err
}

const createEnrollmentGuarded = `-- name: CreateEnrollmentGuarded :one

INSERT INTO enrollment (
    sourced_id, status, date_last_modified, metadata, user_sourced_id,
    user_href, class_sourced_id, class_href, school_sourced_id, school_href,
    role, is_primary, begin_date, end_date
)
SELECT $1::text, $2::text, $3::timestamptz,
       $4::jsonb, $5::text, $6::text,
       $7::text, $8::text,
       $9::text, $10::text,
       $11::text, $12::boolean,
       $13::date, $14::date
WHERE EXISTS (
    SELECT 1 FROM auth_effective_access a
    WHERE a.subject = $15::text
      AND a.org_sourced_id = $9::text
      AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
)
RETURNING sourced_id, status, date_last_modified, metadata, user_sourced_id, user_href, class_sourced_id, class_href, school_sourced_id, school_href, role, is_primary, begin_date, end_date
`

type CreateEnrollmentGuardedParams struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	UserSourcedID    string             `json:"user_sourced_id"`
	UserHref         pgtype.Text        `json:"user_href"`
	ClassSourcedID   string             `json:"class_sourced_id"`
	ClassHref        pgtype.Text        `json:"class_href"`
	SchoolSourcedID  string             `json:"school_sourced_id"`
	SchoolHref       pgtype.Text        `json:"school_href"`
	Role             string             `json:"role"`
	IsPrimary        pgtype.Bool        `json:"is_primary"`
	BeginDate        pgtype.Date        `json:"begin_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	Subject          string             `json:"subject"`
}

// ── Enrollment ────────────────────────────────────────────────────────────────
func (q *Queries) CreateEnrollmentGuarded(ctx context.Context, arg CreateEnrollmentGuardedParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, createEnrollmentGuarded,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.UserSourcedID,
		arg.UserHref,
		arg.ClassSourcedID,
		arg.ClassHref,
		arg.SchoolSourcedID,
		arg.SchoolHref,
		arg.Role,
		arg.IsPrimary,
		arg.BeginDate,
		arg.EndDate,
		arg.Subject,
	)
	var i Enrollment
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.UserSourcedID,
		&i.UserHref,
		&i.ClassSourcedID,
		&i.ClassHref,
		&i.SchoolSourcedID,
		&i.SchoolHref,
		&i.Role,
		&i.IsPrimary,
		&i.BeginDate,
		&i.EndDate,
	)
	return i, err
}

const createOrgGuarded = `-- name: CreateOrgGuarded :one

INSERT INTO org (
    sourced_id, status, date_last_modified, metadata, name, type, identifier,
    parent_sourced_id, parent_href
)
SELECT $1::text, $2::text, $3::timestamptz,
       $4::jsonb, $5::text, $6::text, $7::text,
       $8::text, $9::text
WHERE EXISTS (
    SELECT 1 FROM auth_effective_access a
    WHERE a.subject = $10::text
      AND a.org_sourced_id = COALESCE($8::text, '')
      AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
) OR EXISTS (
    SELECT 1
    FROM auth_grant g
    JOIN auth_principal p ON p.id = g.principal_id
    JOIN auth_role r ON r.name = g.role_name
    WHERE p.subject = $10::text
      AND NOT p.disabled
      AND r.is_global
      AND g.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
      AND (g.expires_at IS NULL OR g.expires_at > NOW())
)
RETURNING sourced_id, status, date_last_modified, metadata, name, type, identifier, parent_sourced_id, parent_href
`

type CreateOrgGuardedParams struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	Name             string             `json:"name"`
	Type             string             `json:"type"`
	Identifier       string             `json:"identifier"`
	ParentSourcedID  pgtype.Text        `json:"parent_sourced_id"`
	ParentHref       pgtype.Text        `json:"parent_href"`
	Subject          string             `json:"subject"`
}

// ── Org ───────────────────────────────────────────────────────────────────────
// Scoped against the parent org: creating a school under a district is a change
// to that district's subtree. A root org (no parent) therefore requires a global
// curating grant, which is the bootstrap path.
func (q *Queries) CreateOrgGuarded(ctx context.Context, arg CreateOrgGuardedParams) (Org, error) {
	row := q.db.QueryRow(ctx, createOrgGuarded,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.Name,
		arg.Type,
		arg.Identifier,
		arg.ParentSourcedID,
		arg.ParentHref,
		arg.Subject,
	)
	var i Org
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Name,
		&i.Type,
		&i.Identifier,
		&i.ParentSourcedID,
		&i.ParentHref,
	)
	return i, err
}

const createUserGuarded = `-- name: CreateUserGuarded :one

INSERT INTO oneroster_user (
    sourced_id, status, date_last_modified, metadata, user_master_identifier,
    username, enabled_user, given_name, family_name, middle_name,
    preferred_first_name, preferred_last_name, preferred_middle_name, pronouns,
    grades, identifier, email, sms, phone, password,
    primary_org_sourced_id, primary_org_href
)
SELECT $1::text, $2::text, $3::timestamptz,
       $4::jsonb, $5::text,
       $6::text, $7::boolean,
       $8::text, $9::text, $10::text,
       $11::text, $12::text,
       $13::text, $14::text,
       $15::text[], $16::text, $17::text,
       $18::text, $19::text, $20::text,
       $21::text, $22::text
WHERE EXISTS (
    SELECT 1 FROM auth_effective_access a
    WHERE a.subject = $23::text
      AND a.org_sourced_id = $24::text
      AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
)
RETURNING sourced_id, status, date_last_modified, metadata, user_master_identifier, username, enabled_user, given_name, family_name, middle_name, preferred_first_name, preferred_last_name, preferred_middle_name, pronouns, grades, identifier, email, sms, phone, password, primary_org_sourced_id, primary_org_href
`

type CreateUserGuardedParams struct {
	SourcedID            string             `json:"sourced_id"`
	Status               string             `json:"status"`
	DateLastModified     pgtype.Timestamptz `json:"date_last_modified"`
	Metadata             []byte             `json:"metadata"`
	UserMasterIdentifier pgtype.Text        `json:"user_master_identifier"`
	Username             pgtype.Text        `json:"username"`
	EnabledUser          bool               `json:"enabled_user"`
	GivenName            string             `json:"given_name"`
	FamilyName           string             `json:"family_name"`
	MiddleName           pgtype.Text        `json:"middle_name"`
	PreferredFirstName   pgtype.Text        `json:"preferred_first_name"`
	PreferredLastName    pgtype.Text        `json:"preferred_last_name"`
	PreferredMiddleName  pgtype.Text        `json:"preferred_middle_name"`
	Pronouns             pgtype.Text        `json:"pronouns"`
	Grades               []string           `json:"grades"`
	Identifier           pgtype.Text        `json:"identifier"`
	Email                pgtype.Text        `json:"email"`
	Sms                  pgtype.Text        `json:"sms"`
	Phone                pgtype.Text        `json:"phone"`
	Password             pgtype.Text        `json:"password"`
	PrimaryOrgSourcedID  pgtype.Text        `json:"primary_org_sourced_id"`
	PrimaryOrgHref       pgtype.Text        `json:"primary_org_href"`
	Subject              string             `json:"subject"`
	ScopeOrgSourcedID    string             `json:"scope_org_sourced_id"`
}

// ── User ──────────────────────────────────────────────────────────────────────
// Scoped on the org named in the request rather than on the user's roles, which
// do not exist yet at creation time. The handler passes the primary org.
func (q *Queries) CreateUserGuarded(ctx context.Context, arg CreateUserGuardedParams) (OnerosterUser, error) {
	row := q.db.QueryRow(ctx, createUserGuarded,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.UserMasterIdentifier,
		arg.Username,
		arg.EnabledUser,
		arg.GivenName,
		arg.FamilyName,
		arg.MiddleName,
		arg.PreferredFirstName,
		arg.PreferredLastName,
		arg.PreferredMiddleName,
		arg.Pronouns,
		arg.Grades,
		arg.Identifier,
		arg.Email,
		arg.Sms,
		arg.Phone,
		arg.Password,
		arg.PrimaryOrgSourcedID,
		arg.PrimaryOrgHref,
		arg.Subject,
		arg.ScopeOrgSourcedID,
	)
	var i OnerosterUser
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.UserMasterIdentifier,
		&i.Username,
		&i.EnabledUser,
		&i.GivenName,
		&i.FamilyName,
		&i.MiddleName,
		&i.PreferredFirstName,
		&i.PreferredLastName,
		&i.PreferredMiddleName,
		&i.Pronouns,
		&i.Grades,
		&i.Identifier,
		&i.Email,
		&i.Sms,
		&i.Phone,
		&i.Password,
		&i.PrimaryOrgSourcedID,
		&i.PrimaryOrgHref,
	)
	return i, err
}

const deleteAcademicSessionGuarded = `-- name: DeleteAcademicSessionGuarded :one
UPDATE academic_session SET
    status             = 'tobedeleted',
    date_last_modified = $1::timestamptz
WHERE sourced_id = $2::text
  AND EXISTS (
      SELECT 1
      FROM auth_grant g
      JOIN auth_principal p ON p.id = g.principal_id
      JOIN auth_role r ON r.name = g.role_name
      WHERE p.subject = $3::text
        AND NOT p.disabled
        AND r.is_global
        AND g.role_name = 'roster_admin'
        AND (g.expires_at IS NULL OR g.expires_at > NOW())
  )
RETURNING sourced_id, status, date_last_modified, metadata, title, start_date, end_date, type, school_year, parent_sourced_id, parent_href
`

type DeleteAcademicSessionGuardedParams struct {
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	SourcedID        string             `json:"sourced_id"`
	Subject          string             `json:"subject"`
}

func (q *Queries) DeleteAcademicSessionGuarded(ctx context.Context, arg DeleteAcademicSessionGuardedParams) (AcademicSession, error) {
	row := q.db.QueryRow(ctx, deleteAcademicSessionGuarded, arg.DateLastModified, arg.SourcedID, arg.Subject)
	var i AcademicSession
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.SchoolYear,
		&i.ParentSourcedID,
		&i.ParentHref,
	)
	return i, err
}

const deleteClassGuarded = `-- name: DeleteClassGuarded :one
UPDATE class SET
    status             = 'tobedeleted',
    date_last_modified = $1::timestamptz
WHERE sourced_id = $2::text
  AND EXISTS (
      SELECT 1 FROM auth_effective_access a
      WHERE a.subject = $3::text
        AND a.org_sourced_id = class.school_sourced_id
        AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
  )
RETURNING sourced_id, status, date_last_modified, metadata, title, class_code, class_type, location, grades, subjects, subject_codes, periods, course_sourced_id, course_href, school_sourced_id, school_href
`

type DeleteClassGuardedParams struct {
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	SourcedID        string             `json:"sourced_id"`
	Subject          string             `json:"subject"`
}

func (q *Queries) DeleteClassGuarded(ctx context.Context, arg DeleteClassGuardedParams) (Class, error) {
	row := q.db.QueryRow(ctx, deleteClassGuarded, arg.DateLastModified, arg.SourcedID, arg.Subject)
	var i Class
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.ClassCode,
		&i.ClassType,
		&i.Location,
		&i.Grades,
		&i.Subjects,
		&i.SubjectCodes,
		&i.Periods,
		&i.CourseSourcedID,
		&i.CourseHref,
		&i.SchoolSourcedID,
		&i.SchoolHref,
	)
	return i, err
}

const deleteCourseGuarded = `-- name: DeleteCourseGuarded :one
UPDATE course SET
    status             = 'tobedeleted',
    date_last_modified = $1::timestamptz
WHERE sourced_id = $2::text
  AND EXISTS (
      SELECT 1 FROM auth_effective_access a
      WHERE a.subject = $3::text
        AND a.org_sourced_id = course.org_sourced_id
        AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
  )
RETURNING sourced_id, status, date_last_modified, metadata, title, course_code, grades, subjects, subject_codes, org_sourced_id, org_href, school_year_sourced_id, school_year_href
`

type DeleteCourseGuardedParams struct {
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	SourcedID        string             `json:"sourced_id"`
	Subject          string             `json:"subject"`
}

func (q *Queries) DeleteCourseGuarded(ctx context.Context, arg DeleteCourseGuardedParams) (Course, error) {
	row := q.db.QueryRow(ctx, deleteCourseGuarded, arg.DateLastModified, arg.SourcedID, arg.Subject)
	var i Course
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.CourseCode,
		&i.Grades,
		&i.Subjects,
		&i.SubjectCodes,
		&i.OrgSourcedID,
		&i.OrgHref,
		&i.SchoolYearSourcedID,
		&i.SchoolYearHref,
	)
	return i, err
}

const deleteEnrollmentGuarded = `-- name: DeleteEnrollmentGuarded :one
UPDATE enrollment SET
    status             = 'tobedeleted',
    date_last_modified = $1::timestamptz
WHERE sourced_id = $2::text
  AND EXISTS (
      SELECT 1 FROM auth_effective_access a
      WHERE a.subject = $3::text
        AND a.org_sourced_id = enrollment.school_sourced_id
        AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
  )
RETURNING sourced_id, status, date_last_modified, metadata, user_sourced_id, user_href, class_sourced_id, class_href, school_sourced_id, school_href, role, is_primary, begin_date, end_date
`

type DeleteEnrollmentGuardedParams struct {
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	SourcedID        string             `json:"sourced_id"`
	Subject          string             `json:"subject"`
}

func (q *Queries) DeleteEnrollmentGuarded(ctx context.Context, arg DeleteEnrollmentGuardedParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, deleteEnrollmentGuarded, arg.DateLastModified, arg.SourcedID, arg.Subject)
	var i Enrollment
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.UserSourcedID,
		&i.UserHref,
		&i.ClassSourcedID,
		&i.ClassHref,
		&i.SchoolSourcedID,
		&i.SchoolHref,
		&i.Role,
		&i.IsPrimary,
		&i.BeginDate,
		&i.EndDate,
	)
	return i, err
}

const deleteOrgGuarded = `-- name: DeleteOrgGuarded :one
UPDATE org SET
    status             = 'tobedeleted',
    date_last_modified = $1::timestamptz
WHERE sourced_id = $2::text
  AND EXISTS (
      SELECT 1 FROM auth_effective_access a
      WHERE a.subject = $3::text
        AND a.org_sourced_id = org.sourced_id
        AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
  )
RETURNING sourced_id, status, date_last_modified, metadata, name, type, identifier, parent_sourced_id, parent_href
`

type DeleteOrgGuardedParams struct {
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	SourcedID        string             `json:"sourced_id"`
	Subject          string             `json:"subject"`
}

// OneRoster deletion is a status flag, not a DELETE: consumers may remove such
// records but are not obliged to, and a hard delete here would cascade through
// every class and enrollment beneath the org.
func (q *Queries) DeleteOrgGuarded(ctx context.Context, arg DeleteOrgGuardedParams) (Org, error) {
	row := q.db.QueryRow(ctx, deleteOrgGuarded, arg.DateLastModified, arg.SourcedID, arg.Subject)
	var i Org
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Name,
		&i.Type,
		&i.Identifier,
		&i.ParentSourcedID,
		&i.ParentHref,
	)
	return i, err
}

const deleteUserGuarded = `-- name: DeleteUserGuarded :one
UPDATE oneroster_user SET
    status             = 'tobedeleted',
    date_last_modified = $1::timestamptz
WHERE sourced_id = $2::text
  AND EXISTS (
      SELECT 1
      FROM user_role ur
      JOIN auth_effective_access a ON a.org_sourced_id = ur.org_sourced_id
      WHERE ur.user_sourced_id = oneroster_user.sourced_id
        AND a.subject = $3::text
        AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
  )
RETURNING sourced_id, status, date_last_modified, metadata, user_master_identifier, username, enabled_user, given_name, family_name, middle_name, preferred_first_name, preferred_last_name, preferred_middle_name, pronouns, grades, identifier, email, sms, phone, password, primary_org_sourced_id, primary_org_href
`

type DeleteUserGuardedParams struct {
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	SourcedID        string             `json:"sourced_id"`
	Subject          string             `json:"subject"`
}

func (q *Queries) DeleteUserGuarded(ctx context.Context, arg DeleteUserGuardedParams) (OnerosterUser, error) {
	row := q.db.QueryRow(ctx, deleteUserGuarded, arg.DateLastModified, arg.SourcedID, arg.Subject)
	var i OnerosterUser
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.UserMasterIdentifier,
		&i.Username,
		&i.EnabledUser,
		&i.GivenName,
		&i.FamilyName,
		&i.MiddleName,
		&i.PreferredFirstName,
		&i.PreferredLastName,
		&i.PreferredMiddleName,
		&i.Pronouns,
		&i.Grades,
		&i.Identifier,
		&i.Email,
		&i.Sms,
		&i.Phone,
		&i.Password,
		&i.PrimaryOrgSourcedID,
		&i.PrimaryOrgHref,
	)
	return i, err
}

const enrollmentIsVisibleForCuration = `-- name: EnrollmentIsVisibleForCuration :one
SELECT EXISTS (
    SELECT 1 FROM enrollment e
    JOIN auth_effective_access a ON a.org_sourced_id = e.school_sourced_id
    WHERE e.sourced_id = $1::text
      AND a.subject = $2::text
      AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
) AS visible
`

type EnrollmentIsVisibleForCurationParams struct {
	SourcedID string `json:"sourced_id"`
	Subject   string `json:"subject"`
}

func (q *Queries) EnrollmentIsVisibleForCuration(ctx context.Context, arg EnrollmentIsVisibleForCurationParams) (bool, error) {
	row := q.db.QueryRow(ctx, enrollmentIsVisibleForCuration, arg.SourcedID, arg.Subject)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}

const orgIsVisibleForCuration = `-- name: OrgIsVisibleForCuration :one

SELECT EXISTS (
    SELECT 1 FROM org o
    JOIN auth_effective_access a ON a.org_sourced_id = o.sourced_id
    WHERE o.sourced_id = $1::text
      AND a.subject = $2::text
      AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
) AS visible
`

type OrgIsVisibleForCurationParams struct {
	SourcedID string `json:"sourced_id"`
	Subject   string `json:"subject"`
}

// ── Visibility probes ─────────────────────────────────────────────────────────
// After a guarded write affects no rows, these say whether the row was invisible
// (not_found) or whether the version moved (aborted). Without them the two are
// indistinguishable, and a curator whose edit lost a race would be told the
// record does not exist.
func (q *Queries) OrgIsVisibleForCuration(ctx context.Context, arg OrgIsVisibleForCurationParams) (bool, error) {
	row := q.db.QueryRow(ctx, orgIsVisibleForCuration, arg.SourcedID, arg.Subject)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}

const subjectHoldsGlobalCuratingGrant = `-- name: SubjectHoldsGlobalCuratingGrant :one
SELECT EXISTS (
    SELECT 1
    FROM auth_grant g
    JOIN auth_principal p ON p.id = g.principal_id
    JOIN auth_role r ON r.name = g.role_name
    WHERE p.subject = $1::text
      AND NOT p.disabled
      AND r.is_global
      AND g.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
      AND (g.expires_at IS NULL OR g.expires_at > NOW())
) AS allowed
`

// The bootstrap case: a global curator with no org to be scoped against, which
// is the only way the first org can be created.
func (q *Queries) SubjectHoldsGlobalCuratingGrant(ctx context.Context, subject string) (bool, error) {
	row := q.db.QueryRow(ctx, subjectHoldsGlobalCuratingGrant, subject)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const subjectIsGlobalRosterAdmin = `-- name: SubjectIsGlobalRosterAdmin :one

SELECT EXISTS (
    SELECT 1
    FROM auth_grant g
    JOIN auth_principal p ON p.id = g.principal_id
    JOIN auth_role r ON r.name = g.role_name
    WHERE p.subject = $1::text
      AND NOT p.disabled
      AND r.is_global
      AND g.role_name = 'roster_admin'
      AND (g.expires_at IS NULL OR g.expires_at > NOW())
) AS allowed
`

// ── AcademicSession (roster_admin only) ───────────────────────────────────────
//
// Sessions are the one rostering entity with no owning org. The OneRoster JSON
// Schema gives AcademicSessionDType no org reference at all: its parent and
// children chain only to other sessions, and schoolYear is a "YYYY" label, not
// a reference. Classes and courses point AT a session, so one session is
// reachable from every org whose classes use it — a union, not a scope.
//
// There is therefore nothing for an org-scoped predicate to check, and a
// brand-new session has no classes pointing at it in any case. These statements
// require a live, deployment-wide roster_admin grant instead. A district_admin
// cannot create a school year, because a school year is not a district's to own.
//
// Unlike the org-scoped writes, a caller without the grant gets zero rows and
// the handler reports permission_denied rather than not_found: sessions are
// readable by any principal holding any grant, so their existence is not a
// secret and there is nothing to protect by pretending otherwise.
func (q *Queries) SubjectIsGlobalRosterAdmin(ctx context.Context, subject string) (bool, error) {
	row := q.db.QueryRow(ctx, subjectIsGlobalRosterAdmin, subject)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const updateAcademicSessionGuarded = `-- name: UpdateAcademicSessionGuarded :one
UPDATE academic_session SET
    status             = $1::text,
    date_last_modified = $2::timestamptz,
    metadata           = $3::jsonb,
    title              = $4::text,
    start_date         = $5::date,
    end_date           = $6::date,
    type               = $7::text,
    school_year        = $8::text,
    parent_sourced_id  = $9::text,
    parent_href        = $10::text
WHERE sourced_id = $11::text
  AND date_last_modified = $12::timestamptz
  AND EXISTS (
      SELECT 1
      FROM auth_grant g
      JOIN auth_principal p ON p.id = g.principal_id
      JOIN auth_role r ON r.name = g.role_name
      WHERE p.subject = $13::text
        AND NOT p.disabled
        AND r.is_global
        AND g.role_name = 'roster_admin'
        AND (g.expires_at IS NULL OR g.expires_at > NOW())
  )
RETURNING sourced_id, status, date_last_modified, metadata, title, start_date, end_date, type, school_year, parent_sourced_id, parent_href
`

type UpdateAcademicSessionGuardedParams struct {
	Status                   string             `json:"status"`
	DateLastModified         pgtype.Timestamptz `json:"date_last_modified"`
	Metadata                 []byte             `json:"metadata"`
	Title                    string             `json:"title"`
	StartDate                pgtype.Date        `json:"start_date"`
	EndDate                  pgtype.Date        `json:"end_date"`
	Type                     string             `json:"type"`
	SchoolYear               string             `json:"school_year"`
	ParentSourcedID          pgtype.Text        `json:"parent_sourced_id"`
	ParentHref               pgtype.Text        `json:"parent_href"`
	SourcedID                string             `json:"sourced_id"`
	ExpectedDateLastModified pgtype.Timestamptz `json:"expected_date_last_modified"`
	Subject                  string             `json:"subject"`
}

func (q *Queries) UpdateAcademicSessionGuarded(ctx context.Context, arg UpdateAcademicSessionGuardedParams) (AcademicSession, error) {
	row := q.db.QueryRow(ctx, updateAcademicSessionGuarded,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.Type,
		arg.SchoolYear,
		arg.ParentSourcedID,
		arg.ParentHref,
		arg.SourcedID,
		arg.ExpectedDateLastModified,
		arg.Subject,
	)
	var i AcademicSession
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.SchoolYear,
		&i.ParentSourcedID,
		&i.ParentHref,
	)
	return i, err
}

const updateClassGuarded = `-- name: UpdateClassGuarded :one
UPDATE class SET
    status             = $1::text,
    date_last_modified = $2::timestamptz,
    metadata           = $3::jsonb,
    title              = $4::text,
    class_code         = $5::text,
    class_type         = $6::text,
    location           = $7::text,
    grades             = $8::text[],
    subjects           = $9::text[],
    subject_codes      = $10::text[],
    periods            = $11::text[],
    course_sourced_id  = $12::text,
    course_href        = $13::text,
    school_sourced_id  = $14::text,
    school_href        = $15::text
WHERE sourced_id = $16::text
  AND date_last_modified = $17::timestamptz
  AND EXISTS (
      SELECT 1 FROM auth_effective_access a
      WHERE a.subject = $18::text
        AND a.org_sourced_id = class.school_sourced_id
        AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
  )
RETURNING sourced_id, status, date_last_modified, metadata, title, class_code, class_type, location, grades, subjects, subject_codes, periods, course_sourced_id, course_href, school_sourced_id, school_href
`

type UpdateClassGuardedParams struct {
	Status                   string             `json:"status"`
	DateLastModified         pgtype.Timestamptz `json:"date_last_modified"`
	Metadata                 []byte             `json:"metadata"`
	Title                    string             `json:"title"`
	ClassCode                pgtype.Text        `json:"class_code"`
	ClassType                pgtype.Text        `json:"class_type"`
	Location                 pgtype.Text        `json:"location"`
	Grades                   []string           `json:"grades"`
	Subjects                 []string           `json:"subjects"`
	SubjectCodes             []string           `json:"subject_codes"`
	Periods                  []string           `json:"periods"`
	CourseSourcedID          string             `json:"course_sourced_id"`
	CourseHref               pgtype.Text        `json:"course_href"`
	SchoolSourcedID          string             `json:"school_sourced_id"`
	SchoolHref               pgtype.Text        `json:"school_href"`
	SourcedID                string             `json:"sourced_id"`
	ExpectedDateLastModified pgtype.Timestamptz `json:"expected_date_last_modified"`
	Subject                  string             `json:"subject"`
}

func (q *Queries) UpdateClassGuarded(ctx context.Context, arg UpdateClassGuardedParams) (Class, error) {
	row := q.db.QueryRow(ctx, updateClassGuarded,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.Title,
		arg.ClassCode,
		arg.ClassType,
		arg.Location,
		arg.Grades,
		arg.Subjects,
		arg.SubjectCodes,
		arg.Periods,
		arg.CourseSourcedID,
		arg.CourseHref,
		arg.SchoolSourcedID,
		arg.SchoolHref,
		arg.SourcedID,
		arg.ExpectedDateLastModified,
		arg.Subject,
	)
	var i Class
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.ClassCode,
		&i.ClassType,
		&i.Location,
		&i.Grades,
		&i.Subjects,
		&i.SubjectCodes,
		&i.Periods,
		&i.CourseSourcedID,
		&i.CourseHref,
		&i.SchoolSourcedID,
		&i.SchoolHref,
	)
	return i, err
}

const updateCourseGuarded = `-- name: UpdateCourseGuarded :one
UPDATE course SET
    status                 = $1::text,
    date_last_modified     = $2::timestamptz,
    metadata               = $3::jsonb,
    title                  = $4::text,
    course_code            = $5::text,
    grades                 = $6::text[],
    subjects               = $7::text[],
    subject_codes          = $8::text[],
    org_sourced_id         = $9::text,
    org_href               = $10::text,
    school_year_sourced_id = $11::text,
    school_year_href       = $12::text
WHERE sourced_id = $13::text
  AND date_last_modified = $14::timestamptz
  AND EXISTS (
      SELECT 1 FROM auth_effective_access a
      WHERE a.subject = $15::text
        AND a.org_sourced_id = course.org_sourced_id
        AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
  )
RETURNING sourced_id, status, date_last_modified, metadata, title, course_code, grades, subjects, subject_codes, org_sourced_id, org_href, school_year_sourced_id, school_year_href
`

type UpdateCourseGuardedParams struct {
	Status                   string             `json:"status"`
	DateLastModified         pgtype.Timestamptz `json:"date_last_modified"`
	Metadata                 []byte             `json:"metadata"`
	Title                    string             `json:"title"`
	CourseCode               string             `json:"course_code"`
	Grades                   []string           `json:"grades"`
	Subjects                 []string           `json:"subjects"`
	SubjectCodes             []string           `json:"subject_codes"`
	OrgSourcedID             pgtype.Text        `json:"org_sourced_id"`
	OrgHref                  pgtype.Text        `json:"org_href"`
	SchoolYearSourcedID      pgtype.Text        `json:"school_year_sourced_id"`
	SchoolYearHref           pgtype.Text        `json:"school_year_href"`
	SourcedID                string             `json:"sourced_id"`
	ExpectedDateLastModified pgtype.Timestamptz `json:"expected_date_last_modified"`
	Subject                  string             `json:"subject"`
}

func (q *Queries) UpdateCourseGuarded(ctx context.Context, arg UpdateCourseGuardedParams) (Course, error) {
	row := q.db.QueryRow(ctx, updateCourseGuarded,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.Title,
		arg.CourseCode,
		arg.Grades,
		arg.Subjects,
		arg.SubjectCodes,
		arg.OrgSourcedID,
		arg.OrgHref,
		arg.SchoolYearSourcedID,
		arg.SchoolYearHref,
		arg.SourcedID,
		arg.ExpectedDateLastModified,
		arg.Subject,
	)
	var i Course
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.CourseCode,
		&i.Grades,
		&i.Subjects,
		&i.SubjectCodes,
		&i.OrgSourcedID,
		&i.OrgHref,
		&i.SchoolYearSourcedID,
		&i.SchoolYearHref,
	)
	return i, err
}

const updateEnrollmentGuarded = `-- name: UpdateEnrollmentGuarded :one
UPDATE enrollment SET
    status             = $1::text,
    date_last_modified = $2::timestamptz,
    metadata           = $3::jsonb,
    user_sourced_id    = $4::text,
    user_href          = $5::text,
    class_sourced_id   = $6::text,
    class_href         = $7::text,
    school_sourced_id  = $8::text,
    school_href        = $9::text,
    role               = $10::text,
    is_primary         = $11::boolean,
    begin_date         = $12::date,
    end_date           = $13::date
WHERE sourced_id = $14::text
  AND date_last_modified = $15::timestamptz
  AND EXISTS (
      SELECT 1 FROM auth_effective_access a
      WHERE a.subject = $16::text
        AND a.org_sourced_id = enrollment.school_sourced_id
        AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
  )
RETURNING sourced_id, status, date_last_modified, metadata, user_sourced_id, user_href, class_sourced_id, class_href, school_sourced_id, school_href, role, is_primary, begin_date, end_date
`

type UpdateEnrollmentGuardedParams struct {
	Status                   string             `json:"status"`
	DateLastModified         pgtype.Timestamptz `json:"date_last_modified"`
	Metadata                 []byte             `json:"metadata"`
	UserSourcedID            string             `json:"user_sourced_id"`
	UserHref                 pgtype.Text        `json:"user_href"`
	ClassSourcedID           string             `json:"class_sourced_id"`
	ClassHref                pgtype.Text        `json:"class_href"`
	SchoolSourcedID          string             `json:"school_sourced_id"`
	SchoolHref               pgtype.Text        `json:"school_href"`
	Role                     string             `json:"role"`
	IsPrimary                pgtype.Bool        `json:"is_primary"`
	BeginDate                pgtype.Date        `json:"begin_date"`
	EndDate                  pgtype.Date        `json:"end_date"`
	SourcedID                string             `json:"sourced_id"`
	ExpectedDateLastModified pgtype.Timestamptz `json:"expected_date_last_modified"`
	Subject                  string             `json:"subject"`
}

func (q *Queries) UpdateEnrollmentGuarded(ctx context.Context, arg UpdateEnrollmentGuardedParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, updateEnrollmentGuarded,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.UserSourcedID,
		arg.UserHref,
		arg.ClassSourcedID,
		arg.ClassHref,
		arg.SchoolSourcedID,
		arg.SchoolHref,
		arg.Role,
		arg.IsPrimary,
		arg.BeginDate,
		arg.EndDate,
		arg.SourcedID,
		arg.ExpectedDateLastModified,
		arg.Subject,
	)
	var i Enrollment
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.UserSourcedID,
		&i.UserHref,
		&i.ClassSourcedID,
		&i.ClassHref,
		&i.SchoolSourcedID,
		&i.SchoolHref,
		&i.Role,
		&i.IsPrimary,
		&i.BeginDate,
		&i.EndDate,
	)
	return i, err
}

const updateOrgGuarded = `-- name: UpdateOrgGuarded :one
UPDATE org SET
    status             = $1::text,
    date_last_modified = $2::timestamptz,
    metadata           = $3::jsonb,
    name               = $4::text,
    type               = $5::text,
    identifier         = $6::text,
    parent_sourced_id  = $7::text,
    parent_href        = $8::text
WHERE sourced_id = $9::text
  AND date_last_modified = $10::timestamptz
  AND EXISTS (
      SELECT 1 FROM auth_effective_access a
      WHERE a.subject = $11::text
        AND a.org_sourced_id = org.sourced_id
        AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
  )
RETURNING sourced_id, status, date_last_modified, metadata, name, type, identifier, parent_sourced_id, parent_href
`

type UpdateOrgGuardedParams struct {
	Status                   string             `json:"status"`
	DateLastModified         pgtype.Timestamptz `json:"date_last_modified"`
	Metadata                 []byte             `json:"metadata"`
	Name                     string             `json:"name"`
	Type                     string             `json:"type"`
	Identifier               string             `json:"identifier"`
	ParentSourcedID          pgtype.Text        `json:"parent_sourced_id"`
	ParentHref               pgtype.Text        `json:"parent_href"`
	SourcedID                string             `json:"sourced_id"`
	ExpectedDateLastModified pgtype.Timestamptz `json:"expected_date_last_modified"`
	Subject                  string             `json:"subject"`
}

func (q *Queries) UpdateOrgGuarded(ctx context.Context, arg UpdateOrgGuardedParams) (Org, error) {
	row := q.db.QueryRow(ctx, updateOrgGuarded,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.Name,
		arg.Type,
		arg.Identifier,
		arg.ParentSourcedID,
		arg.ParentHref,
		arg.SourcedID,
		arg.ExpectedDateLastModified,
		arg.Subject,
	)
	var i Org
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Name,
		&i.Type,
		&i.Identifier,
		&i.ParentSourcedID,
		&i.ParentHref,
	)
	return i, err
}

const updateUserGuarded = `-- name: UpdateUserGuarded :one
UPDATE oneroster_user SET
    status                 = $1::text,
    date_last_modified     = $2::timestamptz,
    metadata               = $3::jsonb,
    user_master_identifier = $4::text,
    username               = $5::text,
    enabled_user           = $6::boolean,
    given_name             = $7::text,
    family_name            = $8::text,
    middle_name            = $9::text,
    preferred_first_name   = $10::text,
    preferred_last_name    = $11::text,
    preferred_middle_name  = $12::text,
    pronouns               = $13::text,
    grades                 = $14::text[],
    identifier             = $15::text,
    email                  = $16::text,
    sms                    = $17::text,
    phone                  = $18::text,
    primary_org_sourced_id = $19::text,
    primary_org_href       = $20::text
WHERE sourced_id = $21::text
  AND date_last_modified = $22::timestamptz
  AND EXISTS (
      SELECT 1
      FROM user_role ur
      JOIN auth_effective_access a ON a.org_sourced_id = ur.org_sourced_id
      WHERE ur.user_sourced_id = oneroster_user.sourced_id
        AND a.subject = $23::text
        AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
  )
RETURNING sourced_id, status, date_last_modified, metadata, user_master_identifier, username, enabled_user, given_name, family_name, middle_name, preferred_first_name, preferred_last_name, preferred_middle_name, pronouns, grades, identifier, email, sms, phone, password, primary_org_sourced_id, primary_org_href
`

type UpdateUserGuardedParams struct {
	Status                   string             `json:"status"`
	DateLastModified         pgtype.Timestamptz `json:"date_last_modified"`
	Metadata                 []byte             `json:"metadata"`
	UserMasterIdentifier     pgtype.Text        `json:"user_master_identifier"`
	Username                 pgtype.Text        `json:"username"`
	EnabledUser              bool               `json:"enabled_user"`
	GivenName                string             `json:"given_name"`
	FamilyName               string             `json:"family_name"`
	MiddleName               pgtype.Text        `json:"middle_name"`
	PreferredFirstName       pgtype.Text        `json:"preferred_first_name"`
	PreferredLastName        pgtype.Text        `json:"preferred_last_name"`
	PreferredMiddleName      pgtype.Text        `json:"preferred_middle_name"`
	Pronouns                 pgtype.Text        `json:"pronouns"`
	Grades                   []string           `json:"grades"`
	Identifier               pgtype.Text        `json:"identifier"`
	Email                    pgtype.Text        `json:"email"`
	Sms                      pgtype.Text        `json:"sms"`
	Phone                    pgtype.Text        `json:"phone"`
	PrimaryOrgSourcedID      pgtype.Text        `json:"primary_org_sourced_id"`
	PrimaryOrgHref           pgtype.Text        `json:"primary_org_href"`
	SourcedID                string             `json:"sourced_id"`
	ExpectedDateLastModified pgtype.Timestamptz `json:"expected_date_last_modified"`
	Subject                  string             `json:"subject"`
}

// Scoped through the user's roles, matching how reads scope them: a user is
// visible where they hold a role, and is writable in the same places.
func (q *Queries) UpdateUserGuarded(ctx context.Context, arg UpdateUserGuardedParams) (OnerosterUser, error) {
	row := q.db.QueryRow(ctx, updateUserGuarded,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.UserMasterIdentifier,
		arg.Username,
		arg.EnabledUser,
		arg.GivenName,
		arg.FamilyName,
		arg.MiddleName,
		arg.PreferredFirstName,
		arg.PreferredLastName,
		arg.PreferredMiddleName,
		arg.Pronouns,
		arg.Grades,
		arg.Identifier,
		arg.Email,
		arg.Sms,
		arg.Phone,
		arg.PrimaryOrgSourcedID,
		arg.PrimaryOrgHref,
		arg.SourcedID,
		arg.ExpectedDateLastModified,
		arg.Subject,
	)
	var i OnerosterUser
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.UserMasterIdentifier,
		&i.Username,
		&i.EnabledUser,
		&i.GivenName,
		&i.FamilyName,
		&i.MiddleName,
		&i.PreferredFirstName,
		&i.PreferredLastName,
		&i.PreferredMiddleName,
		&i.Pronouns,
		&i.Grades,
		&i.Identifier,
		&i.Email,
		&i.Sms,
		&i.Phone,
		&i.Password,
		&i.PrimaryOrgSourcedID,
		&i.PrimaryOrgHref,
	)
	return i, err
}

const userIsVisibleForCuration = `-- name: UserIsVisibleForCuration :one
SELECT EXISTS (
    SELECT 1 FROM oneroster_user u
    JOIN user_role ur ON ur.user_sourced_id = u.sourced_id
    JOIN auth_effective_access a ON a.org_sourced_id = ur.org_sourced_id
    WHERE u.sourced_id = $1::text
      AND a.subject = $2::text
      AND a.role_name IN ('roster_admin', 'district_admin', 'school_admin', 'data_provider')
) AS visible
`

type UserIsVisibleForCurationParams struct {
	SourcedID string `json:"sourced_id"`
	Subject   string `json:"subject"`
}

func (q *Queries) UserIsVisibleForCuration(ctx context.Context, arg UserIsVisibleForCurationParams) (bool, error) {
	row := q.db.QueryRow(ctx, userIsVisibleForCuration, arg.SourcedID, arg.Subject)
	var visible bool
	err := row.Scan(&visible)
	return visible, err
}
