// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AcademicSession struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	Title            string             `json:"title"`
	StartDate        pgtype.Date        `json:"start_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	Type             string             `json:"type"`
	SchoolYear       string             `json:"school_year"`
	ParentSourcedID  pgtype.Text        `json:"parent_sourced_id"`
	ParentHref       pgtype.Text        `json:"parent_href"`
}

type AuthApiToken struct {
	ID          pgtype.UUID        `json:"id"`
	PrincipalID pgtype.UUID        `json:"principal_id"`
	Name        string             `json:"name"`
	TokenHash   []byte             `json:"token_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
}

type AuthEffectiveAccess struct {
	PrincipalID  pgtype.UUID `json:"principal_id"`
	Subject      string      `json:"subject"`
	RoleName     string      `json:"role_name"`
	OrgSourcedID string      `json:"org_sourced_id"`
	IsGlobal     bool        `json:"is_global"`
}

type AuthGrant struct {
	ID           pgtype.UUID        `json:"id"`
	PrincipalID  pgtype.UUID        `json:"principal_id"`
	RoleName     string             `json:"role_name"`
	OrgSourcedID pgtype.Text        `json:"org_sourced_id"`
	GrantedBy    pgtype.UUID        `json:"granted_by"`
	GrantedAt    pgtype.Timestamptz `json:"granted_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type AuthPrincipal struct {
	ID                     pgtype.UUID        `json:"id"`
	Subject                string             `json:"subject"`
	Kind                   string             `json:"kind"`
	Email                  pgtype.Text        `json:"email"`
	DisplayName            pgtype.Text        `json:"display_name"`
	OnerosterUserSourcedID pgtype.Text        `json:"oneroster_user_sourced_id"`
	Disabled               bool               `json:"disabled"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	ModifiedAt             pgtype.Timestamptz `json:"modified_at"`
}

type AuthRole struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	IsGlobal    bool   `json:"is_global"`
}

type Class struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	Title            string             `json:"title"`
	ClassCode        pgtype.Text        `json:"class_code"`
	ClassType        pgtype.Text        `json:"class_type"`
	Location         pgtype.Text        `json:"location"`
	Grades           []string           `json:"grades"`
	Subjects         []string           `json:"subjects"`
	SubjectCodes     []string           `json:"subject_codes"`
	Periods          []string           `json:"periods"`
	CourseSourcedID  string             `json:"course_sourced_id"`
	CourseHref       pgtype.Text        `json:"course_href"`
	SchoolSourcedID  string             `json:"school_sourced_id"`
	SchoolHref       pgtype.Text        `json:"school_href"`
}

type ClassResource struct {
	ClassSourcedID    string      `json:"class_sourced_id"`
	ResourceSourcedID string      `json:"resource_sourced_id"`
	ResourceHref      pgtype.Text `json:"resource_href"`
	Ordinal           int32       `json:"ordinal"`
}

type ClassTerm struct {
	ClassSourcedID           string      `json:"class_sourced_id"`
	AcademicSessionSourcedID string      `json:"academic_session_sourced_id"`
	AcademicSessionHref      pgtype.Text `json:"academic_session_href"`
	Ordinal                  int32       `json:"ordinal"`
}

type Course struct {
	SourcedID           string             `json:"sourced_id"`
	Status              string             `json:"status"`
	DateLastModified    pgtype.Timestamptz `json:"date_last_modified"`
	Metadata            []byte             `json:"metadata"`
	Title               string             `json:"title"`
	CourseCode          string             `json:"course_code"`
	Grades              []string           `json:"grades"`
	Subjects            []string           `json:"subjects"`
	SubjectCodes        []string           `json:"subject_codes"`
	OrgSourcedID        pgtype.Text        `json:"org_sourced_id"`
	OrgHref             pgtype.Text        `json:"org_href"`
	SchoolYearSourcedID pgtype.Text        `json:"school_year_sourced_id"`
	SchoolYearHref      pgtype.Text        `json:"school_year_href"`
}

type CourseResource struct {
	CourseSourcedID   string      `json:"course_sourced_id"`
	ResourceSourcedID string      `json:"resource_sourced_id"`
	ResourceHref      pgtype.Text `json:"resource_href"`
	Ordinal           int32       `json:"ordinal"`
}

type Credential struct {
	ID        int64       `json:"id"`
	ProfileID string      `json:"profile_id"`
	Type      string      `json:"type"`
	Username  string      `json:"username"`
	Password  pgtype.Text `json:"password"`
	Ordinal   int32       `json:"ordinal"`
}

type Demographic struct {
	SourcedID                            string             `json:"sourced_id"`
	Status                               string             `json:"status"`
	DateLastModified                     pgtype.Timestamptz `json:"date_last_modified"`
	Metadata                             []byte             `json:"metadata"`
	BirthDate                            pgtype.Date        `json:"birth_date"`
	Sex                                  pgtype.Text        `json:"sex"`
	AmericanIndianOrAlaskaNative         pgtype.Bool        `json:"american_indian_or_alaska_native"`
	Asian                                pgtype.Bool        `json:"asian"`
	BlackOrAfricanAmerican               pgtype.Bool        `json:"black_or_african_american"`
	NativeHawaiianOrOtherPacificIslander pgtype.Bool        `json:"native_hawaiian_or_other_pacific_islander"`
	White                                pgtype.Bool        `json:"white"`
	DemographicRaceTwoOrMoreRaces        pgtype.Bool        `json:"demographic_race_two_or_more_races"`
	HispanicOrLatinoEthnicity            pgtype.Bool        `json:"hispanic_or_latino_ethnicity"`
	CountryOfBirthCode                   pgtype.Text        `json:"country_of_birth_code"`
	StateOfBirthAbbreviation             pgtype.Text        `json:"state_of_birth_abbreviation"`
	CityOfBirth                          pgtype.Text        `json:"city_of_birth"`
	PublicSchoolResidenceStatus          pgtype.Text        `json:"public_school_residence_status"`
}

type Enrollment struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	UserSourcedID    string             `json:"user_sourced_id"`
	UserHref         pgtype.Text        `json:"user_href"`
	ClassSourcedID   string             `json:"class_sourced_id"`
	ClassHref        pgtype.Text        `json:"class_href"`
	SchoolSourcedID  string             `json:"school_sourced_id"`
	SchoolHref       pgtype.Text        `json:"school_href"`
	Role             string             `json:"role"`
	IsPrimary        pgtype.Bool        `json:"is_primary"`
	BeginDate        pgtype.Date        `json:"begin_date"`
	EndDate          pgtype.Date        `json:"end_date"`
}

type OnerosterUser struct {
	SourcedID            string             `json:"sourced_id"`
	Status               string             `json:"status"`
	DateLastModified     pgtype.Timestamptz `json:"date_last_modified"`
	Metadata             []byte             `json:"metadata"`
	UserMasterIdentifier pgtype.Text        `json:"user_master_identifier"`
	Username             pgtype.Text        `json:"username"`
	EnabledUser          bool               `json:"enabled_user"`
	GivenName            string             `json:"given_name"`
	FamilyName           string             `json:"family_name"`
	MiddleName           pgtype.Text        `json:"middle_name"`
	PreferredFirstName   pgtype.Text        `json:"preferred_first_name"`
	PreferredLastName    pgtype.Text        `json:"preferred_last_name"`
	PreferredMiddleName  pgtype.Text        `json:"preferred_middle_name"`
	Pronouns             pgtype.Text        `json:"pronouns"`
	Grades               []string           `json:"grades"`
	Identifier           pgtype.Text        `json:"identifier"`
	Email                pgtype.Text        `json:"email"`
	Sms                  pgtype.Text        `json:"sms"`
	Phone                pgtype.Text        `json:"phone"`
	Password             pgtype.Text        `json:"password"`
	PrimaryOrgSourcedID  pgtype.Text        `json:"primary_org_sourced_id"`
	PrimaryOrgHref       pgtype.Text        `json:"primary_org_href"`
}

type Org struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	Name             string             `json:"name"`
	Type             string             `json:"type"`
	Identifier       string             `json:"identifier"`
	ParentSourcedID  pgtype.Text        `json:"parent_sourced_id"`
	ParentHref       pgtype.Text        `json:"parent_href"`
}

type OrgClosure struct {
	AncestorSourcedID   string `json:"ancestor_sourced_id"`
	DescendantSourcedID string `json:"descendant_sourced_id"`
	Depth               int32  `json:"depth"`
}

type Resource struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	Title            string             `json:"title"`
	Roles            []string           `json:"roles"`
	Importance       pgtype.Text        `json:"importance"`
	VendorResourceID pgtype.Text        `json:"vendor_resource_id"`
	VendorID         pgtype.Text        `json:"vendor_id"`
	ApplicationID    pgtype.Text        `json:"application_id"`
}

type UserAgent struct {
	UserSourcedID  string      `json:"user_sourced_id"`
	AgentSourcedID string      `json:"agent_sourced_id"`
	AgentHref      pgtype.Text `json:"agent_href"`
	Ordinal        int32       `json:"ordinal"`
}

type UserIdentifier struct {
	ID            int64  `json:"id"`
	UserSourcedID string `json:"user_sourced_id"`
	Type          string `json:"type"`
	Identifier    string `json:"identifier"`
	Ordinal       int32  `json:"ordinal"`
}

type UserProfile struct {
	ProfileID     string      `json:"profile_id"`
	UserSourcedID string      `json:"user_sourced_id"`
	ProfileType   string      `json:"profile_type"`
	VendorID      string      `json:"vendor_id"`
	ApplicationID pgtype.Text `json:"application_id"`
	Description   pgtype.Text `json:"description"`
	Ordinal       int32       `json:"ordinal"`
}

type UserResource struct {
	UserSourcedID     string      `json:"user_sourced_id"`
	ResourceSourcedID string      `json:"resource_sourced_id"`
	ResourceHref      pgtype.Text `json:"resource_href"`
	Ordinal           int32       `json:"ordinal"`
}

type UserRole struct {
	ID            int64       `json:"id"`
	UserSourcedID string      `json:"user_sourced_id"`
	UserHref      pgtype.Text `json:"user_href"`
	RoleType      string      `json:"role_type"`
	Role          string      `json:"role"`
	OrgSourcedID  string      `json:"org_sourced_id"`
	OrgHref       pgtype.Text `json:"org_href"`
	BeginDate     pgtype.Date `json:"begin_date"`
	EndDate       pgtype.Date `json:"end_date"`
	UserProfile   pgtype.Text `json:"user_profile"`
	Ordinal       int32       `json:"ordinal"`
}
