// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: oneroster.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteClassTerms = `-- name: DeleteClassTerms :exec
DELETE FROM class_term WHERE class_sourced_id = $1
`

func (q *Queries) DeleteClassTerms(ctx context.Context, classSourcedID string) error {
	_, err := q.db.Exec(ctx, deleteClassTerms, classSourcedID)
	return err
}

const deleteUserAgents = `-- name: DeleteUserAgents :exec
DELETE FROM user_agent WHERE user_sourced_id = $1
`

func (q *Queries) DeleteUserAgents(ctx context.Context, userSourcedID string) error {
	_, err := q.db.Exec(ctx, deleteUserAgents, userSourcedID)
	return err
}

const deleteUserIdentifiers = `-- name: DeleteUserIdentifiers :exec
DELETE FROM user_identifier WHERE user_sourced_id = $1
`

func (q *Queries) DeleteUserIdentifiers(ctx context.Context, userSourcedID string) error {
	_, err := q.db.Exec(ctx, deleteUserIdentifiers, userSourcedID)
	return err
}

const deleteUserProfiles = `-- name: DeleteUserProfiles :exec
DELETE FROM user_profile WHERE user_sourced_id = $1
`

func (q *Queries) DeleteUserProfiles(ctx context.Context, userSourcedID string) error {
	_, err := q.db.Exec(ctx, deleteUserProfiles, userSourcedID)
	return err
}

const deleteUserRoles = `-- name: DeleteUserRoles :exec
DELETE FROM user_role WHERE user_sourced_id = $1
`

func (q *Queries) DeleteUserRoles(ctx context.Context, userSourcedID string) error {
	_, err := q.db.Exec(ctx, deleteUserRoles, userSourcedID)
	return err
}

const insertCredential = `-- name: InsertCredential :one
INSERT INTO credential (profile_id, type, username, password, ordinal)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, profile_id, type, username, password, ordinal
`

type InsertCredentialParams struct {
	ProfileID string      `json:"profile_id"`
	Type      string      `json:"type"`
	Username  string      `json:"username"`
	Password  pgtype.Text `json:"password"`
	Ordinal   int32       `json:"ordinal"`
}

func (q *Queries) InsertCredential(ctx context.Context, arg InsertCredentialParams) (Credential, error) {
	row := q.db.QueryRow(ctx, insertCredential,
		arg.ProfileID,
		arg.Type,
		arg.Username,
		arg.Password,
		arg.Ordinal,
	)
	var i Credential
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.Type,
		&i.Username,
		&i.Password,
		&i.Ordinal,
	)
	return i, err
}

const insertUserIdentifier = `-- name: InsertUserIdentifier :one
INSERT INTO user_identifier (user_sourced_id, type, identifier, ordinal)
VALUES ($1, $2, $3, $4)
RETURNING id, user_sourced_id, type, identifier, ordinal
`

type InsertUserIdentifierParams struct {
	UserSourcedID string `json:"user_sourced_id"`
	Type          string `json:"type"`
	Identifier    string `json:"identifier"`
	Ordinal       int32  `json:"ordinal"`
}

func (q *Queries) InsertUserIdentifier(ctx context.Context, arg InsertUserIdentifierParams) (UserIdentifier, error) {
	row := q.db.QueryRow(ctx, insertUserIdentifier,
		arg.UserSourcedID,
		arg.Type,
		arg.Identifier,
		arg.Ordinal,
	)
	var i UserIdentifier
	err := row.Scan(
		&i.ID,
		&i.UserSourcedID,
		&i.Type,
		&i.Identifier,
		&i.Ordinal,
	)
	return i, err
}

const insertUserRole = `-- name: InsertUserRole :one
INSERT INTO user_role (
    user_sourced_id, user_href, role_type, role, org_sourced_id, org_href,
    begin_date, end_date, user_profile, ordinal
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_sourced_id, user_href, role_type, role, org_sourced_id, org_href, begin_date, end_date, user_profile, ordinal
`

type InsertUserRoleParams struct {
	UserSourcedID string      `json:"user_sourced_id"`
	UserHref      pgtype.Text `json:"user_href"`
	RoleType      string      `json:"role_type"`
	Role          string      `json:"role"`
	OrgSourcedID  string      `json:"org_sourced_id"`
	OrgHref       pgtype.Text `json:"org_href"`
	BeginDate     pgtype.Date `json:"begin_date"`
	EndDate       pgtype.Date `json:"end_date"`
	UserProfile   pgtype.Text `json:"user_profile"`
	Ordinal       int32       `json:"ordinal"`
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, insertUserRole,
		arg.UserSourcedID,
		arg.UserHref,
		arg.RoleType,
		arg.Role,
		arg.OrgSourcedID,
		arg.OrgHref,
		arg.BeginDate,
		arg.EndDate,
		arg.UserProfile,
		arg.Ordinal,
	)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.UserSourcedID,
		&i.UserHref,
		&i.RoleType,
		&i.Role,
		&i.OrgSourcedID,
		&i.OrgHref,
		&i.BeginDate,
		&i.EndDate,
		&i.UserProfile,
		&i.Ordinal,
	)
	return i, err
}

const replaceClassTerms = `-- name: ReplaceClassTerms :exec
INSERT INTO class_term (class_sourced_id, academic_session_sourced_id, academic_session_href, ordinal)
SELECT $1, term.sourced_id, ($3::text[])[term.ord], (term.ord - 1)::int
FROM unnest($2::text[]) WITH ORDINALITY AS term(sourced_id, ord)
ON CONFLICT (class_sourced_id, academic_session_sourced_id) DO UPDATE SET
    academic_session_href = EXCLUDED.academic_session_href,
    ordinal               = EXCLUDED.ordinal
`

type ReplaceClassTermsParams struct {
	ClassSourcedID string   `json:"class_sourced_id"`
	Column2        []string `json:"column_2"`
	Column3        []string `json:"column_3"`
}

// Terms arrive as an ordered list, inserted in one round trip. WITH ORDINALITY
// supplies the position, so the caller passes parallel arrays and no ordinal
// array; hrefs are subscripted by that position. Single-argument unnest because
// sqlc's catalog does not carry the multi-argument form.
func (q *Queries) ReplaceClassTerms(ctx context.Context, arg ReplaceClassTermsParams) error {
	_, err := q.db.Exec(ctx, replaceClassTerms, arg.ClassSourcedID, arg.Column2, arg.Column3)
	return err
}

const replaceUserAgents = `-- name: ReplaceUserAgents :exec
INSERT INTO user_agent (user_sourced_id, agent_sourced_id, agent_href, ordinal)
SELECT $1, agent.sourced_id, ($3::text[])[agent.ord], (agent.ord - 1)::int
FROM unnest($2::text[]) WITH ORDINALITY AS agent(sourced_id, ord)
ON CONFLICT (user_sourced_id, agent_sourced_id) DO UPDATE SET
    agent_href = EXCLUDED.agent_href,
    ordinal    = EXCLUDED.ordinal
`

type ReplaceUserAgentsParams struct {
	UserSourcedID string   `json:"user_sourced_id"`
	Column2       []string `json:"column_2"`
	Column3       []string `json:"column_3"`
}

func (q *Queries) ReplaceUserAgents(ctx context.Context, arg ReplaceUserAgentsParams) error {
	_, err := q.db.Exec(ctx, replaceUserAgents, arg.UserSourcedID, arg.Column2, arg.Column3)
	return err
}

const upsertAcademicSession = `-- name: UpsertAcademicSession :one
INSERT INTO academic_session (
    sourced_id, status, date_last_modified, metadata, title, start_date,
    end_date, type, school_year, parent_sourced_id, parent_href
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (sourced_id) DO UPDATE SET
    status             = EXCLUDED.status,
    date_last_modified = EXCLUDED.date_last_modified,
    metadata           = EXCLUDED.metadata,
    title              = EXCLUDED.title,
    start_date         = EXCLUDED.start_date,
    end_date           = EXCLUDED.end_date,
    type               = EXCLUDED.type,
    school_year        = EXCLUDED.school_year,
    parent_sourced_id  = EXCLUDED.parent_sourced_id,
    parent_href        = EXCLUDED.parent_href
RETURNING sourced_id, status, date_last_modified, metadata, title, start_date, end_date, type, school_year, parent_sourced_id, parent_href
`

type UpsertAcademicSessionParams struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	Title            string             `json:"title"`
	StartDate        pgtype.Date        `json:"start_date"`
	EndDate          pgtype.Date        `json:"end_date"`
	Type             string             `json:"type"`
	SchoolYear       string             `json:"school_year"`
	ParentSourcedID  pgtype.Text        `json:"parent_sourced_id"`
	ParentHref       pgtype.Text        `json:"parent_href"`
}

func (q *Queries) UpsertAcademicSession(ctx context.Context, arg UpsertAcademicSessionParams) (AcademicSession, error) {
	row := q.db.QueryRow(ctx, upsertAcademicSession,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.Title,
		arg.StartDate,
		arg.EndDate,
		arg.Type,
		arg.SchoolYear,
		arg.ParentSourcedID,
		arg.ParentHref,
	)
	var i AcademicSession
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.SchoolYear,
		&i.ParentSourcedID,
		&i.ParentHref,
	)
	return i, err
}

const upsertClass = `-- name: UpsertClass :one
INSERT INTO class (
    sourced_id, status, date_last_modified, metadata, title, class_code,
    class_type, location, grades, subjects, subject_codes, periods,
    course_sourced_id, course_href, school_sourced_id, school_href
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
ON CONFLICT (sourced_id) DO UPDATE SET
    status             = EXCLUDED.status,
    date_last_modified = EXCLUDED.date_last_modified,
    metadata           = EXCLUDED.metadata,
    title              = EXCLUDED.title,
    class_code         = EXCLUDED.class_code,
    class_type         = EXCLUDED.class_type,
    location           = EXCLUDED.location,
    grades             = EXCLUDED.grades,
    subjects           = EXCLUDED.subjects,
    subject_codes      = EXCLUDED.subject_codes,
    periods            = EXCLUDED.periods,
    course_sourced_id  = EXCLUDED.course_sourced_id,
    course_href        = EXCLUDED.course_href,
    school_sourced_id  = EXCLUDED.school_sourced_id,
    school_href        = EXCLUDED.school_href
RETURNING sourced_id, status, date_last_modified, metadata, title, class_code, class_type, location, grades, subjects, subject_codes, periods, course_sourced_id, course_href, school_sourced_id, school_href
`

type UpsertClassParams struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	Title            string             `json:"title"`
	ClassCode        pgtype.Text        `json:"class_code"`
	ClassType        pgtype.Text        `json:"class_type"`
	Location         pgtype.Text        `json:"location"`
	Grades           []string           `json:"grades"`
	Subjects         []string           `json:"subjects"`
	SubjectCodes     []string           `json:"subject_codes"`
	Periods          []string           `json:"periods"`
	CourseSourcedID  string             `json:"course_sourced_id"`
	CourseHref       pgtype.Text        `json:"course_href"`
	SchoolSourcedID  string             `json:"school_sourced_id"`
	SchoolHref       pgtype.Text        `json:"school_href"`
}

func (q *Queries) UpsertClass(ctx context.Context, arg UpsertClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, upsertClass,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.Title,
		arg.ClassCode,
		arg.ClassType,
		arg.Location,
		arg.Grades,
		arg.Subjects,
		arg.SubjectCodes,
		arg.Periods,
		arg.CourseSourcedID,
		arg.CourseHref,
		arg.SchoolSourcedID,
		arg.SchoolHref,
	)
	var i Class
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.ClassCode,
		&i.ClassType,
		&i.Location,
		&i.Grades,
		&i.Subjects,
		&i.SubjectCodes,
		&i.Periods,
		&i.CourseSourcedID,
		&i.CourseHref,
		&i.SchoolSourcedID,
		&i.SchoolHref,
	)
	return i, err
}

const upsertCourse = `-- name: UpsertCourse :one
INSERT INTO course (
    sourced_id, status, date_last_modified, metadata, title, course_code,
    grades, subjects, subject_codes, org_sourced_id, org_href,
    school_year_sourced_id, school_year_href
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
ON CONFLICT (sourced_id) DO UPDATE SET
    status                 = EXCLUDED.status,
    date_last_modified     = EXCLUDED.date_last_modified,
    metadata               = EXCLUDED.metadata,
    title                  = EXCLUDED.title,
    course_code            = EXCLUDED.course_code,
    grades                 = EXCLUDED.grades,
    subjects               = EXCLUDED.subjects,
    subject_codes          = EXCLUDED.subject_codes,
    org_sourced_id         = EXCLUDED.org_sourced_id,
    org_href               = EXCLUDED.org_href,
    school_year_sourced_id = EXCLUDED.school_year_sourced_id,
    school_year_href       = EXCLUDED.school_year_href
RETURNING sourced_id, status, date_last_modified, metadata, title, course_code, grades, subjects, subject_codes, org_sourced_id, org_href, school_year_sourced_id, school_year_href
`

type UpsertCourseParams struct {
	SourcedID           string             `json:"sourced_id"`
	Status              string             `json:"status"`
	DateLastModified    pgtype.Timestamptz `json:"date_last_modified"`
	Metadata            []byte             `json:"metadata"`
	Title               string             `json:"title"`
	CourseCode          string             `json:"course_code"`
	Grades              []string           `json:"grades"`
	Subjects            []string           `json:"subjects"`
	SubjectCodes        []string           `json:"subject_codes"`
	OrgSourcedID        pgtype.Text        `json:"org_sourced_id"`
	OrgHref             pgtype.Text        `json:"org_href"`
	SchoolYearSourcedID pgtype.Text        `json:"school_year_sourced_id"`
	SchoolYearHref      pgtype.Text        `json:"school_year_href"`
}

func (q *Queries) UpsertCourse(ctx context.Context, arg UpsertCourseParams) (Course, error) {
	row := q.db.QueryRow(ctx, upsertCourse,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.Title,
		arg.CourseCode,
		arg.Grades,
		arg.Subjects,
		arg.SubjectCodes,
		arg.OrgSourcedID,
		arg.OrgHref,
		arg.SchoolYearSourcedID,
		arg.SchoolYearHref,
	)
	var i Course
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.CourseCode,
		&i.Grades,
		&i.Subjects,
		&i.SubjectCodes,
		&i.OrgSourcedID,
		&i.OrgHref,
		&i.SchoolYearSourcedID,
		&i.SchoolYearHref,
	)
	return i, err
}

const upsertDemographics = `-- name: UpsertDemographics :one
INSERT INTO demographics (
    sourced_id, status, date_last_modified, metadata, birth_date, sex,
    american_indian_or_alaska_native, asian, black_or_african_american,
    native_hawaiian_or_other_pacific_islander, white,
    demographic_race_two_or_more_races, hispanic_or_latino_ethnicity,
    country_of_birth_code, state_of_birth_abbreviation, city_of_birth,
    public_school_residence_status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
ON CONFLICT (sourced_id) DO UPDATE SET
    status                                    = EXCLUDED.status,
    date_last_modified                        = EXCLUDED.date_last_modified,
    metadata                                  = EXCLUDED.metadata,
    birth_date                                = EXCLUDED.birth_date,
    sex                                       = EXCLUDED.sex,
    american_indian_or_alaska_native          = EXCLUDED.american_indian_or_alaska_native,
    asian                                     = EXCLUDED.asian,
    black_or_african_american                 = EXCLUDED.black_or_african_american,
    native_hawaiian_or_other_pacific_islander = EXCLUDED.native_hawaiian_or_other_pacific_islander,
    white                                     = EXCLUDED.white,
    demographic_race_two_or_more_races        = EXCLUDED.demographic_race_two_or_more_races,
    hispanic_or_latino_ethnicity              = EXCLUDED.hispanic_or_latino_ethnicity,
    country_of_birth_code                     = EXCLUDED.country_of_birth_code,
    state_of_birth_abbreviation               = EXCLUDED.state_of_birth_abbreviation,
    city_of_birth                             = EXCLUDED.city_of_birth,
    public_school_residence_status            = EXCLUDED.public_school_residence_status
RETURNING sourced_id, status, date_last_modified, metadata, birth_date, sex, american_indian_or_alaska_native, asian, black_or_african_american, native_hawaiian_or_other_pacific_islander, white, demographic_race_two_or_more_races, hispanic_or_latino_ethnicity, country_of_birth_code, state_of_birth_abbreviation, city_of_birth, public_school_residence_status
`

type UpsertDemographicsParams struct {
	SourcedID                            string             `json:"sourced_id"`
	Status                               string             `json:"status"`
	DateLastModified                     pgtype.Timestamptz `json:"date_last_modified"`
	Metadata                             []byte             `json:"metadata"`
	BirthDate                            pgtype.Date        `json:"birth_date"`
	Sex                                  pgtype.Text        `json:"sex"`
	AmericanIndianOrAlaskaNative         pgtype.Bool        `json:"american_indian_or_alaska_native"`
	Asian                                pgtype.Bool        `json:"asian"`
	BlackOrAfricanAmerican               pgtype.Bool        `json:"black_or_african_american"`
	NativeHawaiianOrOtherPacificIslander pgtype.Bool        `json:"native_hawaiian_or_other_pacific_islander"`
	White                                pgtype.Bool        `json:"white"`
	DemographicRaceTwoOrMoreRaces        pgtype.Bool        `json:"demographic_race_two_or_more_races"`
	HispanicOrLatinoEthnicity            pgtype.Bool        `json:"hispanic_or_latino_ethnicity"`
	CountryOfBirthCode                   pgtype.Text        `json:"country_of_birth_code"`
	StateOfBirthAbbreviation             pgtype.Text        `json:"state_of_birth_abbreviation"`
	CityOfBirth                          pgtype.Text        `json:"city_of_birth"`
	PublicSchoolResidenceStatus          pgtype.Text        `json:"public_school_residence_status"`
}

func (q *Queries) UpsertDemographics(ctx context.Context, arg UpsertDemographicsParams) (Demographic, error) {
	row := q.db.QueryRow(ctx, upsertDemographics,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.BirthDate,
		arg.Sex,
		arg.AmericanIndianOrAlaskaNative,
		arg.Asian,
		arg.BlackOrAfricanAmerican,
		arg.NativeHawaiianOrOtherPacificIslander,
		arg.White,
		arg.DemographicRaceTwoOrMoreRaces,
		arg.HispanicOrLatinoEthnicity,
		arg.CountryOfBirthCode,
		arg.StateOfBirthAbbreviation,
		arg.CityOfBirth,
		arg.PublicSchoolResidenceStatus,
	)
	var i Demographic
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.BirthDate,
		&i.Sex,
		&i.AmericanIndianOrAlaskaNative,
		&i.Asian,
		&i.BlackOrAfricanAmerican,
		&i.NativeHawaiianOrOtherPacificIslander,
		&i.White,
		&i.DemographicRaceTwoOrMoreRaces,
		&i.HispanicOrLatinoEthnicity,
		&i.CountryOfBirthCode,
		&i.StateOfBirthAbbreviation,
		&i.CityOfBirth,
		&i.PublicSchoolResidenceStatus,
	)
	return i, err
}

const upsertEnrollment = `-- name: UpsertEnrollment :one
INSERT INTO enrollment (
    sourced_id, status, date_last_modified, metadata, user_sourced_id,
    user_href, class_sourced_id, class_href, school_sourced_id, school_href,
    role, is_primary, begin_date, end_date
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (sourced_id) DO UPDATE SET
    status             = EXCLUDED.status,
    date_last_modified = EXCLUDED.date_last_modified,
    metadata           = EXCLUDED.metadata,
    user_sourced_id    = EXCLUDED.user_sourced_id,
    user_href          = EXCLUDED.user_href,
    class_sourced_id   = EXCLUDED.class_sourced_id,
    class_href         = EXCLUDED.class_href,
    school_sourced_id  = EXCLUDED.school_sourced_id,
    school_href        = EXCLUDED.school_href,
    role               = EXCLUDED.role,
    is_primary         = EXCLUDED.is_primary,
    begin_date         = EXCLUDED.begin_date,
    end_date           = EXCLUDED.end_date
RETURNING sourced_id, status, date_last_modified, metadata, user_sourced_id, user_href, class_sourced_id, class_href, school_sourced_id, school_href, role, is_primary, begin_date, end_date
`

type UpsertEnrollmentParams struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	UserSourcedID    string             `json:"user_sourced_id"`
	UserHref         pgtype.Text        `json:"user_href"`
	ClassSourcedID   string             `json:"class_sourced_id"`
	ClassHref        pgtype.Text        `json:"class_href"`
	SchoolSourcedID  string             `json:"school_sourced_id"`
	SchoolHref       pgtype.Text        `json:"school_href"`
	Role             string             `json:"role"`
	IsPrimary        pgtype.Bool        `json:"is_primary"`
	BeginDate        pgtype.Date        `json:"begin_date"`
	EndDate          pgtype.Date        `json:"end_date"`
}

func (q *Queries) UpsertEnrollment(ctx context.Context, arg UpsertEnrollmentParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, upsertEnrollment,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.UserSourcedID,
		arg.UserHref,
		arg.ClassSourcedID,
		arg.ClassHref,
		arg.SchoolSourcedID,
		arg.SchoolHref,
		arg.Role,
		arg.IsPrimary,
		arg.BeginDate,
		arg.EndDate,
	)
	var i Enrollment
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.UserSourcedID,
		&i.UserHref,
		&i.ClassSourcedID,
		&i.ClassHref,
		&i.SchoolSourcedID,
		&i.SchoolHref,
		&i.Role,
		&i.IsPrimary,
		&i.BeginDate,
		&i.EndDate,
	)
	return i, err
}

const upsertOrg = `-- name: UpsertOrg :one


INSERT INTO org (
    sourced_id, status, date_last_modified, metadata, name, type, identifier,
    parent_sourced_id, parent_href
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (sourced_id) DO UPDATE SET
    status             = EXCLUDED.status,
    date_last_modified = EXCLUDED.date_last_modified,
    metadata           = EXCLUDED.metadata,
    name               = EXCLUDED.name,
    type               = EXCLUDED.type,
    identifier         = EXCLUDED.identifier,
    parent_sourced_id  = EXCLUDED.parent_sourced_id,
    parent_href        = EXCLUDED.parent_href
RETURNING sourced_id, status, date_last_modified, metadata, name, type, identifier, parent_sourced_id, parent_href
`

type UpsertOrgParams struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	Name             string             `json:"name"`
	Type             string             `json:"type"`
	Identifier       string             `json:"identifier"`
	ParentSourcedID  pgtype.Text        `json:"parent_sourced_id"`
	ParentHref       pgtype.Text        `json:"parent_href"`
}

// OneRoster rostering queries.
//
// Upserts rather than inserts throughout: a roster arrives as a full snapshot
// from the source system, so re-importing must converge rather than conflict.
// ── Org ───────────────────────────────────────────────────────────────────────
func (q *Queries) UpsertOrg(ctx context.Context, arg UpsertOrgParams) (Org, error) {
	row := q.db.QueryRow(ctx, upsertOrg,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.Name,
		arg.Type,
		arg.Identifier,
		arg.ParentSourcedID,
		arg.ParentHref,
	)
	var i Org
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Name,
		&i.Type,
		&i.Identifier,
		&i.ParentSourcedID,
		&i.ParentHref,
	)
	return i, err
}

const upsertResource = `-- name: UpsertResource :one
INSERT INTO resource (
    sourced_id, status, date_last_modified, metadata, title, roles,
    importance, vendor_resource_id, vendor_id, application_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (sourced_id) DO UPDATE SET
    status             = EXCLUDED.status,
    date_last_modified = EXCLUDED.date_last_modified,
    metadata           = EXCLUDED.metadata,
    title              = EXCLUDED.title,
    roles              = EXCLUDED.roles,
    importance         = EXCLUDED.importance,
    vendor_resource_id = EXCLUDED.vendor_resource_id,
    vendor_id          = EXCLUDED.vendor_id,
    application_id     = EXCLUDED.application_id
RETURNING sourced_id, status, date_last_modified, metadata, title, roles, importance, vendor_resource_id, vendor_id, application_id
`

type UpsertResourceParams struct {
	SourcedID        string             `json:"sourced_id"`
	Status           string             `json:"status"`
	DateLastModified pgtype.Timestamptz `json:"date_last_modified"`
	Metadata         []byte             `json:"metadata"`
	Title            string             `json:"title"`
	Roles            []string           `json:"roles"`
	Importance       pgtype.Text        `json:"importance"`
	VendorResourceID pgtype.Text        `json:"vendor_resource_id"`
	VendorID         pgtype.Text        `json:"vendor_id"`
	ApplicationID    pgtype.Text        `json:"application_id"`
}

func (q *Queries) UpsertResource(ctx context.Context, arg UpsertResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, upsertResource,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.Title,
		arg.Roles,
		arg.Importance,
		arg.VendorResourceID,
		arg.VendorID,
		arg.ApplicationID,
	)
	var i Resource
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.Roles,
		&i.Importance,
		&i.VendorResourceID,
		&i.VendorID,
		&i.ApplicationID,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO oneroster_user (
    sourced_id, status, date_last_modified, metadata, user_master_identifier,
    username, enabled_user, given_name, family_name, middle_name,
    preferred_first_name, preferred_last_name, preferred_middle_name, pronouns,
    grades, identifier, email, sms, phone, password,
    primary_org_sourced_id, primary_org_href
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16,
    $17, $18, $19, $20, $21, $22
)
ON CONFLICT (sourced_id) DO UPDATE SET
    status                 = EXCLUDED.status,
    date_last_modified     = EXCLUDED.date_last_modified,
    metadata               = EXCLUDED.metadata,
    user_master_identifier = EXCLUDED.user_master_identifier,
    username               = EXCLUDED.username,
    enabled_user           = EXCLUDED.enabled_user,
    given_name             = EXCLUDED.given_name,
    family_name            = EXCLUDED.family_name,
    middle_name            = EXCLUDED.middle_name,
    preferred_first_name   = EXCLUDED.preferred_first_name,
    preferred_last_name    = EXCLUDED.preferred_last_name,
    preferred_middle_name  = EXCLUDED.preferred_middle_name,
    pronouns               = EXCLUDED.pronouns,
    grades                 = EXCLUDED.grades,
    identifier             = EXCLUDED.identifier,
    email                  = EXCLUDED.email,
    sms                    = EXCLUDED.sms,
    phone                  = EXCLUDED.phone,
    password               = EXCLUDED.password,
    primary_org_sourced_id = EXCLUDED.primary_org_sourced_id,
    primary_org_href       = EXCLUDED.primary_org_href
RETURNING sourced_id, status, date_last_modified, metadata, user_master_identifier, username, enabled_user, given_name, family_name, middle_name, preferred_first_name, preferred_last_name, preferred_middle_name, pronouns, grades, identifier, email, sms, phone, password, primary_org_sourced_id, primary_org_href
`

type UpsertUserParams struct {
	SourcedID            string             `json:"sourced_id"`
	Status               string             `json:"status"`
	DateLastModified     pgtype.Timestamptz `json:"date_last_modified"`
	Metadata             []byte             `json:"metadata"`
	UserMasterIdentifier pgtype.Text        `json:"user_master_identifier"`
	Username             pgtype.Text        `json:"username"`
	EnabledUser          bool               `json:"enabled_user"`
	GivenName            string             `json:"given_name"`
	FamilyName           string             `json:"family_name"`
	MiddleName           pgtype.Text        `json:"middle_name"`
	PreferredFirstName   pgtype.Text        `json:"preferred_first_name"`
	PreferredLastName    pgtype.Text        `json:"preferred_last_name"`
	PreferredMiddleName  pgtype.Text        `json:"preferred_middle_name"`
	Pronouns             pgtype.Text        `json:"pronouns"`
	Grades               []string           `json:"grades"`
	Identifier           pgtype.Text        `json:"identifier"`
	Email                pgtype.Text        `json:"email"`
	Sms                  pgtype.Text        `json:"sms"`
	Phone                pgtype.Text        `json:"phone"`
	Password             pgtype.Text        `json:"password"`
	PrimaryOrgSourcedID  pgtype.Text        `json:"primary_org_sourced_id"`
	PrimaryOrgHref       pgtype.Text        `json:"primary_org_href"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (OnerosterUser, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.SourcedID,
		arg.Status,
		arg.DateLastModified,
		arg.Metadata,
		arg.UserMasterIdentifier,
		arg.Username,
		arg.EnabledUser,
		arg.GivenName,
		arg.FamilyName,
		arg.MiddleName,
		arg.PreferredFirstName,
		arg.PreferredLastName,
		arg.PreferredMiddleName,
		arg.Pronouns,
		arg.Grades,
		arg.Identifier,
		arg.Email,
		arg.Sms,
		arg.Phone,
		arg.Password,
		arg.PrimaryOrgSourcedID,
		arg.PrimaryOrgHref,
	)
	var i OnerosterUser
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.UserMasterIdentifier,
		&i.Username,
		&i.EnabledUser,
		&i.GivenName,
		&i.FamilyName,
		&i.MiddleName,
		&i.PreferredFirstName,
		&i.PreferredLastName,
		&i.PreferredMiddleName,
		&i.Pronouns,
		&i.Grades,
		&i.Identifier,
		&i.Email,
		&i.Sms,
		&i.Phone,
		&i.Password,
		&i.PrimaryOrgSourcedID,
		&i.PrimaryOrgHref,
	)
	return i, err
}

const upsertUserProfile = `-- name: UpsertUserProfile :one
INSERT INTO user_profile (
    profile_id, user_sourced_id, profile_type, vendor_id, application_id,
    description, ordinal
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (profile_id) DO UPDATE SET
    user_sourced_id = EXCLUDED.user_sourced_id,
    profile_type    = EXCLUDED.profile_type,
    vendor_id       = EXCLUDED.vendor_id,
    application_id  = EXCLUDED.application_id,
    description     = EXCLUDED.description,
    ordinal         = EXCLUDED.ordinal
RETURNING profile_id, user_sourced_id, profile_type, vendor_id, application_id, description, ordinal
`

type UpsertUserProfileParams struct {
	ProfileID     string      `json:"profile_id"`
	UserSourcedID string      `json:"user_sourced_id"`
	ProfileType   string      `json:"profile_type"`
	VendorID      string      `json:"vendor_id"`
	ApplicationID pgtype.Text `json:"application_id"`
	Description   pgtype.Text `json:"description"`
	Ordinal       int32       `json:"ordinal"`
}

func (q *Queries) UpsertUserProfile(ctx context.Context, arg UpsertUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, upsertUserProfile,
		arg.ProfileID,
		arg.UserSourcedID,
		arg.ProfileType,
		arg.VendorID,
		arg.ApplicationID,
		arg.Description,
		arg.Ordinal,
	)
	var i UserProfile
	err := row.Scan(
		&i.ProfileID,
		&i.UserSourcedID,
		&i.ProfileType,
		&i.VendorID,
		&i.ApplicationID,
		&i.Description,
		&i.Ordinal,
	)
	return i, err
}
