// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: rostering.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAcademicSessionForSubject = `-- name: GetAcademicSessionForSubject :one
SELECT s.sourced_id, s.status, s.date_last_modified, s.metadata, s.title, s.start_date, s.end_date, s.type, s.school_year, s.parent_sourced_id, s.parent_href
FROM academic_session s
WHERE EXISTS (SELECT 1 FROM auth_effective_access a WHERE a.subject = $1::text)
  AND s.sourced_id = $2::text
`

type GetAcademicSessionForSubjectParams struct {
	Subject   string `json:"subject"`
	SourcedID string `json:"sourced_id"`
}

func (q *Queries) GetAcademicSessionForSubject(ctx context.Context, arg GetAcademicSessionForSubjectParams) (AcademicSession, error) {
	row := q.db.QueryRow(ctx, getAcademicSessionForSubject, arg.Subject, arg.SourcedID)
	var i AcademicSession
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.StartDate,
		&i.EndDate,
		&i.Type,
		&i.SchoolYear,
		&i.ParentSourcedID,
		&i.ParentHref,
	)
	return i, err
}

const getClassForSubject = `-- name: GetClassForSubject :one
SELECT DISTINCT c.sourced_id, c.status, c.date_last_modified, c.metadata, c.title, c.class_code, c.class_type, c.location, c.grades, c.subjects, c.subject_codes, c.periods, c.course_sourced_id, c.course_href, c.school_sourced_id, c.school_href
FROM class c
JOIN auth_effective_access a ON a.org_sourced_id = c.school_sourced_id
WHERE a.subject = $1::text
  AND c.sourced_id = $2::text
`

type GetClassForSubjectParams struct {
	Subject   string `json:"subject"`
	SourcedID string `json:"sourced_id"`
}

func (q *Queries) GetClassForSubject(ctx context.Context, arg GetClassForSubjectParams) (Class, error) {
	row := q.db.QueryRow(ctx, getClassForSubject, arg.Subject, arg.SourcedID)
	var i Class
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.ClassCode,
		&i.ClassType,
		&i.Location,
		&i.Grades,
		&i.Subjects,
		&i.SubjectCodes,
		&i.Periods,
		&i.CourseSourcedID,
		&i.CourseHref,
		&i.SchoolSourcedID,
		&i.SchoolHref,
	)
	return i, err
}

const getCourseForSubject = `-- name: GetCourseForSubject :one
SELECT DISTINCT c.sourced_id, c.status, c.date_last_modified, c.metadata, c.title, c.course_code, c.grades, c.subjects, c.subject_codes, c.org_sourced_id, c.org_href, c.school_year_sourced_id, c.school_year_href
FROM course c
JOIN auth_effective_access a ON a.org_sourced_id = c.org_sourced_id
WHERE a.subject = $1::text
  AND c.sourced_id = $2::text
`

type GetCourseForSubjectParams struct {
	Subject   string `json:"subject"`
	SourcedID string `json:"sourced_id"`
}

func (q *Queries) GetCourseForSubject(ctx context.Context, arg GetCourseForSubjectParams) (Course, error) {
	row := q.db.QueryRow(ctx, getCourseForSubject, arg.Subject, arg.SourcedID)
	var i Course
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Title,
		&i.CourseCode,
		&i.Grades,
		&i.Subjects,
		&i.SubjectCodes,
		&i.OrgSourcedID,
		&i.OrgHref,
		&i.SchoolYearSourcedID,
		&i.SchoolYearHref,
	)
	return i, err
}

const getDemographicsForSubject = `-- name: GetDemographicsForSubject :one
SELECT DISTINCT d.sourced_id, d.status, d.date_last_modified, d.metadata, d.birth_date, d.sex, d.american_indian_or_alaska_native, d.asian, d.black_or_african_american, d.native_hawaiian_or_other_pacific_islander, d.white, d.demographic_race_two_or_more_races, d.hispanic_or_latino_ethnicity, d.country_of_birth_code, d.state_of_birth_abbreviation, d.city_of_birth, d.public_school_residence_status
FROM demographics d
JOIN user_role r ON r.user_sourced_id = d.sourced_id
JOIN auth_effective_access a ON a.org_sourced_id = r.org_sourced_id
WHERE a.subject = $1::text
  AND d.sourced_id = $2::text
`

type GetDemographicsForSubjectParams struct {
	Subject   string `json:"subject"`
	SourcedID string `json:"sourced_id"`
}

func (q *Queries) GetDemographicsForSubject(ctx context.Context, arg GetDemographicsForSubjectParams) (Demographic, error) {
	row := q.db.QueryRow(ctx, getDemographicsForSubject, arg.Subject, arg.SourcedID)
	var i Demographic
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.BirthDate,
		&i.Sex,
		&i.AmericanIndianOrAlaskaNative,
		&i.Asian,
		&i.BlackOrAfricanAmerican,
		&i.NativeHawaiianOrOtherPacificIslander,
		&i.White,
		&i.DemographicRaceTwoOrMoreRaces,
		&i.HispanicOrLatinoEthnicity,
		&i.CountryOfBirthCode,
		&i.StateOfBirthAbbreviation,
		&i.CityOfBirth,
		&i.PublicSchoolResidenceStatus,
	)
	return i, err
}

const getEnrollmentForSubject = `-- name: GetEnrollmentForSubject :one
SELECT DISTINCT e.sourced_id, e.status, e.date_last_modified, e.metadata, e.user_sourced_id, e.user_href, e.class_sourced_id, e.class_href, e.school_sourced_id, e.school_href, e.role, e.is_primary, e.begin_date, e.end_date
FROM enrollment e
JOIN auth_effective_access a ON a.org_sourced_id = e.school_sourced_id
WHERE a.subject = $1::text
  AND e.sourced_id = $2::text
`

type GetEnrollmentForSubjectParams struct {
	Subject   string `json:"subject"`
	SourcedID string `json:"sourced_id"`
}

func (q *Queries) GetEnrollmentForSubject(ctx context.Context, arg GetEnrollmentForSubjectParams) (Enrollment, error) {
	row := q.db.QueryRow(ctx, getEnrollmentForSubject, arg.Subject, arg.SourcedID)
	var i Enrollment
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.UserSourcedID,
		&i.UserHref,
		&i.ClassSourcedID,
		&i.ClassHref,
		&i.SchoolSourcedID,
		&i.SchoolHref,
		&i.Role,
		&i.IsPrimary,
		&i.BeginDate,
		&i.EndDate,
	)
	return i, err
}

const getOrgForSubject = `-- name: GetOrgForSubject :one
SELECT DISTINCT o.sourced_id, o.status, o.date_last_modified, o.metadata, o.name, o.type, o.identifier, o.parent_sourced_id, o.parent_href
FROM org o
JOIN auth_effective_access a ON a.org_sourced_id = o.sourced_id
WHERE a.subject = $1::text
  AND o.sourced_id = $2::text
`

type GetOrgForSubjectParams struct {
	Subject   string `json:"subject"`
	SourcedID string `json:"sourced_id"`
}

func (q *Queries) GetOrgForSubject(ctx context.Context, arg GetOrgForSubjectParams) (Org, error) {
	row := q.db.QueryRow(ctx, getOrgForSubject, arg.Subject, arg.SourcedID)
	var i Org
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.Name,
		&i.Type,
		&i.Identifier,
		&i.ParentSourcedID,
		&i.ParentHref,
	)
	return i, err
}

const getUserForSubject = `-- name: GetUserForSubject :one
SELECT DISTINCT u.sourced_id, u.status, u.date_last_modified, u.metadata, u.user_master_identifier, u.username, u.enabled_user, u.given_name, u.family_name, u.middle_name, u.preferred_first_name, u.preferred_last_name, u.preferred_middle_name, u.pronouns, u.grades, u.identifier, u.email, u.sms, u.phone, u.password, u.primary_org_sourced_id, u.primary_org_href
FROM oneroster_user u
JOIN user_role r ON r.user_sourced_id = u.sourced_id
JOIN auth_effective_access a ON a.org_sourced_id = r.org_sourced_id
WHERE a.subject = $1::text
  AND u.sourced_id = $2::text
`

type GetUserForSubjectParams struct {
	Subject   string `json:"subject"`
	SourcedID string `json:"sourced_id"`
}

func (q *Queries) GetUserForSubject(ctx context.Context, arg GetUserForSubjectParams) (OnerosterUser, error) {
	row := q.db.QueryRow(ctx, getUserForSubject, arg.Subject, arg.SourcedID)
	var i OnerosterUser
	err := row.Scan(
		&i.SourcedID,
		&i.Status,
		&i.DateLastModified,
		&i.Metadata,
		&i.UserMasterIdentifier,
		&i.Username,
		&i.EnabledUser,
		&i.GivenName,
		&i.FamilyName,
		&i.MiddleName,
		&i.PreferredFirstName,
		&i.PreferredLastName,
		&i.PreferredMiddleName,
		&i.Pronouns,
		&i.Grades,
		&i.Identifier,
		&i.Email,
		&i.Sms,
		&i.Phone,
		&i.Password,
		&i.PrimaryOrgSourcedID,
		&i.PrimaryOrgHref,
	)
	return i, err
}

const listAcademicSessionsForSubject = `-- name: ListAcademicSessionsForSubject :many

SELECT s.sourced_id, s.status, s.date_last_modified, s.metadata, s.title, s.start_date, s.end_date, s.type, s.school_year, s.parent_sourced_id, s.parent_href
FROM academic_session s
WHERE EXISTS (SELECT 1 FROM auth_effective_access a WHERE a.subject = $1::text)
  AND s.status <> 'tobedeleted'
  AND ($2::text = '' OR s.type = $2::text)
  AND s.sourced_id > $3::text
ORDER BY s.sourced_id
LIMIT $4::int
`

type ListAcademicSessionsForSubjectParams struct {
	Subject        string `json:"subject"`
	SessionType    string `json:"session_type"`
	AfterSourcedID string `json:"after_sourced_id"`
	PageSize       int32  `json:"page_size"`
}

// ── AcademicSession ───────────────────────────────────────────────────────────
// Academic sessions carry no org: a school year is a property of the deployment,
// not of any one district. They are therefore readable by any principal holding
// any live grant, and the EXISTS below is that check. Scoping them per-org would
// require inventing an ownership edge the OneRoster model does not define.
func (q *Queries) ListAcademicSessionsForSubject(ctx context.Context, arg ListAcademicSessionsForSubjectParams) ([]AcademicSession, error) {
	rows, err := q.db.Query(ctx, listAcademicSessionsForSubject,
		arg.Subject,
		arg.SessionType,
		arg.AfterSourcedID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AcademicSession{}
	for rows.Next() {
		var i AcademicSession
		if err := rows.Scan(
			&i.SourcedID,
			&i.Status,
			&i.DateLastModified,
			&i.Metadata,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.Type,
			&i.SchoolYear,
			&i.ParentSourcedID,
			&i.ParentHref,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassTermsForClasses = `-- name: ListClassTermsForClasses :many
SELECT ct.class_sourced_id, ct.ordinal, ct.academic_session_href, s.sourced_id, s.status, s.date_last_modified, s.metadata, s.title, s.start_date, s.end_date, s.type, s.school_year, s.parent_sourced_id, s.parent_href
FROM class_term ct
JOIN academic_session s ON s.sourced_id = ct.academic_session_sourced_id
WHERE ct.class_sourced_id = ANY($1::text[])
ORDER BY ct.class_sourced_id, ct.ordinal
`

type ListClassTermsForClassesRow struct {
	ClassSourcedID      string             `json:"class_sourced_id"`
	Ordinal             int32              `json:"ordinal"`
	AcademicSessionHref pgtype.Text        `json:"academic_session_href"`
	SourcedID           string             `json:"sourced_id"`
	Status              string             `json:"status"`
	DateLastModified    pgtype.Timestamptz `json:"date_last_modified"`
	Metadata            []byte             `json:"metadata"`
	Title               string             `json:"title"`
	StartDate           pgtype.Date        `json:"start_date"`
	EndDate             pgtype.Date        `json:"end_date"`
	Type                string             `json:"type"`
	SchoolYear          string             `json:"school_year"`
	ParentSourcedID     pgtype.Text        `json:"parent_sourced_id"`
	ParentHref          pgtype.Text        `json:"parent_href"`
}

// Association load for a page of classes, batched by class id rather than issued
// once per class: PostgreSQL is a remote server, so N+1 here would be N round
// trips. Returns the terms of every requested class at once; the caller groups
// them by class_sourced_id.
func (q *Queries) ListClassTermsForClasses(ctx context.Context, classSourcedIds []string) ([]ListClassTermsForClassesRow, error) {
	rows, err := q.db.Query(ctx, listClassTermsForClasses, classSourcedIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassTermsForClassesRow{}
	for rows.Next() {
		var i ListClassTermsForClassesRow
		if err := rows.Scan(
			&i.ClassSourcedID,
			&i.Ordinal,
			&i.AcademicSessionHref,
			&i.SourcedID,
			&i.Status,
			&i.DateLastModified,
			&i.Metadata,
			&i.Title,
			&i.StartDate,
			&i.EndDate,
			&i.Type,
			&i.SchoolYear,
			&i.ParentSourcedID,
			&i.ParentHref,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesForSubject = `-- name: ListClassesForSubject :many

SELECT DISTINCT c.sourced_id, c.status, c.date_last_modified, c.metadata, c.title, c.class_code, c.class_type, c.location, c.grades, c.subjects, c.subject_codes, c.periods, c.course_sourced_id, c.course_href, c.school_sourced_id, c.school_href
FROM class c
JOIN auth_effective_access a ON a.org_sourced_id = c.school_sourced_id
WHERE a.subject = $1::text
  AND c.status <> 'tobedeleted'
  AND ($2::text = '' OR c.school_sourced_id IN (
        SELECT descendant_sourced_id FROM org_closure
        WHERE ancestor_sourced_id = $2::text))
  AND c.sourced_id > $3::text
ORDER BY c.sourced_id
LIMIT $4::int
`

type ListClassesForSubjectParams struct {
	Subject        string `json:"subject"`
	OrgSourcedID   string `json:"org_sourced_id"`
	AfterSourcedID string `json:"after_sourced_id"`
	PageSize       int32  `json:"page_size"`
}

// ── Class ─────────────────────────────────────────────────────────────────────
func (q *Queries) ListClassesForSubject(ctx context.Context, arg ListClassesForSubjectParams) ([]Class, error) {
	rows, err := q.db.Query(ctx, listClassesForSubject,
		arg.Subject,
		arg.OrgSourcedID,
		arg.AfterSourcedID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.SourcedID,
			&i.Status,
			&i.DateLastModified,
			&i.Metadata,
			&i.Title,
			&i.ClassCode,
			&i.ClassType,
			&i.Location,
			&i.Grades,
			&i.Subjects,
			&i.SubjectCodes,
			&i.Periods,
			&i.CourseSourcedID,
			&i.CourseHref,
			&i.SchoolSourcedID,
			&i.SchoolHref,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoursesForSubject = `-- name: ListCoursesForSubject :many

SELECT DISTINCT c.sourced_id, c.status, c.date_last_modified, c.metadata, c.title, c.course_code, c.grades, c.subjects, c.subject_codes, c.org_sourced_id, c.org_href, c.school_year_sourced_id, c.school_year_href
FROM course c
JOIN auth_effective_access a ON a.org_sourced_id = c.org_sourced_id
WHERE a.subject = $1::text
  AND c.status <> 'tobedeleted'
  AND ($2::text = '' OR c.org_sourced_id IN (
        SELECT descendant_sourced_id FROM org_closure
        WHERE ancestor_sourced_id = $2::text))
  AND c.sourced_id > $3::text
ORDER BY c.sourced_id
LIMIT $4::int
`

type ListCoursesForSubjectParams struct {
	Subject        string `json:"subject"`
	OrgSourcedID   string `json:"org_sourced_id"`
	AfterSourcedID string `json:"after_sourced_id"`
	PageSize       int32  `json:"page_size"`
}

// ── Course ────────────────────────────────────────────────────────────────────
func (q *Queries) ListCoursesForSubject(ctx context.Context, arg ListCoursesForSubjectParams) ([]Course, error) {
	rows, err := q.db.Query(ctx, listCoursesForSubject,
		arg.Subject,
		arg.OrgSourcedID,
		arg.AfterSourcedID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.SourcedID,
			&i.Status,
			&i.DateLastModified,
			&i.Metadata,
			&i.Title,
			&i.CourseCode,
			&i.Grades,
			&i.Subjects,
			&i.SubjectCodes,
			&i.OrgSourcedID,
			&i.OrgHref,
			&i.SchoolYearSourcedID,
			&i.SchoolYearHref,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDemographicsForSubject = `-- name: ListDemographicsForSubject :many

SELECT DISTINCT d.sourced_id, d.status, d.date_last_modified, d.metadata, d.birth_date, d.sex, d.american_indian_or_alaska_native, d.asian, d.black_or_african_american, d.native_hawaiian_or_other_pacific_islander, d.white, d.demographic_race_two_or_more_races, d.hispanic_or_latino_ethnicity, d.country_of_birth_code, d.state_of_birth_abbreviation, d.city_of_birth, d.public_school_residence_status
FROM demographics d
JOIN user_role r ON r.user_sourced_id = d.sourced_id
JOIN auth_effective_access a ON a.org_sourced_id = r.org_sourced_id
WHERE a.subject = $1::text
  AND d.status <> 'tobedeleted'
  AND ($2::text = '' OR r.org_sourced_id IN (
        SELECT descendant_sourced_id FROM org_closure
        WHERE ancestor_sourced_id = $2::text))
  AND d.sourced_id > $3::text
ORDER BY d.sourced_id
LIMIT $4::int
`

type ListDemographicsForSubjectParams struct {
	Subject        string `json:"subject"`
	OrgSourcedID   string `json:"org_sourced_id"`
	AfterSourcedID string `json:"after_sourced_id"`
	PageSize       int32  `json:"page_size"`
}

// ── Demographics ──────────────────────────────────────────────────────────────
// Demographics share the user's sourced_id, so visibility follows the user's.
func (q *Queries) ListDemographicsForSubject(ctx context.Context, arg ListDemographicsForSubjectParams) ([]Demographic, error) {
	rows, err := q.db.Query(ctx, listDemographicsForSubject,
		arg.Subject,
		arg.OrgSourcedID,
		arg.AfterSourcedID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Demographic{}
	for rows.Next() {
		var i Demographic
		if err := rows.Scan(
			&i.SourcedID,
			&i.Status,
			&i.DateLastModified,
			&i.Metadata,
			&i.BirthDate,
			&i.Sex,
			&i.AmericanIndianOrAlaskaNative,
			&i.Asian,
			&i.BlackOrAfricanAmerican,
			&i.NativeHawaiianOrOtherPacificIslander,
			&i.White,
			&i.DemographicRaceTwoOrMoreRaces,
			&i.HispanicOrLatinoEthnicity,
			&i.CountryOfBirthCode,
			&i.StateOfBirthAbbreviation,
			&i.CityOfBirth,
			&i.PublicSchoolResidenceStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnrollmentsForSubject = `-- name: ListEnrollmentsForSubject :many

SELECT DISTINCT e.sourced_id, e.status, e.date_last_modified, e.metadata, e.user_sourced_id, e.user_href, e.class_sourced_id, e.class_href, e.school_sourced_id, e.school_href, e.role, e.is_primary, e.begin_date, e.end_date
FROM enrollment e
JOIN auth_effective_access a ON a.org_sourced_id = e.school_sourced_id
WHERE a.subject = $1::text
  AND e.status <> 'tobedeleted'
  AND ($2::text = '' OR e.school_sourced_id IN (
        SELECT descendant_sourced_id FROM org_closure
        WHERE ancestor_sourced_id = $2::text))
  AND e.sourced_id > $3::text
ORDER BY e.sourced_id
LIMIT $4::int
`

type ListEnrollmentsForSubjectParams struct {
	Subject        string `json:"subject"`
	OrgSourcedID   string `json:"org_sourced_id"`
	AfterSourcedID string `json:"after_sourced_id"`
	PageSize       int32  `json:"page_size"`
}

// ── Enrollment ────────────────────────────────────────────────────────────────
func (q *Queries) ListEnrollmentsForSubject(ctx context.Context, arg ListEnrollmentsForSubjectParams) ([]Enrollment, error) {
	rows, err := q.db.Query(ctx, listEnrollmentsForSubject,
		arg.Subject,
		arg.OrgSourcedID,
		arg.AfterSourcedID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Enrollment{}
	for rows.Next() {
		var i Enrollment
		if err := rows.Scan(
			&i.SourcedID,
			&i.Status,
			&i.DateLastModified,
			&i.Metadata,
			&i.UserSourcedID,
			&i.UserHref,
			&i.ClassSourcedID,
			&i.ClassHref,
			&i.SchoolSourcedID,
			&i.SchoolHref,
			&i.Role,
			&i.IsPrimary,
			&i.BeginDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrgsForSubject = `-- name: ListOrgsForSubject :many


SELECT DISTINCT o.sourced_id, o.status, o.date_last_modified, o.metadata, o.name, o.type, o.identifier, o.parent_sourced_id, o.parent_href
FROM org o
JOIN auth_effective_access a ON a.org_sourced_id = o.sourced_id
WHERE a.subject = $1::text
  AND o.status <> 'tobedeleted'
  AND o.sourced_id > $2::text
ORDER BY o.sourced_id
LIMIT $3::int
`

type ListOrgsForSubjectParams struct {
	Subject        string `json:"subject"`
	AfterSourcedID string `json:"after_sourced_id"`
	PageSize       int32  `json:"page_size"`
}

// Subject-scoped rostering reads: every query the RPC service issues.
//
// Two invariants hold for every query in this file, and there is deliberately no
// unscoped variant of any of them — an unscoped read would be the easier call to
// reach for, and reaching for it would silently disable authorization.
//
//  1. Authorization is in the query. Each read joins auth_effective_access on
//     the entity's owning org and filters by the calling subject, so the
//     database never materializes a row the caller may not see. Filtering in Go
//     after an unscoped read would move that decision into the handler, where a
//     missed branch leaks data.
//
//  2. Paging is keyset, not offset. `sourced_id` is the primary key and
//     therefore a total order, so `sourced_id > @after_sourced_id` resumes
//     exactly where the previous page stopped. Rosters are rewritten by bulk
//     imports; under OFFSET that traffic makes pages skip and repeat rows.
//     An empty @after_sourced_id starts at the first page, because ” sorts
//     before every non-empty identifier.
//
// DISTINCT throughout: a principal holding two roles over the same org matches
// auth_effective_access twice, which would otherwise duplicate the entity.
//
// Entities whose owning org is NULL (a course with no org) match no row in
// auth_effective_access and are therefore invisible to everyone. That is
// intentional — an unowned row has no scope to check, so it fails closed.
// ── Org ───────────────────────────────────────────────────────────────────────
func (q *Queries) ListOrgsForSubject(ctx context.Context, arg ListOrgsForSubjectParams) ([]Org, error) {
	rows, err := q.db.Query(ctx, listOrgsForSubject, arg.Subject, arg.AfterSourcedID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Org{}
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.SourcedID,
			&i.Status,
			&i.DateLastModified,
			&i.Metadata,
			&i.Name,
			&i.Type,
			&i.Identifier,
			&i.ParentSourcedID,
			&i.ParentHref,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSchoolsForSubject = `-- name: ListSchoolsForSubject :many
SELECT DISTINCT o.sourced_id, o.status, o.date_last_modified, o.metadata, o.name, o.type, o.identifier, o.parent_sourced_id, o.parent_href
FROM org o
JOIN auth_effective_access a ON a.org_sourced_id = o.sourced_id
WHERE a.subject = $1::text
  AND o.type = 'school'
  AND o.status <> 'tobedeleted'
  AND o.sourced_id > $2::text
ORDER BY o.sourced_id
LIMIT $3::int
`

type ListSchoolsForSubjectParams struct {
	Subject        string `json:"subject"`
	AfterSourcedID string `json:"after_sourced_id"`
	PageSize       int32  `json:"page_size"`
}

func (q *Queries) ListSchoolsForSubject(ctx context.Context, arg ListSchoolsForSubjectParams) ([]Org, error) {
	rows, err := q.db.Query(ctx, listSchoolsForSubject, arg.Subject, arg.AfterSourcedID, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Org{}
	for rows.Next() {
		var i Org
		if err := rows.Scan(
			&i.SourcedID,
			&i.Status,
			&i.DateLastModified,
			&i.Metadata,
			&i.Name,
			&i.Type,
			&i.Identifier,
			&i.ParentSourcedID,
			&i.ParentHref,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAgentsForUsers = `-- name: ListUserAgentsForUsers :many
SELECT user_sourced_id, agent_sourced_id, agent_href, ordinal
FROM user_agent
WHERE user_sourced_id = ANY($1::text[])
ORDER BY user_sourced_id, ordinal
`

func (q *Queries) ListUserAgentsForUsers(ctx context.Context, userSourcedIds []string) ([]UserAgent, error) {
	rows, err := q.db.Query(ctx, listUserAgentsForUsers, userSourcedIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserAgent{}
	for rows.Next() {
		var i UserAgent
		if err := rows.Scan(
			&i.UserSourcedID,
			&i.AgentSourcedID,
			&i.AgentHref,
			&i.Ordinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserIdentifiersForUsers = `-- name: ListUserIdentifiersForUsers :many
SELECT id, user_sourced_id, type, identifier, ordinal FROM user_identifier
WHERE user_sourced_id = ANY($1::text[])
ORDER BY user_sourced_id, ordinal
`

func (q *Queries) ListUserIdentifiersForUsers(ctx context.Context, userSourcedIds []string) ([]UserIdentifier, error) {
	rows, err := q.db.Query(ctx, listUserIdentifiersForUsers, userSourcedIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserIdentifier{}
	for rows.Next() {
		var i UserIdentifier
		if err := rows.Scan(
			&i.ID,
			&i.UserSourcedID,
			&i.Type,
			&i.Identifier,
			&i.Ordinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRolesForUsers = `-- name: ListUserRolesForUsers :many
SELECT id, user_sourced_id, user_href, role_type, role, org_sourced_id, org_href, begin_date, end_date, user_profile, ordinal FROM user_role
WHERE user_sourced_id = ANY($1::text[])
ORDER BY user_sourced_id, ordinal
`

// Batched association load for a page of users; see ListClassTermsForClasses.
func (q *Queries) ListUserRolesForUsers(ctx context.Context, userSourcedIds []string) ([]UserRole, error) {
	rows, err := q.db.Query(ctx, listUserRolesForUsers, userSourcedIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRole{}
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(
			&i.ID,
			&i.UserSourcedID,
			&i.UserHref,
			&i.RoleType,
			&i.Role,
			&i.OrgSourcedID,
			&i.OrgHref,
			&i.BeginDate,
			&i.EndDate,
			&i.UserProfile,
			&i.Ordinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersForSubject = `-- name: ListUsersForSubject :many

SELECT DISTINCT u.sourced_id, u.status, u.date_last_modified, u.metadata, u.user_master_identifier, u.username, u.enabled_user, u.given_name, u.family_name, u.middle_name, u.preferred_first_name, u.preferred_last_name, u.preferred_middle_name, u.pronouns, u.grades, u.identifier, u.email, u.sms, u.phone, u.password, u.primary_org_sourced_id, u.primary_org_href
FROM oneroster_user u
JOIN user_role r ON r.user_sourced_id = u.sourced_id
JOIN auth_effective_access a ON a.org_sourced_id = r.org_sourced_id
WHERE a.subject = $1::text
  AND u.status <> 'tobedeleted'
  AND ($2::text = '' OR r.role = $2::text)
  AND ($3::text = '' OR r.org_sourced_id IN (
        SELECT descendant_sourced_id FROM org_closure
        WHERE ancestor_sourced_id = $3::text))
  AND u.sourced_id > $4::text
ORDER BY u.sourced_id
LIMIT $5::int
`

type ListUsersForSubjectParams struct {
	Subject        string `json:"subject"`
	Role           string `json:"role"`
	OrgSourcedID   string `json:"org_sourced_id"`
	AfterSourcedID string `json:"after_sourced_id"`
	PageSize       int32  `json:"page_size"`
}

// ── User ──────────────────────────────────────────────────────────────────────
// A user is scoped through the orgs their roles name, not through primary_org:
// primary_org is nullable and a user may legitimately hold roles at several
// schools, so the role edge is the one that decides visibility.
func (q *Queries) ListUsersForSubject(ctx context.Context, arg ListUsersForSubjectParams) ([]OnerosterUser, error) {
	rows, err := q.db.Query(ctx, listUsersForSubject,
		arg.Subject,
		arg.Role,
		arg.OrgSourcedID,
		arg.AfterSourcedID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OnerosterUser{}
	for rows.Next() {
		var i OnerosterUser
		if err := rows.Scan(
			&i.SourcedID,
			&i.Status,
			&i.DateLastModified,
			&i.Metadata,
			&i.UserMasterIdentifier,
			&i.Username,
			&i.EnabledUser,
			&i.GivenName,
			&i.FamilyName,
			&i.MiddleName,
			&i.PreferredFirstName,
			&i.PreferredLastName,
			&i.PreferredMiddleName,
			&i.Pronouns,
			&i.Grades,
			&i.Identifier,
			&i.Email,
			&i.Sms,
			&i.Phone,
			&i.Password,
			&i.PrimaryOrgSourcedID,
			&i.PrimaryOrgHref,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
